Repository camunda/camunda-bpm-platform, pull requests merged in 2019-10, with the labels that each got.

#480 CAM-10808: add support for WildFly 18
  distro/wildfly/assembly/src/wildfly/standalone-full.xml
  distro/wildfly/assembly/src/wildfly/standalone.xml
  parent/pom.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml
  qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
Labels: wildfly

#491 CAM-10871: mark variable expression context as resolved
  engine/src/main/java/org/camunda/bpm/engine/impl/el/VariableScopeElResolver.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ValueIncreasingListener.java
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.testSetVariableByExpressionFromListener.bpmn20.xml
Labels: postgresql

#490 CAM-10842
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/TaskListenerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobAcquisitionBackoffIdleTest.java
Labels: tomcat

#482 [CAM-10851] bump jackson to version 2.10.0
  bom/pom.xml
  distro/jbossas7/modules/src/main/modules/com/fasterxml/jackson/core/jackson-annotations/main/module.xml
  distro/jbossas7/modules/src/main/modules/com/fasterxml/jackson/core/jackson-core/main/module.xml
  distro/jbossas7/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/main/module.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-annotations/2.10.0/module.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-core/2.10.0/module.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/2.10.0/module.xml
  distro/wildfly8/modules/pom.xml
  distro/wildfly8/modules/src/main/modules/com/fasterxml/jackson/core/jackson-annotations/2.10.0/module.xml
  distro/wildfly8/modules/src/main/modules/com/fasterxml/jackson/core/jackson-core/2.10.0/module.xml
  distro/wildfly8/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/2.10.0/module.xml
  engine-rest/pom.xml
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/resources-wildfly/jboss-deployment-structure-spin-json.xml
Labels: all-as

#488 CAM-10865 add annotation during process instance modification
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/ModificationDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/modification/ProcessInstanceModificationDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ModificationRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/ProcessInstanceResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ModificationRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ModificationBuilderImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceModificationBuilderImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractModificationCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ModifyProcessInstanceAsyncCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ModifyProcessInstanceCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ProcessInstanceModificationBatchCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ProcessInstanceModificationCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/StartProcessInstanceAtActivitiesCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/oplog/UserOperationLogContextEntry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/oplog/UserOperationLogContextEntryBuilder.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/UserOperationLogManager.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/ModificationBuilder.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/ProcessInstanceModificationBuilder.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ModificationUserOperationLogTest.java
Labels: all-db

#498 CAM-10627: chore(engine): log bpmn stack trace on level DEBUG
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ContextLogger.java
Labels: postgresql

#494 CAM-10887: Historic activity instance statistics selection by process instance id
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/history/HistoricProcessDefinitionRestService.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricActivityStatisticsQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricProcessDefinitionRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityStatisticsRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricActivityStatisticsQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricActivityStatisticsQueryImpl.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricStatistics.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricActivityStatisticsQueryTest.java
Labels: all-db

#500 [CAM-10879] fix module.xml descriptors of json-smart
  distro/jbossas7/modules/src/main/modules/net/minidev/json-smart/main/module.xml
  distro/wildfly/modules/src/main/modules/net/minidev/json-smart/main/module.xml
  distro/wildfly8/modules/src/main/modules/net/minidev/json-smart/main/module.xml
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/spin/SpinJsonPathTest.java
  qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/jsonpath-process.bpmn
Labels: all-as

#505 [CAM-10829] fix prefix of angular bootstrap ui directive in form engine
  engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/HtmlFormEngine.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/HtmlFormEngineTest.testRenderDateField.html
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/HtmlFormEngineTest.testRenderDateFieldWithPattern.html
Labels: postgresql

#501 CAM-10802: fix(engine): fix update user when password policy is enabled
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SaveUserCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/UserEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/identity/CustomPasswordPolicyTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/identity/DefaultPasswordPolicyTest.java
Labels: all-db

#504 CAM-10864 adjust variable ignore case queries
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/CaseExecution.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Commons.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Execution.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricCaseInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/VariableInstanceAuthorizationTest.java
Labels: all-db

#507 CAM-10724: feat(engine): define task event lifecycle
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/AbstractTaskListenerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/TaskListenerErrorThrowTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/TaskListenerEventLifecycleTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/TaskListenerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/util/RecorderTaskListener.java
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/tasklistener/TaskListenerErrorThrowTest.testThrowErrorOnCreateScriptListenerAndCatchOnUserTask.bpmn20.xml
Labels: wildfly

#506 CAM-10904: improve(engine-tests): pin time in locked user tests
  engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceTest.java
Labels: all-db

#509 fix(engine): replace MDC usage by commons facade
  bom/pom.xml
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataLoggingContext.java
Labels: wildfly

#511 CAM-10903: task or query with involved user
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/usertask/TaskCandidateTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/usertask/groupTest.bpmn
Labels: all-db

#510 CAM-10910: idIn parameter for group query
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/GroupRestService.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/identity/GroupQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/GroupRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/GroupRestServiceQueryTest.java
Labels: rest-api

#514 CAM-9653: remove unnecessary synchronization
  engine/src/main/java/org/camunda/bpm/engine/impl/cmmn/model/CaseDefinitionBuilder.java
  engine/src/main/java/org/camunda/bpm/engine/impl/context/Context.java
  engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/HtmlDocumentBuilder.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/ProcessDefinitionBuilder.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/xml/ParseHandler.java
Labels: wildfly

#517 CAM-10918: bump surefire to 2.22.2
  engine-dmn/pom.xml
  parent/pom.xml
Labels: all-as

#522 CAM-10889: task UPDATE event for attachment, comment, variables
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractVariableCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AddCommentCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CreateAttachmentCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteAttachmentCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SaveAttachmentCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskVariablesCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/TaskListenerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/util/RecorderTaskListener.java
Labels: all-db

#527 CAM-10923: chore(qa): add commons testing
  qa/test-db-upgrade/pom.xml
Labels: rolling-update

#516 CAM-10374: add JAXB to webapp-standalone
  distro/tomcat/webapp-standalone/pom.xml
Labels: tomcat

#525 CAM-10939: query incidents by process definition key
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/IncidentQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncidentQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricIncidentQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/IncidentQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/IncidentQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Incident.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/IncidentQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentQueryTest.java
Labels: all-db
