Repository camunda/camunda-bpm-platform, pull requests merged in 2019-06, with the labels that each got.

#346 CAM-5164 : avoid NPE on deploy with history 'auto'
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/dmn/configuration/DmnEngineConfigurationBuilder.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/ActivityInstanceEndListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/ActivityInstanceStartListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/ActivityInstanceUpdateListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/HistoryDecisionEvaluationListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/HistoryExecutionListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/HistoryParseListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/HistoryTaskListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/ProcessInstanceEndListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/ProcessInstanceStartListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/parser/ProcessInstanceUpdateListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/transformer/CaseActivityInstanceCreateListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/transformer/CaseActivityInstanceEndListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/transformer/CaseActivityInstanceUpdateListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/transformer/CaseInstanceCloseListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/transformer/CaseInstanceCreateListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/transformer/CaseInstanceUpdateListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/transformer/CmmnHistoryTransformListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/transformer/HistoryCaseExecutionListener.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/deploy/DeploymentAutoHistoryTest.java
Labels: h2

#348 [CAM-9938] Only log stacktrace of OptimisticLockingException on DEBUG
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutorLogger.java
Labels: all-db

#357 Add #processDefinitionKeyIn() and #processDefinitionKeyNotIn() in HistoricProcessInstanceQuery and ProcessInstanceQuery
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/ProcessInstanceQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Execution.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
Labels: all-db

#359 [CAM-9114] fix(engine): correct results for or queries with multiple joins
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java
Labels: all-db

#356 Add missing "and" operator in historic detail query
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricDetailQueryTest.java
Labels: all-db

#355 Expose DelegateTask#getFollowUpDate() and DelegateTask#setFollowUpDate()
  engine/src/main/java/org/camunda/bpm/engine/delegate/DelegateTask.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/DelegateTaskTest.java
Labels: postgresql

#358 Update LICENSE and NOTICE files in distros
  distro/jbossas7/assembly/assembly.xml
  distro/jbossas7/webapp-standalone/pom.xml
  distro/license/LICENSE.txt
  distro/license/NOTICE.txt
  distro/tomcat/assembly/assembly.xml
  distro/tomcat/assembly/src/LICENSE-2.0.txt
  distro/tomcat/webapp-standalone/pom.xml
  distro/wildfly/assembly/assembly.xml
  distro/wildfly/assembly/src/LICENSE-2.0.txt
Labels: all-as

#363 [CAM-9837] remove inner select * from job acquisition query
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
Labels: all-db

#362 [CAM-10067] configuration for exception logging during cmd/job execution
  engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ProcessEngineLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobHelper.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/CmdExceptionLoggingTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExceptionLoggingTest.java
Labels: all-as

#361 [CAM-10087] feat(engine): enable XML secure processing
  engine/src/main/java/org/camunda/bpm/engine/impl/util/xml/Parse.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseProcessDefinitionFSP.bpmn20.xml
Labels: postgresql
