Repository camunda/camunda-bpm-platform, pull requests merged in 2019-09, with the labels that each got.

#457 CAM-10760: improve docs for classloader switch during job execution
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
  javaee/jobexecutor-ra/src/main/java/org/camunda/bpm/container/impl/threading/ra/inflow/JcaInflowExecuteJobsRunnable.java
Labels: all-as

#460 CAM-10398 Handle bpmn error in user task
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/ExternalTaskBpmnError.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskBpmnErrorDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/TaskResource.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/TaskService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/ExternalTaskActivityBehavior.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleTaskBpmnErrorCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/task/HandleTaskBpmnErrorAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
Labels: all-db

#459 CAM-10672: link historic incidents to correct stacktrace
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncident.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncidentQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricIncidentQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricIncidentQueryProperty.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricIncidentEventEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoryEventProcessor.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/incident/IncidentContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricExternalTaskLogManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricIncidentManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricJobLogManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/IncidentEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/test/AbstractProcessEngineTestCase.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/Incident.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricExternalTaskLogTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentTest.java
Labels: all-db

#462 CAM-10397: escalation event can be handled in user task
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskEscalationDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/TaskResource.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/TaskService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/BpmnBehaviorLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/ThrowEscalationEventActivityBehavior.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/helper/EscalationEventDefinitionFinder.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/helper/EscalationHandler.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CommandLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleTaskEscalationCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/task/HandleTaskAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/escalation/EscalationEventParseInvalidProcessTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/task/TaskServiceTest.handleUserTaskEscalation.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/escalation/EscalationEventParseInvalidProcessTest.invalidAttachement.bpmn20.xml
Labels: all-db

#456 [CAM-10693]: expose versionTag to fetched external tasks
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/helper/MockExternalTaskBuilder.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/LockedExternalTaskDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockExternalTaskBuilder.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
Labels: wildfly

#470 CAM-10815: low-hanging fruit bootstrap rule conversions
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/batch/HistoricBatchQueryAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/cfg/DeploymentCacheCfgTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/form/FormServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/BulkHistoryDeleteCmmnDisabledTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/BulkHistoryDeleteDmnDisabledTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryCleanupBatchWindowForEveryDayTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryCleanupDmnDisabledTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryCleanupHistoricBatchTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryCleanupTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/AbstractHistoryCleanupSchedulerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerActivityInstancesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerAttachmentsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerBatchesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerCommentsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerDecisionsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerDetailsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerExternalTaskLogsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerIdentityLinkLogsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerIncidentsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerJobLogTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerProcessInstancesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerTaskInstancesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerUserOperationLogsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerVariableInstancesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceWithJdbcSimpleProcessingTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/MultiTenancySharedDefinitionPropagationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/suspensionstate/MultiTenancyProcessDefinitionSuspensionStateTenantIdProviderTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/CreateAndResolveIncidentTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/MessageCorrelationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstantiationWithVariablesInReturnTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/MigrationVariablesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceWithJdbcSimpleProcessingTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/variables/JavaSerializationProhibitedTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/variables/JavaSerializationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/error/UnhandledBpmnErrorTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/message/MessageIntermediateEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventPayloadTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/CleanableHistoricBatchReportTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/DeploymentAwareJobExecutorForOracleTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/FailedJobListenerWithRetriesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobDefinitionCreationAndDeletionWithParseListenerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobDefinitionCreationBothAsyncWithParseListenerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobDefinitionCreationWithParseListenerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobDefinitionDeletionWithParseListenerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/CustomHistoryLevelIdentityLinkTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/CustomHistoryLevelIncidentTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/CustomHistoryLevelUserOperationLogTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/CustomHistoryLevelWithoutUserOperationLogTest.java
Labels: all-db

#468 CAM-10745: chore(deps): bump tomcat to 9.0.24
  parent/pom.xml
Labels: tomcat

#464 [CAM-9855]: cascade timer duedate changes to subsequent timers
  engine/src/main/java/org/camunda/bpm/engine/ManagementService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/calendar/CycleBusinessCalendar.java
  engine/src/main/java/org/camunda/bpm/engine/impl/calendar/DurationHelper.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetJobDuedateCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TimerEntity.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/UpdateDuedateOnRecurringTimerTest.java
Labels: all-db

#466 [CAM-9855] Expose "cascade" flag to /job/{id}/duedate REST endpoint
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobDuedateDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/JobResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.11_to_7.12.sql
Labels: rest-api
