Repository camunda/camunda-bpm-platform, pull requests merged in 2019-12, with the labels that each got.

#551 CAM-11104: chore(engine): remove oracle 10 code
  database/pom.xml
  engine/pom.xml
Labels: all-db

#565 [CAM-11032] chore(old-engine): use explicit version numbers
  qa/test-old-engine/pom.xml
Labels: migration

#557 correct state for externally canceled subprocess
  engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceModificationBuilderImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractDeleteProcessInstanceCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractInstanceCancellationCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractInstantiationCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractProcessInstanceModificationCommand.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ModifyProcessInstanceCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationDeleteCascade.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceTerminationCascadeStateTest.java
Labels: h2

#554 Adjust renamed tomcat property maxActive to maxTotal
  distro/tomcat/assembly/src/conf/server.xml
  qa/tomcat-runtime/src/main/conf/server.xml
Labels: tomcat

#577 CAM-11151 chore(rest): remove unreferenced class
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/hal/tenant/HalTenantResolver.java
Labels: rest-api

#572 CAM-11149 feat(engine/rest): make unlimited queries public api
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessDefinitionRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricCaseDefinitionRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricDecisionStatisticsRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricProcessDefinitionRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/impl/ProcessDefinitionResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/FilterResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/StatisticsRestTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityStatisticsRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricCaseActivityStatisticsRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDecisionStatisticsRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/AbstractQuery.java
  engine/src/main/java/org/camunda/bpm/engine/query/Query.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/queries/BoundedNumberOfMaxResultsTest.java
Labels: rest-api

#559 CAM-11117: fix(db): add historic act inst start-end-time index
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.db2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.h2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mariadb.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mssql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mysql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.oracle.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.postgres.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.10_patch_7.10.13_to_7.10.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.11_patch_7.11.7_to_7.11.8.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.12_patch_7.12.0_to_7.12.1.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.10_patch_7.10.13_to_7.10.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.11_patch_7.11.7_to_7.11.8.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.12_patch_7.12.0_to_7.12.1.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.10_patch_7.10.13_to_7.10.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.11_patch_7.11.7_to_7.11.8.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.12_patch_7.12.0_to_7.12.1.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.10_patch_7.10.13_to_7.10.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.11_patch_7.11.7_to_7.11.8.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.12_patch_7.12.0_to_7.12.1.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.10_patch_7.10.13_to_7.10.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.11_patch_7.11.7_to_7.11.8.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.12_patch_7.12.0_to_7.12.1.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.10_patch_7.10.13_to_7.10.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.11_patch_7.11.7_to_7.11.8.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.12_patch_7.12.0_to_7.12.1.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.10_patch_7.10.13_to_7.10.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.11_patch_7.11.7_to_7.11.8.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.12_patch_7.12.0_to_7.12.1.sql
Labels: all-db

#578 CAM-11131: Improve cancellation API
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/ProcessInstanceResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstanceModificationBuilderImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractDeleteProcessInstanceCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/ProcessInstanceModificationBuilder.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceTerminationCascadeStateTest.java
Labels: h2

#580 CAM-11108 chore(database): remove jdbc drivers for db2 9.7 & 10.1
  database/pom.xml
Labels: all-db

#574 CAM-11148 fix(rest): make group query in check auth resource unlimited
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/AuthorizationRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AuthorizationRestServiceInteractionTest.java
Labels: rest-api

#570 CAM-11118 fix(engine/rest): remove query limit for historic query based operations
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessInstanceRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/ManagementService.java
  engine/src/main/java/org/camunda/bpm/engine/RuntimeService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/RuntimeServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/SetJobsRetriesByProcessBatchCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/batch/DeleteProcessInstanceBatchCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceAsyncOperationsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceAsyncOperationsTest.java
Labels: oracle

#583 fix(db): adjust drop index statement for mysql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.12_patch_7.12.0_to_7.12.1.sql
Labels: migration

#575 CAM-11150 fix(rest): make groups query unlimited in groups info resource
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/IdentityRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IdentityRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessEngineRestServiceTest.java
Labels: rest-api

#573 CAM-9571: fix(engine): unlock job with custom retries when fails
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DefaultJobRetryCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/async/FoxJobRetryCmdTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/RetryIntervalsConfigurationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentJobExecutorTest.java
  qa/test-db-instance-migration/test-fixture-712/src/main/java/org/camunda/bpm/qa/upgrade/TestFixture.java
  qa/test-db-instance-migration/test-fixture-712/src/main/java/org/camunda/bpm/qa/upgrade/customretries/FailingIntermediateBoundaryTimerJobScenario.java
  qa/test-db-instance-migration/test-fixture-712/src/main/resources/org/camunda/bpm/qa/upgrade/customretries/failingTimerJob.bpmn20.xml
  qa/test-db-instance-migration/test-migration/src/test/java/org/camunda/bpm/qa/upgrade/scenarios7130/customretries/FailingIntermediateBoundaryTimerJobTest.java
Labels: oracle

#576 CAM-11102: chore(qa): remove jboss it tests
  README.md
  qa/README.md
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/java-wildfly-servlet/org/camunda/bpm/integrationtest/util/TestConstants.java
  qa/integration-tests-engine/src/test/java-wildfly-servlet/org/camunda/bpm/integrationtest/util/TestContainer.java
  qa/integration-tests-engine/src/test/java-wildfly-servlet/org/camunda/bpm/integrationtest/util/TestProcessApplication.java
  qa/integration-tests-engine/src/test/java-wildfly/org/camunda/bpm/integrationtest/util/TestConstants.java
  qa/integration-tests-engine/src/test/java-wildfly/org/camunda/bpm/integrationtest/util/TestContainer.java
  qa/integration-tests-engine/src/test/java-wildfly/org/camunda/bpm/integrationtest/util/TestProcessApplication.java
  qa/integration-tests-engine/src/test/resources-jboss-domain/arquillian.xml
  qa/integration-tests-engine/src/test/resources-jboss-remote/arquillian.xml
  qa/integration-tests-engine/src/test/resources-jboss/arquillian.xml
  qa/integration-tests-engine/src/test/resources-jboss/jboss-deployment-structure-spin-json.xml
  qa/integration-tests-engine/src/test/resources-jboss/jboss-deployment-structure.xml
  qa/integration-tests-engine/src/test/resources-wildfly/arquillian.xml
  qa/integration-tests-engine/src/test/resources-wildfly/jobExecutorActivate-processes.xml
  qa/integration-tests-engine/src/test/resources-wildfly/org/camunda/bpm/integrationtest/jobexecutor/IndependentJobExecutionTest.pa1.xml
  qa/integration-tests-engine/src/test/resources-wildfly/org/camunda/bpm/integrationtest/paOnEngine1.xml
  qa/integration-tests-engine/src/test/resources-wildfly/org/camunda/bpm/integrationtest/processes-javaSerializationEnabled-pa1.xml
  qa/integration-tests-engine/src/test/resources-wildfly/org/camunda/bpm/integrationtest/processes-javaSerializationEnabled-pa2.xml
  qa/integration-tests-engine/src/test/resources-wildfly/persistence-nonexisting-ds.xml
  qa/integration-tests-engine/src/test/resources-wildfly/persistence.xml
  qa/integration-tests-engine/src/test/resources-wildfly/singleEngine.xml
  qa/integration-tests-engine/src/test/resources-wildfly/singleEngineWithProcessEnginePlugin.xml
  qa/integration-tests-engine/src/test/resources-wildfly/twoEngines.xml
  qa/integration-tests-webapps/shared-engine/pom.xml
  qa/pom.xml
Labels: wildfly

#582 CAM-11147 chore(engine): avoid NPE while reconfiguring the cleanup job
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/EverLivingJobEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentHistoryCleanupReconfigureTest.java
Labels: all-db

#588 CAM-9932: fix transient flag for serialized typed values
  engine-plugins/spin-plugin/src/main/java/org/camunda/spin/plugin/impl/JsonValueSerializer.java
  engine-plugins/spin-plugin/src/main/java/org/camunda/spin/plugin/impl/XmlValueSerializer.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/JsonDelegate.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/JsonValueTest.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/XmlValueTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricDecisionInputInstanceEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricDecisionOutputInstanceEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricDetailVariableInstanceUpdateEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricVariableInstanceEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/util/TypedValueField.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/AbstractObjectValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/AbstractSerializableValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/BooleanValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/ByteArrayValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/DateValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/DoubleValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/FileValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/IntegerValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/LongValueSerlializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/NullValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/PrimitiveValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/ShortValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/StringValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/TypedValueSerializer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/serializer/jpa/JPAVariableSerializer.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/TransientVariableTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/variables/FileValueSerializerTest.java
Labels: h2

#553 CAM-11100: chore(database): adjust mssql jdbc driver versions
  database/pom.xml
Labels: sqlserver

#591 CAM-11191: transient flag is preserved in call activity mapping
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/callactivity/CallActivityTest.java
Labels: h2

#590 CAM-11190 fix(engine/rest): add incident -> activity id mapping in instance tree
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ActivityInstanceDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ActivityInstanceIncidentDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/TransitionInstanceDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AbstractRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetActivityInstanceCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ActivityInstanceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TransitionInstanceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/ActivityInstance.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/TransitionInstance.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
Labels: oracle, rest-api

#581 CAM-11157 chore(database): remove jdbc drivers for postgres 9.1 & 9.3
  database/pom.xml
Labels: postgresql

#579 CAM-10682: Replace CMMN with BPMN call activity in invoice example
  examples/invoice/src/main/java/org/camunda/bpm/example/invoice/InvoiceProcessApplication.java
  examples/invoice/src/main/resources/META-INF/processes.xml
  examples/invoice/src/main/resources/invoice.v1.bpmn
  examples/invoice/src/main/resources/invoice.v2.bpmn
  examples/invoice/src/main/resources/review-invoice.cmmn
  examples/invoice/src/main/resources/reviewInvoice.bpmn
  examples/invoice/src/test/java/org/camunda/bpm/example/invoice/InvoiceTestCase.java
Labels: h2

#563 CAM-11105: chore(project): move source code level to Java 8
  .travis.yml
  README.md
  bom/pom.xml
  distro/tomcat/assembly/assembly.xml
  distro/tomcat/assembly/src/tomcat/setenv.bat
  distro/tomcat/assembly/src/tomcat/setenv.sh
  distro/tomcat/assembly/src/tomcat6/setenv.bat
  distro/tomcat/assembly/src/tomcat6/setenv.sh
  distro/wildfly/pom.xml
  engine-dmn/bom/pom.xml
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/DmnDecisionResultTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/DmnDecisionTableResultTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/DmnEngineApiTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/ExpressionLanguageTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/FeelIntegrationTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/evaluate/DmnDecisionEvaluationTest.java
  engine-plugins/spin-plugin/pom.xml
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/script/SpinScriptTaskSupportWithAutoStoreScriptVariablesTest.java
  engine-spring/compatibility-test-spring5/pom.xml
  engine-spring/core/pom.xml
  engine/pom.xml
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/scripttask/ScriptTaskTest.java
  model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/CamundaExtensionsTest.java
  parent/pom.xml
  pom.xml
  qa/integration-tests-engine/src/test/resources-tomcat/arquillian.xml
  qa/integration-tests-engine/src/test/resources-wildfly-domain/arquillian.xml
  qa/integration-tests-engine/src/test/resources-wildfly/arquillian.xml
  qa/integration-tests-webapps/shared-engine/pom.xml
  qa/integration-tests-webapps/shared-engine/src/test/resources/arquillian.xml
  qa/integration-tests-webapps/standalone-engine/pom.xml
  qa/pom.xml
  qa/tomcat-runtime/src/main/conf/server.xml
Labels: all-as

#598 Allow group and category elements
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/Bpmn.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/BpmnModelConstants.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/instance/CategoryImpl.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/instance/GroupImpl.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/instance/Category.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/instance/Group.java
  model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/instance/CategoryTest.java
  model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/instance/GroupTest.java
Labels: h2

#597 CAM-11217: feat(engine): set default composite history event handler
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/handler/CompositeHistoryEventHandler.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/AbstractCompositeHistoryEventHandlerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/CompositeDbHistoryEventHandlerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/CompositeHistoryEventHandlerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/DefaultHistoryEventHandlerTest.java
Labels: h2
