Repository camunda/camunda-bpm-platform, pull requests merged in 2019-08, with the labels that each got.

#427 [CAM-10673] Remove loanApproval.bpmn from standalone webapps
  distro/jbossas7/webapp-standalone/src/main/resources/bpmn/loanApproval.bpmn
  distro/tomcat/webapp-standalone/src/main/resources/bpmn/loanApproval.bpmn
Labels: tomcat

#430 [CAM-10699, CAM-10695] Bump java-uuid-generator dependency to 3.2.0
  bom/pom.xml
Labels: all-db

#429 [CAM-10696, CAM-10695] Bump mybatis dependency to 3.4.6
  bom/pom.xml
Labels: all-db

#434 [CAM-10696, CAM-10695] Bump mybatis dependency to 3.4.6
  bom/pom.xml
Labels: all-db

#435 [CAM-10699, CAM-10695 Bump java-uuid-generator dependency to 3.2.0
  bom/pom.xml
Labels: all-db

#446 CAM-10730: fix(engine): task query assignee in filter can be extended
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java
Labels: rest-api

#436 [CAM-10616] chore(engine): add job log index for job def config
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.db2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.h2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mariadb.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mssql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mysql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.oracle.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.postgres.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.10_patch_7.10.6_to_7.10.7.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.11_patch_7.11.2_to_7.11.3.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.10_patch_7.10.6_to_7.10.7.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.11_patch_7.11.2_to_7.11.3.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.10_patch_7.10.6_to_7.10.7.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.11_patch_7.11.2_to_7.11.3.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.10_patch_7.10.6_to_7.10.7.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.11_patch_7.11.2_to_7.11.3.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.10_patch_7.10.6_to_7.10.7.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.11_patch_7.11.2_to_7.11.3.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.10_patch_7.10.6_to_7.10.7.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.11_patch_7.11.2_to_7.11.3.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.10_patch_7.10.6_to_7.10.7.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.11_patch_7.11.2_to_7.11.3.sql
Labels: rolling-update

#432 [CAM-10702, CAM-10695] Bump slf4j-api dependency to 1.7.26
  distro/jbossas7/modules/pom.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly8/modules/pom.xml
Labels: all-as

#440 [CAM-10711, CAM-10695] Bump httpclient dependency to 4.5.9
  bom/pom.xml
  distro/jbossas7/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml
  distro/wildfly/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml
  distro/wildfly8/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml
  qa/integration-tests-webapps/pom.xml
Labels: all-as

#441 fix(engine): perform context classloader switch before running a job
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/classloading/jobexecution/ClassloadingDuringJobExecutionTest.java
Labels: all-as

#450 CAM-10282: add PostgreSQL specific count queries
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Batch.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/CaseDefinition.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/CaseExecution.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/CaseSentryPart.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/DecisionDefinition.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/DecisionRequirementsDefinition.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Deployment.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/EventSubscription.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Execution.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ExternalTask.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Filter.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Group.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricActivityInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricBatch.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricCaseActivityInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricCaseInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDecisionInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricExternalTaskLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIdentityLinkLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricStatistics.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Incident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/JobDefinition.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ProcessDefinition.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/SchemaLogEntry.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Statistics.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Tenant.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/User.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/UserOperationLogEntry.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
Labels: all-db

#451 CAM-10697: bump jackson-databind to 2.9.9.3
  bom/pom.xml
  distro/jbossas7/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/main/module.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/2.9.9.3/module.xml
  distro/wildfly8/modules/pom.xml
  distro/wildfly8/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/2.9.9.3/module.xml
  engine-rest/pom.xml
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/resources-wildfly/jboss-deployment-structure-spin-json.xml
Labels: all-as

#452 CAM-10379: fix classloading for weblogic server
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
  javaee/jobexecutor-ra/src/main/java/org/camunda/bpm/container/impl/threading/ra/inflow/JcaInflowExecuteJobsRunnable.java
Labels: all-as
