Repository camunda/camunda-bpm-platform, pull requests merged in 2019-11, with the labels that each got.

#530 CAM-10929: deprecate Optimize permissions
  engine/src/main/java/org/camunda/bpm/engine/authorization/OptimizePermissions.java
  engine/src/main/java/org/camunda/bpm/engine/authorization/Resources.java
Labels: rest-api

#503 Add support for new license format
  engine/src/main/java/org/camunda/bpm/engine/ManagementService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteLicenseKeyCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetLicenseKeyCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/LicenseCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/PurgeDatabaseAndCacheCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetLicenseKeyCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/management/DatabasePurgeReport.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ResourceManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/test/TestHelper.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Resource.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/LicenseUserOperationLogTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceTableCountTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyAuthTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyDirtyDbTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/CompetingLicenseKeyAccessTest.java
Labels: all-db

#520 CAM-10805: chore(rest): ensure correct rest exception log levels
  engine-rest/engine-rest/pom.xml
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionHandler.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionHandlerHelper.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionLogger.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/JsonMappingExceptionHandler.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/JsonParseExceptionHandler.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ProcessEngineExceptionHandler.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/RestExceptionHandler.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/UserRestServiceInteractionTest.java
Labels: rest-api

#531 CAM-10955: fetch hal variables without pagination limit
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/FilterResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
Labels: rest-api

#536 CAM-10667 Refactor License Key Deletion
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteLicenseKeyCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/PurgeDatabaseAndCacheCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ResourceEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ResourceManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Resource.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/LicenseUserOperationLogTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyDirtyDbTest.java
Labels: all-db

#540 CAM-10991: fix(rest): expose closedIncidents to hist act statistics response
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricActivityStatisticsDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityStatisticsRestServiceQueryTest.java
Labels: rest-api

#542 [CAM-11003] fix(engine): correct logging context properties' names
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataLoggingContext.java
  engine/src/test/java/org/camunda/bpm/engine/test/logging/ProcessDataLoggingContextTest.java
Labels: wildfly

#529 CAM-10600: create index on act_hi_detail.var_inst_id_
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.db2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.h2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mariadb.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mssql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mysql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.oracle.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.postgres.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.11_to_7.12.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.11_to_7.12.sql
Labels: all-db

#523 CAM-10906: chore(engine): add incident ids in get activities instances
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/ActivityInstanceDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/TransitionInstanceDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AbstractRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetActivityInstanceCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ActivityInstanceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ProcessElementInstanceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TransitionInstanceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/ActivityInstance.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/TransitionInstance.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/ActivityInstanceAssert.java
Labels: all-db

#537 CAM-6554: feat(engine): query historic queries without tenant id
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricActivityInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricCaseActivityInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricDecisionInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricDetailQuery.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricExternalTaskLogQuery.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricIdentityLinkLogQuery.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncidentQuery.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricJobLogQuery.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricTaskInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricVariableInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricActivityInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricCaseActivityInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricDecisionInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricDetailQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricExternalTaskLogQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricIdentityLinkLogQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricIncidentQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricJobLogQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricVariableInstanceQueryImpl.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricActivityInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricCaseActivityInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDecisionInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricExternalTaskLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIdentityLinkLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/cmmn/query/history/MultiTenancyHistoricCaseActivityInstanceQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/cmmn/query/history/MultiTenancyHistoricCaseInstanceQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricActivityInstanceQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricDecisionInstanceQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricDetailFormPropertyQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricDetailVariableUpdateQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricExternalTaskLogTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricIdentityLinkLogQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricIncidentQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricJobLogQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricProcessInstanceQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricTaskInstanceQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricVariableInstanceQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/TestOrderingUtil.java
Labels: postgresql

#538 CAM-6554: feat(rest): query historic queries without tenant id
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricActivityInstanceQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricCaseActivityInstanceQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricDecisionInstanceQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricDetailQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricExternalTaskLogQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIdentityLinkLogQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricVariableInstanceQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricCaseActivityInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDecisionInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDetailRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricExternalTaskLogRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIdentityLinkLogRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricVariableInstanceRestServiceQueryTest.java
Labels: rest-api

#546 [CAM-10964] chore(wildfly): activate MDC by default in log
  distro/wildfly/assembly/src/wildfly/standalone.xml
Labels: wildfly

#543 CAM-11037: expose open/resolved/closed incidents count to historic activity instance statistics
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricActivityStatisticsDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricActivityStatisticsQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricActivityStatisticsRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricActivityStatistics.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricActivityStatisticsQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricActivityStatisticsQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricActivityStatisticsImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricStatisticsManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricStatistics.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricActivityStatisticsQueryTest.java
Labels: all-db

#548 CAM-10990: do not validate affected rows of INSERTs
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/BatchDbSqlSession.java
Labels: all-db

#539 CAM-10992: order decision definitions by requirements key
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/repository/DecisionDefinitionQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/DecisionDefinitionRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/dmn/entity/repository/DecisionDefinitionQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/dmn/entity/repository/DecisionDefinitionQueryProperty.java
  engine/src/main/java/org/camunda/bpm/engine/repository/DecisionDefinitionQuery.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/repository/DecisionDefinitionQueryTest.java
Labels: all-db

#544 CAM-10962: prevent task op log on instance modification
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AssignTaskCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ClaimTaskCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CompleteTaskCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DelegateTaskCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteTaskCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ResolveTaskCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SaveTaskCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskOwnerCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskPriorityCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SubmitTaskFormCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmmn/cmd/CompleteCaseExecutionCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskManager.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ModificationUserOperationLogTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/useroperationlog/UserOperationLogTaskServiceAndBeanTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/useroperationlog/UserOperationLogTaskTest.java
Labels: all-db

#528 CAM-10771: improve Bpmn Parser exceptions
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/ParseExceptionDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/ProblemDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/ResourceReportDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionHandlerHelper.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/DeploymentRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine/src/main/java/org/camunda/bpm/engine/ParseException.java
  engine/src/main/java/org/camunda/bpm/engine/Problem.java
  engine/src/main/java/org/camunda/bpm/engine/ResourceReport.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/ResourceReportImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/EngineUtilLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/xml/Parse.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/xml/Problem.java
  engine/src/main/java/org/camunda/bpm/engine/impl/xml/ProblemImpl.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/async/AsyncAfterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/callactivity/CallActivityTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/compensate/CompensationEventParseInvalidProcessTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/conditional/ConditionalStartEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/error/BoundaryErrorEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/escalation/EscalationEventParseInvalidProcessTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/link/LinkEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/message/MessageBoundaryEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/message/MessageIntermediateEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/message/MessageStartEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventParseInvalidProcessTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/external/ExternalTaskParseTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/gateway/EventBasedGatewayTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/gateway/ExclusiveGatewayTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/iomapping/InputOutputEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/iomapping/InputOutputTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/job/JobPrioritizationBpmnConstantValueTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/subprocess/transaction/TransactionSubProcessTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/dmn/businessruletask/DmnBusinessRuleTaskResultMappingTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/compensate/CompensationEventParseInvalidProcessTest.illegalCompensateActivityRefNestedScope.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/compensate/CompensationEventParseInvalidProcessTest.invalidIncomingSequenceflow.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/compensate/CompensationEventParseInvalidProcessTest.invalidOutgoingSequenceflow.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/compensate/CompensationEventParseInvalidProcessTest.multipleCompensationCatchEventsCompensationAttributeMissingFails.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/signal/InvalidProcessWithSignalNoId.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/gateway/EventBasedGatewayTest.testEventInvalidSequenceFlow.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.testMultipleTimerStartEvents.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseMultipleStartEvent.bpmn20.xml
Labels: all-db

#549 CAM-11090: disable javascript compilation
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/script/SpinScriptTaskSupportTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/scripting/SourceExecutableScript.java
Labels: mysql

#552 CAM-11090: relax test assertion
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/script/SpinJRubyScriptTaskTest.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/script/SpinScriptTaskSupportTest.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/script/SpinScriptTaskSupportWithAutoStoreScriptVariablesTest.java
Labels: mysql

#560 CAM-10583: chore(typed-values): adjust old version for clirr comparison check
  typed-values/pom.xml
Labels: tomcat

#562 [CAM-11032] chore(qa): adjust old-engine dependencies
  qa/test-old-engine/pom.xml
Labels: migration
