Repository camunda/camunda-bpm-platform, pull requests merged in 2020-07, with the labels that each got.

#874 fix(engine): fix httpclient shading
  engine/pom.xml
Labels: postgresql, wildfly

#872 CAM-12025: integrate telemetry reporter with engine
  engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ProcessEngineImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/PropertyManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetryReporter.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/JsonUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentInstallationIdInitializationTest.java
  engine/src/test/resources/camunda.cfg.plugins.xml
  engine/src/test/resources/camunda.cfg.prefix.xml
  engine/src/test/resources/camunda.cfg.prefix_extended.xml
  engine/src/test/resources/camunda.cfg.xml
Labels: all-db

#877 chore(engine/distro): shade commons logging
  distro/jbossas7/modules/src/main/modules/org/camunda/bpm/camunda-engine/main/module.xml
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/camunda-engine/main/module.xml
  engine/pom.xml
Labels: all-as

#855 feat(rest/open-api): add historic process instance endpoints
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/AbstractSetRemovalTimeDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/DeleteHistoricProcessInstancesDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/DurationReportResultDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/SetRemovalTimeToHistoricProcessInstancesDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/count/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/count/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/delete/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/report/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/set-removal-time/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/{id}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/{id}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/{id}/variable-instances/delete.ftl
Labels: rest-api

#886 chore(distro-run): fix typo in default configuration comment
  distro/run/assembly/resources/default.yml
Labels: run

#879 chore(engine): configure model parser more strict regarding xxe
  engine/src/main/java/org/camunda/bpm/engine/impl/util/xml/Parse.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.java
Labels: all-as

#890 fix(mysql): improve update removal time query for MySQL
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
Labels: mysql

#891 fix(openapi): add missing process instance endpoint
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/get.ftl
Labels: rest-api

#893 [CAM-11919] chore(platform): bump SpringBoot to 2.3
  pom.xml
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/CsrfPreventionIT.java
Labels: run, spring-boot

#896 CAM-12120: replace log4j with logback
  engine-dmn/feel-scala/pom.xml
  engine-dmn/feel-scala/src/test/resources/logback-test.xml
  engine-dmn/pom.xml
Labels: h2

#888 fix(engine): ignore failure of db operation when op for owning entity has failed
  engine/pom.xml
  engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/HasDbReferences.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/operation/DbEntityOperation.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/operation/DbOperationManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/BatchDbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/SimpleDbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentHistoryCleanupUpdateOfFailingJobTest.java
Labels: all-db

#895 CAM-12106: make el resolver volatile
  engine/src/main/java/org/camunda/bpm/engine/impl/el/ExpressionManager.java
Labels: h2

#894 chore(fix): partition delete historicProcessInstances when > 2000
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java
  qa/large-data-tests/pom.xml
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/DeleteDeploymentCascadeTest.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/DmnHelper.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/EngineDataGenerator.java
Labels: all-db

#900 chore(fix): partition historicProcessInstances input/output lookup
  engine/src/main/java/org/camunda/bpm/engine/impl/optimize/OptimizeManager.java
Labels: all-db

#902 chore(test): make sure t2 finishes after t1
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentHistoryCleanupUpdateOfFailingJobTest.java
Labels: all-db, mariadb, no-build

#905 CAM-12187: add direct JAXB-API dependency
  distro/run/core/pom.xml
Labels: run

#901 fix(engine): prevent caching of procDefs on app resume
  engine/src/main/java/org/camunda/bpm/engine/impl/repository/DefaultDeploymentHandler.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessApplicationDeploymentTest.java
Labels: wildfly

#913 chore(pom): bump dependency of SQL Server to 8.2.2
  database/pom.xml
Labels: sqlserver

#914 fix(qa/webapps): download chrome driver version on-the-fly
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/LoginIT.java
  qa/integration-tests-webapps/pom.xml
Labels: webapp-integration
