Repository camunda/camunda-bpm-platform, pull requests merged in 2020-10, with the labels that each got.

#1040 CAM-12557: fix(telemetry): skip sending initial report during engine close
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetryReporter.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: default-build

#1045 Fix critical sonar issues in FetchAndLockHandlerImpl
  engine-rest/engine-rest-jaxrs2/src/main/java/org/camunda/bpm/engine/rest/impl/FetchAndLockHandlerImpl.java
Labels: hacktoberfest-accepted

#1053 fix(engine): resolve candidate groups outside of SQL
  engine-plugins/identity-ldap/src/test/java/org/camunda/bpm/identity/impl/ldap/ProcessDefinitionQueryWithCustomIdentityProviderTest.java
  engine-plugins/identity-ldap/src/test/resources/org/camunda/bpm/identity/impl/ldap/ProcessDefinitionQueryWithCustomIdentityProviderTest.bpmn20.xml
  engine/src/main/java/org/camunda/bpm/engine/impl/ProcessDefinitionQueryImpl.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ProcessDefinition.xml
Labels: all-db

#1055 CAM-12559: fix(engine): enable or queries for tenant id filtering
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java
  engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/MultiTenancyFilterServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/MultiTenancySignalReceiveTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/query/MultiTenancyTaskQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyMessageCorrelationCmdTenantCheckTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyMessageEventReceivedCmdTenantCheckTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancySignalReceiveCmdTenantCheckTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java
Labels: all-db

#1057 CAM-12576: chore(tests): improve telemetry test to be process engine configuration
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryMultipleEnginesTest.java
Labels: h2

#1050 chore: added badges for quick naigation
  README.md
Labels: hacktoberfest-accepted

#1014 CAM-12512: chore(starter): disable telemetry reporter
  distro/run/core/src/test/resources/application.yml
  distro/run/qa/integration-tests/src/test/resources/base-test-application.yml
  spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-all/src/test/resources/application.properties
  spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-json-jackson/src/test/resources/application.properties
  spring-boot-starter/starter-qa/integration-test-simple/src/test/resources/application.properties
  spring-boot-starter/starter-qa/integration-test-webapp/invoice-example/src/main/resources/application.yaml
  spring-boot-starter/starter-qa/integration-test-webapp/runtime/src/test/resources/application.properties
  spring-boot-starter/starter-rest/src/test/resources/application.properties
  spring-boot-starter/starter-webapp-core/src/test/resources/application.properties
  spring-boot-starter/starter/src/test/resources/application.properties
Labels: spring-boot

#1044 [CAM-11923] feat(engine): use dedicated camundaBpmTransactionManager bean if declared
  spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultDatasourceConfiguration.java
  spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/configuration/impl/DefaultDatasourceConfigurationTest.java
Labels: hacktoberfest-accepted

#1054 [CAM-12584] Added logo and badges in README.md
  README.md
Labels: hacktoberfest-accepted

#1049 [CAM-12579] chore: add repo licence link
  README.md
Labels: hacktoberfest-accepted

#1061 CAM-12601: chore(engine): adjust duplicated code in persistence logger
  engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
Labels: default-build

#1065 Update README.md
  README.md
Labels: hacktoberfest-accepted

#1043 [CAM-12091] fix(engine): add error when parsing process without start event
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.testInvalidProcessWithoutStartEvent.bpmn20.xml
Labels: hacktoberfest-accepted

#1070 [CAM-12583] fix(rest): return 'assigned' attribute of task filter
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
Labels: rest-api

#1071 CAM-12391: fix(rest-openapi): fix variables query parameter
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/get.ftl
Labels: rest-api

#1068 CAM-12131: fix(engine): pg jdbc api change adjustments
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java
Labels: all-db

#1081 fix(engine-rest): return invalid request for double quoted date value
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/converter/DateConverter.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/converter/DateConverterTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java
Labels: rest-api

#1083 CAM-12503: chore(rest): bump commons-fileupload version
  internal-dependencies/pom.xml
Labels: rest-api

#1079 CAM-12612: fix qa for CockroachDB
  qa/test-db-upgrade/config/org/camunda/bpm/engine/test/concurrency/historycleanup.camunda.cfg.xml
  qa/test-db-upgrade/pom.xml
  qa/test-old-engine/config/org/camunda/bpm/engine/test/concurrency/historycleanup.camunda.cfg.xml
  qa/test-old-engine/pom.xml
Labels: all-db, cockroachdb

#1075 chore(telemetry): add webapps to telemetry data
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/WebApplicationUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: webapp-integration

#1082 fix(telemetry): reliably fetch app server info
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/WebApplicationUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/PlatformTelemetryRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/test/ProcessEngineRule.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: spring-boot

#1088 test(telemetry): add webapp data to telemetry test
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java
Labels: weblogic
