Repository camunda/camunda-bpm-platform, pull requests merged in 2020-08, with the labels that each got.

#906 fix(large-data): only cleanup DeleteDeploymentCascadeTest data
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/DeleteDeploymentCascadeTest.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/EngineDataGenerator.java
Labels: all-db

#885 fix(engine): fix telemetry data to respect enterprise aplha versions
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ParseUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ProcessEngineDetails.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/ProcessEngineDetailsTest.java
Labels: postgresql

#920 [CAM-11943] chore(model-api): ensure unique path for schema resources
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/BpmnModelConstants.java
  model-api/bpmn-model/src/main/resources/org/camunda/bpm/model/bpmn/schema/BPMN20.xsd
  model-api/bpmn-model/src/main/resources/org/camunda/bpm/model/bpmn/schema/BPMNDI.xsd
  model-api/bpmn-model/src/main/resources/org/camunda/bpm/model/bpmn/schema/DC.xsd
  model-api/bpmn-model/src/main/resources/org/camunda/bpm/model/bpmn/schema/DI.xsd
  model-api/bpmn-model/src/main/resources/org/camunda/bpm/model/bpmn/schema/Semantic.xsd
  model-api/cmmn-model/src/main/java/org/camunda/bpm/model/cmmn/impl/CmmnModelConstants.java
  model-api/cmmn-model/src/main/resources/org/camunda/bpm/model/cmmn/schema/cmmn10/CMMN10.xsd
  model-api/cmmn-model/src/main/resources/org/camunda/bpm/model/cmmn/schema/cmmn10/CMMN10CaseModel.xsd
  model-api/cmmn-model/src/main/resources/org/camunda/bpm/model/cmmn/schema/cmmn11/CMMN11.xsd
  model-api/cmmn-model/src/main/resources/org/camunda/bpm/model/cmmn/schema/cmmn11/CMMN11CaseModel.xsd
  model-api/cmmn-model/src/main/resources/org/camunda/bpm/model/cmmn/schema/cmmn11/CMMNDI11.xsd
  model-api/cmmn-model/src/main/resources/org/camunda/bpm/model/cmmn/schema/cmmn11/DC.xsd
  model-api/cmmn-model/src/main/resources/org/camunda/bpm/model/cmmn/schema/cmmn11/DI.xsd
  model-api/dmn-model/README.md
  model-api/dmn-model/src/main/java/org/camunda/bpm/model/dmn/impl/DmnModelConstants.java
  model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DC.xsd
  model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DI.xsd
  model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DMN11.xsd
  model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DMN11_Alternative.xsd
  model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DMN12.xsd
  model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DMN13.xsd
  model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DMNDI12.xsd
  model-api/dmn-model/src/main/resources/org/camunda/bpm/model/dmn/schema/DMNDI13.xsd
Labels: default-build

#928 chore(qa): adjust module dependencies
  distro/jbossas7/modules/src/main/modules/org/camunda/bpm/jboss/camunda-jboss-subsystem/main/module.xml
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml
  qa/wildfly-runtime/src/main/common/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml
Labels: all-as

#912 fix(spring-boot): change enterLicenseKey logger to take string argument
  spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/util/SpringBootProcessEngineLogger.java
Labels: spring-boot

#922 [CAM-11757] chore(engine): bump Spring to version 5
  distro/jbossas7/webapp-standalone/pom.xml
  distro/tomcat/webapp-standalone/pom.xml
  engine-spring/compatibility-test-spring4/pom.xml
  engine-spring/compatibility-test-spring5/pom.xml
  engine-spring/compatibility-test-spring5/src/test/resources/META-INF/services/org.camunda.bpm.engine.spring.test.SpringTestHelper
  engine-spring/core/pom.xml
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/Spring3TestHelper.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/Spring5TestHelper.java
  engine-spring/core/src/test/resources/META-INF/services/org.camunda.bpm.engine.spring.test.SpringTestHelper
  engine-spring/pom.xml
  parent/pom.xml
Labels: all-as, webapp-integration

#933 [CAM-11422] chore(platform): extract dependency versions from parent
  distro/jbossas7/pom.xml
  distro/jbossas7/webapp-standalone/pom.xml
  distro/license-book/pom.xml
  distro/run/pom.xml
  distro/sql-script/pom.xml
  distro/tomcat/pom.xml
  distro/tomcat/webapp-standalone/pom.xml
  distro/webjar/pom.xml
  distro/wildfly/pom.xml
  engine-cdi/pom.xml
  engine-dmn/pom.xml
  engine-plugins/pom.xml
  engine-rest/engine-rest/pom.xml
  engine-rest/pom.xml
  engine-spring/compatibility-test-spring4/pom.xml
  engine-spring/core/pom.xml
  engine/pom.xml
  examples/invoice/pom.xml
  internal-dependencies/pom.xml
  javaee/ejb-client/pom.xml
  javaee/ejb-service/pom.xml
  javaee/jobexecutor-ra/pom.xml
  javaee/jobexecutor-rar/pom.xml
  model-api/pom.xml
  parent/pom.xml
  pom.xml
  qa/integration-tests-engine/pom.xml
  qa/pom.xml
  qa/test-db-upgrade/pom.xml
  qa/test-old-engine/pom.xml
  spring-boot-starter/pom.xml
  typed-values/pom.xml
  webapps/h2-webapp/pom.xml
Labels: migration, no-build, rolling-update, spring-boot, webapp-integration, wildfly

#943 feat(engine): add batch operation to set variables
  engine/src/main/java/org/camunda/bpm/engine/RuntimeService.java
  engine/src/main/java/org/camunda/bpm/engine/authorization/BatchPermissions.java
  engine/src/main/java/org/camunda/bpm/engine/batch/Batch.java
  engine/src/main/java/org/camunda/bpm/engine/history/UserOperationLogEntry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/RuntimeServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/AbstractBatchJobHandler.java
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/BatchConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/BatchEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/variables/BatchSetVariablesHandler.java
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/variables/SetVariablesJsonConverter.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CommandLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/batch/variables/SetVariablesToProcessInstancesBatchCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/VariableUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/scope/AbstractVariableScope.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/batch/creation/SetVariablesBatchAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/helper/BatchSetRemovalTimeRule.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/dmn/businessruletask/TestPojo.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/BatchRule.java
Labels: no-build
