Repository camunda/camunda-bpm-platform, pull requests merged in 2020-01, with the labels that each got.

#601 chore(engine-sql): add index to historic variable instance table
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.db2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.h2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mariadb.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mssql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mysql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.oracle.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.postgres.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.12_to_7.13.sql
Labels: all-db

#609 [CAM-10628] feat(database): add profiles for Oracle 19
  database/pom.xml
  settings/maven/nexus-settings.xml
Labels: oracle

#611 CAM-11233: feat(rest): add historic job log hostname parameter
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java
Labels: rest-api, rolling-update

#618 CAM-10952: chore(engine/rest): add processInstanceIdIn to the task query
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskManager.java
  engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
Labels: oracle

#613 Remove file ending from NOTICE and LICENSE files (distro)
  distro/jbossas7/assembly/assembly.xml
  distro/license/LICENSE
  distro/license/NOTICE
  distro/tomcat/assembly/assembly.xml
  distro/wildfly/assembly/assembly.xml
Labels: wildfly

#617 [CAM-10378] feat(engine): add id of failed activity to job
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncident.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricJobLog.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/ExecuteJobsCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/context/Context.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricIncidentEventEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricJobLogEvent.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/incident/IncidentContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/AtomicOperationInvocation.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandInvocationContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ProcessDataLoggingContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobHelper.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/FailedJobListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobFailureCollector.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/IncidentEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/Incident.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/Job.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Incident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/IncidentTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/JobEntityTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricJobLogTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/history/HistoricJobLogTest.testAsyncContinuationWithFollowUp.bpmn20.xml
Labels: all-db

#619 [CAM-10378] feat(rest): add id of failed activity
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/IncidentDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockJobBuilder.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java
Labels: rest-api

#624 [CAM-10378]: chore(engine+rest): rename failed activity properties
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/IncidentDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockJobBuilder.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncident.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricJobLog.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricIncidentEventEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricJobLogEvent.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/incident/IncidentContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/FailedJobListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/IncidentEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/Incident.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/Job.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Incident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/IncidentTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/JobEntityTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricJobLogTest.java
Labels: all-db

#623 CAM-11250: correct history event on instance migration
  engine/src/main/java/org/camunda/bpm/engine/impl/migration/instance/MigratingActivityInstance.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/CustomHistoryEventHandlerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/ProcessEngineConfigurator.java
Labels: h2

#628 CAM-10977: use Resteasy 3 instead of 2 on Tomcat
  distro/tomcat/distro/pom.xml
  distro/tomcat/webapp/pom.xml
Labels: tomcat
