Repository camunda/camunda-bpm-platform, pull requests merged in 2020-02, with the labels that each got.

#637 feel ❤️ JBoss EAP
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml
Labels: jbosseap

#638 WIP exclude slf4j from shading [feel]
  distro/jbossas7/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml
  engine-dmn/engine/pom.xml
Labels: all-as

#635 CAM-11285: Resteasy 3 update
  distro/tomcat/webapp/pom.xml
  engine-rest/assembly/assembly-war-jbossas7.xml
  engine-rest/assembly/assembly-war-tomcat.xml
  engine-rest/assembly/pom.xml
  engine-rest/engine-rest-jaxrs2/pom.xml
  engine-rest/engine-rest/pom.xml
  parent/pom.xml
Labels: webapp-integration

#631 [CAM-11273] feat(engine+rest): add job query filter for failed activity
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricJobLogQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricJobLogQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/JobQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/JobQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/JobQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricJobLogQueryTest.java
Labels: rest-api

#630 [CAM-11274] feat(engine+rest): add query filter for failed activity id
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/IncidentQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncidentQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricIncidentQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/IncidentQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/IncidentQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Incident.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/IncidentQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentQueryTest.java
Labels: rest-api

#640 CAM-11314 add java 8 types to dmn date transformer
  engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/type/DateDataTypeTransformer.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/FeelBehavior.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/NewScalaFeelBehaviorTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/type/DmnDataTypeTransformerTest.java
  engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/feel/scala_literal_expression_date_typed.dmn
Labels: h2

#643 CAM-11347 add constructor instead of init block
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/NewScalaFeelBehaviorTest.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/CamundaFeelEngine.java
Labels: h2

#646 chore(dmn): make zoneddatetime instance more robust
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/type/DmnDataTypeTransformerTest.java
Labels: h2

#633 CAM-11345: remove BOM from pom hierarchy
  bom/pom.xml
  database/pom.xml
  engine-rest/engine-rest/pom.xml
  parent/pom.xml
  pom.xml
  qa/integration-tests-engine/pom.xml
  qa/test-db-instance-migration/test-fixture-710/pom.xml
  qa/test-db-instance-migration/test-fixture-711/pom.xml
  qa/test-db-instance-migration/test-fixture-712/pom.xml
  qa/test-db-instance-migration/test-fixture-713/pom.xml
  qa/test-db-instance-migration/test-fixture-72/pom.xml
  qa/test-db-instance-migration/test-fixture-73/pom.xml
  qa/test-db-instance-migration/test-fixture-74/pom.xml
  qa/test-db-instance-migration/test-fixture-75/pom.xml
  qa/test-db-instance-migration/test-fixture-76/pom.xml
  qa/test-db-instance-migration/test-fixture-77/pom.xml
  qa/test-db-instance-migration/test-fixture-78/pom.xml
  qa/test-db-instance-migration/test-fixture-79/pom.xml
  qa/test-db-instance-migration/test-migration/pom.xml
  qa/test-db-rolling-update/create-old-engine/pom.xml
  qa/test-db-rolling-update/rolling-update-util/pom.xml
  qa/test-db-rolling-update/test-old-engine/pom.xml
  qa/test-db-util/pom.xml
  qa/test-old-engine/pom.xml
Labels: all-as

#653 fix(engine): populate historic process instance state during migration
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/history/MigrationHistoricProcessInstanceTest.java
Labels: h2

#652 fix(engine-rest): enable remote fetching in shrinkwrap test
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/TomcatServerBootstrap.java
Labels: rest-api

#650 CAM-11351: improve macros and cleanup parser in open api doc generation
  engine-rest/engine-rest-openapi-generator/src/main/java/org/camunda/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
  engine-rest/engine-rest-openapi/pom.xml
  engine-rest/engine-rest-openapi/src/main/templates/lib/macros.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/CaseDefinitionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DecisionDefinitionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/ProcessDefinitionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesByProcessDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/modification/ProcessInstanceModificationInstructionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/commons/process-instance-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/commons/sort-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/commons/sort-props.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/create/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/count/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/count/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/delete-historic-query-based/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/delete/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/job-retries-historic-query-based/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/job-retries/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/suspended/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/activity-instances/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/modification-async/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/modification/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/suspended/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/data/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/data/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/put.ftl
Labels: rest-api

#657 chore(optimize): add tests to ensure databases can cope with page size
  parent/pom.xml
  qa/large-data-tests/README.md
  qa/large-data-tests/pom.xml
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/util/DmnHelper.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/util/EngineDataGenerator.java
  qa/large-data-tests/src/test/resources/camunda.cfg.xml
  qa/large-data-tests/src/test/resources/logback-test.xml
  qa/pom.xml
Labels: all-as

#656 fix(webapps): ensure correct response on missing csrf token
  qa/integration-tests-webapps/integration-tests/src/test/java/org/camunda/bpm/AbstractWebIntegrationTest.java
  qa/integration-tests-webapps/integration-tests/src/test/java/org/camunda/bpm/CsrfPreventionIT.java
Labels: tomcat, webapp-integration

#648 chore(openapi): add json schema validation
  engine-rest/engine-rest-openapi-generator/pom.xml
  engine-rest/engine-rest-openapi-generator/src/main/java/org/camunda/bpm/engine/rest/openapi/generator/impl/SchemaValidator.java
  engine-rest/engine-rest-openapi-generator/src/main/java/org/camunda/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
  engine-rest/engine-rest-openapi/pom.xml
  engine-rest/engine-rest-openapi/src/main/openapi/schema.json
Labels: rest-api

#659 fix(engine-rest): forward Maven settings from build to shrinkwrap
  engine-rest/engine-rest/pom.xml
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/TomcatServerBootstrap.java
Labels: rest-api

#660 CAM-11395: rewrite variable condition to join
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryServiceTest.java
Labels: all-db

#666 CAM-11393 Adjust package structure according to feel-scala
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/CamundaFeelEngine.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ContextVariableWrapper.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunctionTransformer.java
  engine-dmn/feel-scala/src/main/resources/META-INF/services/org.camunda.feel.impl.spi.CustomValueMapper
  engine-dmn/feel-scala/src/main/resources/META-INF/services/org.camunda.feel.valuemapper.CustomValueMapper
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionSpiTest.java
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/helper/NonSpiFunctionProvider.java
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/helper/SpiFunctionProvider.java
Labels: h2

#608 [CAM-10748] feat(engine-cdi): add JobExecutor using managed threads
  engine-cdi/pom.xml
  engine-cdi/src/main/java/org/camunda/bpm/engine/cdi/impl/ManagedJobExecutor.java
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/jobexecutor/ManagedJobExecutorTest.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/jobexecutor/beans/ManagedJobExecutorBean.java
  qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/jobexecutor/ManagedJobExecutorTest.testManagedExecutorUsed.bpmn20.xml
Labels: all-as

#663 CAM-11262 separate engine-dmn & feel-scala artifact
  distro/jbossas7/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-feel-scala/main/module.xml
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-feel-scala/main/module.xml
  engine-dmn/engine/pom.xml
  engine-dmn/feel-scala/pom.xml
Labels: all-as

#670 CAM-11398: chore(dmn): update feel custom providers setters
  engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java
Labels: h2

#664 CAM-11346: feat(feel): port spin feel integration from scala to java
  bom/pom.xml
  engine-dmn/feel-spin/README.md
  engine-dmn/feel-spin/pom.xml
  engine-dmn/feel-spin/src/main/resources/META-INF.services/org.camunda.feel.spi.CustomValueMapper
  engine-dmn/feel-spin/src/main/scala/org/camunda/bpm/dmn/feel/impl/integration/spin/CamundaSpinValueMapper.scala
  engine-dmn/feel-spin/src/test/scala/org/camunda/bpm/dmn/feel/impl/integration/spin/CamundaSpinValueMapperTest.scala
  engine-dmn/pom.xml
  engine-plugins/spin-plugin/pom.xml
  engine-plugins/spin-plugin/src/main/java/org/camunda/spin/plugin/impl/feel/integration/SpinValueMapper.java
  engine-plugins/spin-plugin/src/main/resources/META-INF/services/org.camunda.feel.valuemapper.CustomValueMapper
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/el/SpinFunctionMapperTest.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/impl/feel/integration/FeelEngineIT.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/impl/feel/integration/FeelSpiValueMapperTest.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/impl/feel/integration/SpinValueMapperTest.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/DmnBusinessRuleTaskResultMappingTest.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/variables/XmlListSerializable.java
  engine-plugins/spin-plugin/src/test/resources/org/camunda/spin/plugin/impl/feel/integration/DecisionFEELInputJSON.dmn11.xml
  engine-plugins/spin-plugin/src/test/resources/org/camunda/spin/plugin/impl/feel/integration/DecisionFEELInputXML.dmn11.xml
Labels: oracle

#671 [CAM-11293] Enable support for authentication via LDAP
  distro/run/distro/pom.xml
  distro/run/distro/src/main/java/org/camunda/bpm/run/CamundaBpmRunSecurityConfiguration.java
  distro/run/distro/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunLdapProperties.java
  distro/run/distro/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunProperties.java
  distro/run/distro/src/test/java/org/camunda/bpm/run/test/config/identity/DemoUserConfigurationTest.java
  distro/run/distro/src/test/java/org/camunda/bpm/run/test/config/identity/LdapConfigurationTest.java
  distro/run/distro/src/test/resources/application-test-demo-user.yml
  distro/run/distro/src/test/resources/application-test-ldap-enabled.yml
Labels: h2

#674 CAM-11426 Get rid of feel-scala service loaders
  distro/jbossas7/modules/src/main/modules/org/camunda/bpm/camunda-engine-plugin-spin/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-feel-scala/main/module.xml
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/camunda-engine-plugin-spin/main/module.xml
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-feel-scala/main/module.xml
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/CamundaFeelEngineFactory.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ContextVariableWrapper.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelEngine.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelLogger.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/spin/SpinValueMapperFactory.java
  engine-dmn/feel-scala/src/main/resources/META-INF/services/org.camunda.feel.valuemapper.CustomValueMapper
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionSpiTest.java
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionTest.java
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/helper/FunctionProvider.java
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/helper/NonSpiFunctionProvider.java
  engine-plugins/spin-plugin/src/main/resources/META-INF/services/org.camunda.feel.valuemapper.CustomValueMapper
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/impl/feel/integration/FeelSpiValueMapperTest.java
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/impl/feel/integration/SpinValueMapperTest.java
Labels: h2

#673 [CAM-11290] Fix CORS tests
  distro/run/distro/pom.xml
  distro/run/distro/src/test/java/org/camunda/bpm/run/test/config/cors/AbstractCorsConfigurationTest.java
  distro/run/distro/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationDisabledTest.java
  distro/run/distro/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledAllowedOriginConfiguredTest.java
  distro/run/distro/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledWildcardTest.java
Labels: h2

#678 CAM-11412: chore(dmn): add limitation on date transformer
  engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/type/DateDataTypeTransformer.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/type/DmnDataTypeTransformerTest.java
Labels: h2

#665 CAM-11354: smoke tests for rest OpenAPI doc
  engine-rest/engine-rest-openapi-generator/pom.xml
  engine-rest/engine-rest-openapi/pom.xml
  engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/DeploymentTest.java
  engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/ProcessInstanceTest.java
  engine-rest/engine-rest-openapi/src/test/resources/one.bpmn
Labels: rest-api

#677 CAM-11464 Consolidate all FEEL Exceptions to logger class
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelEngine.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelLogger.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunctionTransformer.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilderImpl.java
Labels: h2

#679 CAM-11405 In scala-feel, add varargs flag for custom functions
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelLogger.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunction.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/CustomFunctionTransformer.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilder.java
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilderImpl.java
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionTest.java
Labels: h2

#676 CAM-11454 Move Engine ITs to verify feel-scala spin integration
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/impl/feel/integration/FeelEngineIT.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/spin/FeelEngineIT.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/spin/JsonListSerializable.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/spin/XmlListSerializable.java
  qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/functional/spin/feel/feel-spin-json-decision.dmn
  qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/functional/spin/feel/feel-spin-json-process.bpmn
  qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/functional/spin/feel/feel-spin-xml-decision.dmn
  qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/functional/spin/feel/feel-spin-xml-process.bpmn
Labels: all-as

#685 CAM-11471: chore(feel): move feel-scala version property
  engine-dmn/pom.xml
  pom.xml
Labels: h2

#681 CAM-11470 For FEEL, ensure context functions are not available
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/FeelBehavior.java
  engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/feel/context_function.dmn
Labels: h2

#684 CAM-11363 For FEEL Scala, change snapshot to alpha version
  pom.xml
Labels: all-as

#686 chore(run): extract core module for distros
  distro/run/assembly/assembly.xml
  distro/run/assembly/pom.xml
  distro/run/assembly/resources/start.bat
  distro/run/assembly/resources/start.sh
  distro/run/core/pom.xml
  distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRun.java
  distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunSecurityConfiguration.java
  distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunAuthenticationProperties.java
  distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunCorsProperty.java
  distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunLdapProperties.java
  distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunProperties.java
  distro/run/core/src/main/resources/banner.txt
  distro/run/core/src/test/java/org/camunda/bpm/run/test/AbstractRestTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationDisabledTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledAllowedOriginConfiguredTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledWildcardTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/https/HttpsConfigurationEnabledTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/identity/DemoUserConfigurationTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/identity/LdapConfigurationTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/util/LoggingInterceptor.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/util/TestUtils.java
  distro/run/core/src/test/resources/application-test-auth-disabled.yml
  distro/run/core/src/test/resources/application-test-cors-enabled.yml
  distro/run/core/src/test/resources/application-test-demo-user.yml
  distro/run/core/src/test/resources/application-test-https-enabled.yml
  distro/run/core/src/test/resources/application-test-ldap-enabled.yml
  distro/run/core/src/test/resources/keystore.p12
  distro/run/distro/assembly.xml
  distro/run/distro/pom.xml
  distro/run/pom.xml
Labels: h2

#682 fix(rest-openapi): fix the dateLibrary in the client generator config
  engine-rest/engine-rest-openapi/README.md
  engine-rest/engine-rest-openapi/pom.xml
  engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/DeploymentTest.java
Labels: rest-api

#687 CAM-11473: chore(feel/spin): update scala feel logger category
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelLogger.java
  engine-plugins/spin-plugin/pom.xml
  engine-plugins/spin-plugin/src/test/java/org/camunda/spin/plugin/impl/feel/integration/SpinValueMapperTest.java
Labels: h2

#680 chore(rest-openapi): add paths/models auto-resolve
  engine-rest/engine-rest-openapi-generator/src/main/java/org/camunda/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
  engine-rest/engine-rest-openapi/README.md
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/all.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/all.ftl
Labels: rest-api

#672 [CAM-11295, CAM-11296] Auto-deploy all files in configuration/resources
  distro/run/assembly/assembly.xml
  distro/run/assembly/resources/application.yml
  distro/run/assembly/resources/dummyResource/dummy.bpmn
  distro/run/assembly/resources/start.bat
  distro/run/assembly/resources/start.sh
  distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunDeploymentConfiguration.java
  distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunProcessEngineConfiguration.java
  distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunSecurityConfiguration.java
  distro/run/qa/pom.xml
  distro/run/qa/src/test/java/org/camunda/bpm/run/qa/AutoDeploymentIntegrationTest.java
  distro/run/qa/src/test/java/org/camunda/bpm/run/qa/ComponentAvailabilityTest.java
  distro/run/qa/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java
  distro/run/qa/src/test/java/org/camunda/bpm/run/qa/webapps/LoginITTest.java
  distro/run/qa/src/test/resources/base-test-application.yml
  distro/run/qa/src/test/resources/deployment/form.html
  distro/run/qa/src/test/resources/deployment/script.js
Labels: h2
