Repository camunda/camunda-bpm-platform, pull requests merged in 2020-09, with the labels that each got.

#945 feat(rest): add batch operation to set variables
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/batch/SetVariablesAsyncDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/variables-async/post.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/ProcessInstanceRestService.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/batch/SetVariablesAsyncDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessInstanceRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
Labels: no-build

#941 CAM-10520: do not persist transient local variables
  engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/scope/AbstractVariableScope.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/DecisionEvaluationUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/MessageCorrelationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/TransientVariableTest.java
Labels: h2

#935 chore(engine): add command counter
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/JtaProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/StandaloneProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandCounterInterceptor.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/CommandCounter.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Command.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryDataTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryRegistryCounterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: h2, no-build

#944 feat(engine): add configurable cleanup of historyCleanupJob logs
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ConfigurationLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/DefaultHistoryRemovalTimeProvider.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupRemovalTimeTest.java
Labels: all-db

#947 [CAM-11457] feat(env): add support for WildFly 20
  distro/wildfly/assembly/src/wildfly/standalone-full.xml
  distro/wildfly/assembly/src/wildfly/standalone.xml
  distro/wildfly/subsystem/pom.xml
  parent/pom.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml
  qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
Labels: wildfly

#948 chore(engine): adjust initilizeTelemetry config to null by default
  engine/src/main/java/org/camunda/bpm/engine/ManagementService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/IsTelemetryEnabledCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentTelemetryConfigurationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryDefaultConfigTest.java
Labels: all-db

#939 chore(engine-rest): expose telemetry configuration fetch
  engine-rest/engine-rest-openapi/src/main/templates/paths/telemetry/configuration/get.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/TelemetryRestService.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/TelemetryConfigurationDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/TelemetryRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TelemetryRestServiceTest.java
Labels: rest-api

#934 chore(engine): adjust RuntimeServiceTest case
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
Labels: all-db

#955 chore(engine): expand telemetry data with metrics
  engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Metric.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java
  engine/src/test/resources/logback-test.xml
Labels: default-build, no-build

#949 CAM-12330: set variables immediately when submitting start form
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SubmitStartFormCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/util/FormPropertyStartContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/form/FormServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/CustomHistoryEventHandlerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/FullHistoryTest.java
Labels: h2

#967 fix(test): fix setting time in telemetry metric tests
  engine/pom.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: default-build, mysql

#969 fix(test): ensure database schema creation before test
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java
Labels: all-db, default-build

#965 chore(engine/rest): add batch id to runtime variables
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/VariableInstanceDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/VariableInstanceQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/VariableInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/VariableInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockVariableInstanceBuilder.java
  engine/src/main/java/org/camunda/bpm/engine/impl/VariableInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/batch/variables/SetVariablesToProcessInstancesBatchCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/variable/listener/DelegateCaseVariableInstanceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/VariableInstance.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/VariableInstanceQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.db2.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.h2.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mariadb.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mssql.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mysql.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.oracle.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.postgres.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/VariableInstanceQueryTest.java
Labels: no-build

#970 fix(engine): change property setter to primitive
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Labels: all-db, default-build

#972 chore(spring): add command counter interceptor to spring setup
  engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringTransactionsProcessEngineConfiguration.java
Labels: default-build

#977 chore(engine): add user operation log when configuring telemetry
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: all-db

#974 chore(engine): improve unique task worker count calculation
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricTaskInstanceManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: all-db

#954 fix(engine): skip variable update listeners for batch operation
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/variables/BatchSetVariablesHandler.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/util/TypedValueField.java
Labels: h2

#982 fix(tests): remove incorrect response body from telemetry stubs
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java
Labels: all-db

#989 chore(engine): bump spin to 1.10.0
  pom.xml
Labels: no-build

#988 chore(engine): make telemetry metric fields consistent to database
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java
Labels: default-build

#980 chore(engine): extend telemetry data with jdk info
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Jdk.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ParseUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: default-build, no-build

#971 CAM-12408: avoid cmmn complexity in task query
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/AuthorizationCheck.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Statistics.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/cmmn/CmmnDisabledTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/ProcessEngineTestRule.java
Labels: default-build

#978 fix(engine): suppress sql exceptions
  engine/src/main/java/org/camunda/bpm/engine/impl/TablePageQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/DbEntityManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/BatchDbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/SimpleDbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandInvocationContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/IdentityInfoManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TableDataManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/IdentityInfo.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/TableData.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/cfg/PersistenceExceptionTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/persistence/SuppressSqlExceptionsTest.java
Labels: all-db

#991 chore(engine+rest): add license key to telemetry
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/WebApplicationUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteLicenseKeyCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetLicenseKeyCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/LicenseKeyData.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/LicenseKeyUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/license/LicenseKeyTelemetryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/ProcessEngineDetailsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryRegistryCounterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterSuiteElement.java
Labels: websphere

#983 test(telemetry): add telemetry IT to ensure reporting works
  internal-dependencies/pom.xml
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java
  qa/integration-tests-engine/src/test/resources-tomcat/org/camunda/bpm/integrationtest/telemetry/processes-connectPlugin.xml
  qa/integration-tests-engine/src/test/resources-wildfly/org/camunda/bpm/integrationtest/telemetry/processes-connectPlugin.xml
Labels: all-as

#995 CAM-12421: chore(engine): add telemetry request timeout configuration
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetryReporter.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ConnectUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/telemetry/TelemetryTaskWorkerMetricsTest.java
  pom.xml
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java
Labels: default-build

#1002 CAM-12471: chore(telemetry): ensure EDE and EDI metrics are passed in telemetry
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: all-db

#1003 CAM-12432М chore(engine): collect dynamic data only when telemetry is enabled
  engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandCounterInterceptor.java
  engine/src/main/java/org/camunda/bpm/engine/impl/metrics/MetricsRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/TelemetryUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryDynamicDataTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryMultipleEnginesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryStaticDataTest.java
Labels: default-build

#999 CAM-12410: use a single proc def join in task query
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/TaskAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/StandaloneTasksAndCmmnDisabledTest.java
Labels: all-db

#1000 CAM-12469: chore(dmn): bump feel scala engine version
  engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/feel/context_function.dmn
  pom.xml
Labels: all-as

#1012 fix(engine): log authorization exceptions on detail log level
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandContext.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/AuthorizationLoggingTest.java
Labels: authorizations

#1008 CAM-12492: fix(telemetry): resolve static camunda integration in telemetry data
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: default-build

#1011 CAM-12411: add new variable index
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.cockroachdb.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.db2.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.h2.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mariadb.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mssql.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mysql.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.oracle.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.postgres.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.13_to_7.14.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.13_to_7.14.sql
Labels: all-db

#1010 fix(qa): fix tear down in telemetry IT
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java
Labels: all-as

#1004 chore(telemetry): send initial message to ET
  engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/Internals.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetryReporter.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryConfigurationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryDynamicDataTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryMultipleEnginesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/NoInitMessageBootstrapEngineCommand.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/NoInitMessageInMemProcessEngineConfiguration.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java
Labels: no-build
