Repository camunda/camunda-bpm-platform, pull requests merged in 2020-12, with the labels that each got.

#1160 feat(openapi): identity endpoints
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/BasicUserCredentialsDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/CheckPasswordPolicyResultDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/CheckPasswordPolicyRuleDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/PasswordPolicyDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/PasswordPolicyRequestDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/PasswordPolicyRuleDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/UserCredentialsDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/UserDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/UserProfileDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/IdentityServiceGroupDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/IdentityServiceGroupInfoDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/IdentityServiceUserDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/security/auth/AuthenticationResult.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/identity/groups/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/identity/password-policy/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/identity/password-policy/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/identity/verify/post.ftl
Labels: rest-api

#1149 CAM-12793: chore(pipelines): resolve pr labels
  .ci/daily/Jenkinsfile
  Jenkinsfile
Labels: no-build, postgresql

#1153 CAM-12751: handle pipeline stage errors
  .ci/daily/Jenkinsfile
  Jenkinsfile
Labels: all-db

#1162 CAM-12819: feat(side-pipe): add slow pipeline with crdb
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: cockroachdb

#1168 chore(ci): extract publishTestResult in shared library
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: h2

#1169 CAM-12867: feat(ci): extract db methods to shared lib
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: h2

#1166 fix(openapi): int32 durationInMills too small
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricActivityInstanceDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceDto.ftl
Labels: rest-api

#1159 chore(dependencies): bump Tomcat to 9.0.40
  parent/pom.xml
Labels: tomcat

#1175 CAM-12851: extract agent methods
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: all-db, no-build

#1171 CAM-12866: extract mvn methods to shared lib
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: cockroachdb, no-build

#1170 CAM-12855: chore(ci): extract withLabels
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: no-build, postgresql

#1126 fix(engine): correct excluding condition in job query
  engine/src/main/java/org/camunda/bpm/engine/impl/JobQueryImpl.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/JobQueryTest.java
Labels: h2

#1191 fix(parse): parse empty extension properties
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParseUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/parse/BpmnParseTest.testParseEmptyExtensionProperty.bpmn
Labels: default-build

#1181 CAM-12830: chore(ci): extract trigger downstream
  Jenkinsfile
Labels: authorizations, no-build

#1183 CAM-12862: chore(ci): extract stash/unstash methods
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: no-build, rest-api

#1184 CAM-12863: Pipeline extract artifact logic
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: all-as, no-build

#1177 CAM-12832: define ACT_IDX_JOB_HANDLER on hashed column on Oracle
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.14_patch_7.14.2_to_7.14.3.sql
Labels: oracle

#1187 CAM-12861: extract runMaven method
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: h2, no-build

#1192 CAM-12892: extract ee update
  Jenkinsfile
Labels: h2, no-build, postgresql

#1186 CAM-12753: chore(ci): add email notification upon build status change
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: no-build

#1198 CAM-12864: chore(ci): use cambpmRunMaven method in Assembly
  Jenkinsfile
Labels: all-as, no-build

#1202 CAM-12877: feat(ci): adjust sidetrack pipeline
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
Labels: cockroachdb, no-build

#1203 CAM-12905: chore(ci): add all rest stages
  Jenkinsfile
Labels: no-build, rest-api

#1195 test(spring/cdi): add dmn juel context tests
  engine-cdi/pom.xml
  engine-cdi/src/test/java/org/camunda/bpm/engine/cdi/test/dmn/DmnJuelTest.java
  engine-cdi/src/test/resources/org/camunda/bpm/engine/cdi/test/dmn/JuelTest.dmn
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/dmn/DmnJuelTest.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/dmn/Testbean.java
  engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/dmn/DmnJuelTest-applicationContext.xml
  engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/dmn/JuelTest.dmn
Labels: default-build

#1209 CAM-12907: chore(ci): add missing engine-IT stages
  Jenkinsfile
Labels: all-as, no-build

#1210 fix(engine): fix parsing of weeks >3 of ISO8601 durations
  engine/src/main/java/org/camunda/bpm/engine/impl/calendar/DurationHelper.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/calendar/DurationHelperTest.java
Labels: default-build

#1213 CAM-12899: Pipeline imp mvn
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: postgresql
