Repository camunda/camunda-bpm-platform, pull requests merged in 2020-05, with the labels that each got.

#808 CAM-11116: fix(db): set correct oracle db column type
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.decision.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
Labels: oracle

#806 CAM-11669: use latest OpenJPA 2.x patch level
  engine/pom.xml
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/jpa/BigIntegerIdJPAEntity.java
  engine/src/test/resources/META-INF/persistence.xml
  parent/pom.xml
Labels: default-build

#813 CAM-11669: use OpenJPA 1 for old-engine tests
  qa/test-old-engine/pom.xml
Labels: h2

#814 CAM-10419: remove dependency plugin execution from mgmt sections
  qa/test-db-instance-migration/test-migration/pom.xml
  qa/test-db-rolling-update/create-new-engine/pom.xml
  qa/test-db-rolling-update/test-old-engine/pom.xml
Labels: migration

#803 CAM-11323: do not expose shaded libraries
  engine-dmn/engine/pom.xml
  engine-dmn/feel-scala/pom.xml
  engine/pom.xml
  parent/pom.xml
Labels: default-build

#821 CAM-11750: fix(engine): ensure distinct deploy time timestamps
  engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessApplicationDeploymentTest.java
Labels: mysql

#820 CAM-11778: chore(engine): fix typo in method argument
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/BpmnActivityBehavior.java
Labels: default-build

#819 CAM-11109: fix empty properties filter
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/FilterEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/JsonUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterPropertiesTest.java
Labels: all-db, rest-api

#828 CAM-11774: fix(rest): remove unused error details property
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/get.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/ExternalTaskDto.java
Labels: rest-api

#829 CAM-11899: fix large data tests
  qa/large-data-tests/pom.xml
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/util/EngineDataGenerator.java
Labels: default-build

#822 CAM-11887: remove distinct from fetch and lock on postgres
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/ExternalTask.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/FetchExternalTaskAuthorizationTest.java
Labels: all-db

#837 fix(rest-openapi): fix string arrays definitions in query parameters
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/deployment-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/external-task-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/process-definition-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.ftl
Labels: rest-api

#839 CAM-11950: separate Spring boot build into assembly and distro
  pom.xml
  spring-boot-starter/pom.xml
  spring-boot-starter/starter-qa/pom.xml
Labels: run

#840 CAM-11950: fix(jboss): revert distro and distro-ce profile merge
  distro/jbossas7/pom.xml
Labels: jbosseap, wildfly
