Repository camunda/camunda-bpm-platform, pull requests merged in 2020-03, with the labels that each got.

#697 CAM-11510: Rename configuration class
  distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunConfiguration.java
Labels: h2

#700 chore(rest-openapi): extract text formatting function
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableQueryParameterDto.ftl
Labels: rest-api

#701 CAM-11302: add support for two configuration yml files
  distro/run/assembly/assembly.xml
  distro/run/assembly/resources/default.yml
  distro/run/assembly/resources/production.yml
  distro/run/assembly/resources/start.bat
  distro/run/assembly/resources/start.sh
  distro/run/qa/pom.xml
  distro/run/qa/src/test/java/org/camunda/bpm/run/qa/ProductionConfigurationIntegrationTest.java
  distro/run/qa/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java
  distro/run/qa/src/test/resources/ProductionConfigurationIntegrationTest_production.yml
Labels: h2

#702 CAM-11481: include DDL SQL scripts in distro
  distro/run/distro/assembly.xml
  distro/run/distro/pom.xml
  distro/run/qa/src/test/java/org/camunda/bpm/run/qa/SqlAvailabilityIntegrationTest.java
Labels: h2

#705 CAM-11449: include license and notice files in run distro
  distro/run/assembly/assembly.xml
  distro/run/assembly/pom.xml
Labels: h2

#704 CAM-11297: include a README file in the packaged Run distro
  distro/run/README.md
  distro/run/assembly/assembly.xml
  distro/run/assembly/resources/README.txt
Labels: h2

#703 CAM-11298: add default configuration for both configuration files in Camunda BPM Run
  distro/run/assembly/resources/default.yml
  distro/run/assembly/resources/production.yml
  distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunAuthenticationProperties.java
Labels: h2

#707 [CAM-11183] feat(engine): make scheduled state updates deployment-aware
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractSetJobDefinitionStateCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractSetStateCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ProcessDefinitionManager.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ActivateJobDefinitionTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/SuspendJobDefinitionTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/suspensionstate/MultiTenancyJobDefinitionSuspensionStateTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/suspensionstate/MultiTenancyProcessDefinitionSuspensionStateTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/repository/ProcessDefinitionSuspensionTest.java
Labels: h2

#712 chore(webapp-integration): move integration tests to main source dir…
  distro/run/qa/integration-tests/pom.xml
  distro/run/qa/runtime/pom.xml
  qa/integration-tests-webapps/integration-tests/pom.xml
  qa/integration-tests-webapps/integration-tests/src/main/domains/domain1/config/default-web.xml
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/AbstractWebIntegrationTest.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/AbstractWebappUiIntegrationTest.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/CsrfPreventionIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/ErrorPageIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/ExceptionLoggerIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/HttpHeaderSecurityIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/LoginIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/SessionCookieSecurityIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/SetupTests.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/TestProperties.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/rest/EmbeddedEngineRest_WILDFLY.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/rest/RestIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/rest/RestJaxRs2IT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/rest/beans/CustomProcessEngineProvider.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/rest/beans/CustomRestApplication.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/util/SeleniumScreenshotRule.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/util/TestUtil.java
  qa/integration-tests-webapps/integration-tests/src/main/resources/testconfig.properties
  qa/integration-tests-webapps/pom.xml
  qa/integration-tests-webapps/shared-engine/pom.xml
  qa/integration-tests-webapps/standalone-engine/pom.xml
  spring-boot-starter/starter-qa/integration-test-webapp/runtimes/pom.xml
Labels: webapp-integration

#715 CAM-11537: feat(open-api): add schema log endpoints
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/sort-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/sort-props.ftl
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SchemaLogEntryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SchemaLogQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/schema/log/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/schema/log/post.ftl
Labels: rest-api

#706 CAM-11529: add documentation for condition endpoint
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/EvaluationConditionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/condition/post.ftl
Labels: rest-api

#711 CAM-8724: fix(engine): timer jobs are executed on time
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobManager.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobAcquisitionBackoffIdleTest.java
Labels: all-as

#720 feat(engine): introduce historic task permissions
  engine/src/main/java/org/camunda/bpm/engine/EntityTypes.java
  engine/src/main/java/org/camunda/bpm/engine/authorization/HistoricTaskPermissions.java
  engine/src/main/java/org/camunda/bpm/engine/authorization/Resources.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ResourceTypeUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
Labels: authorizations

#722 feat(engine): add config flag to enable historic instance permissions
  engine/src/main/java/org/camunda/bpm/engine/AuthorizationService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AuthorizationCheckCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/EnableHistoricInstancePermissionsTest.java
Labels: authorizations

#730 CAM-11530: add documentation for signal endpoint
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SignalDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/signal/post.ftl
Labels: rest-api

#739 CAM-11662: feat(open-api): add dto macro
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/AtomLink.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/CountResultDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/EvaluationConditionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ExceptionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/MultiFormDeploymentDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/MultiFormVariableBinaryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ParseExceptionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/PatchVariablesDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ProblemDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ProcessEngineDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ResourceReportDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SchemaLogEntryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SchemaLogQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SignalDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SuspensionStateDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableQueryParameterDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableValueDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VersionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/CaseDefinitionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DecisionDefinitionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DecisionRequirementsDefinitionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DeploymentDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/ProcessDefinitionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ActivityInstanceDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ActivityInstanceIncidentDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceSuspensionStateAsyncDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceSuspensionStateDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesByProcessDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/TransitionInstanceDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/TriggerVariableValueDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/batch/BatchDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/batch/DeleteProcessInstancesDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/modification/ProcessInstanceModificationDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/modification/ProcessInstanceModificationInstructionDto.ftl
Labels: rest-api

#733 CAM-11550: feat(open-api): add task comment endpoints
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/LinkableDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/DeploymentDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/TriggerVariableValueDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/CommentDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/create/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/{commentId}/get.ftl
Labels: rest-api

#744 CAM-11578: Bump tomcat version to > 9.0.30
  distro/tomcat/assembly/src/conf/server.xml
  parent/pom.xml
  pom.xml
  qa/tomcat-runtime/src/main/conf/server.xml
Labels: tomcat

#735 CAM-11531: add OpenAPI documentation for message endpoint
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/message/CorrelationMessageDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/message/MessageCorrelationResultWithVariableDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ExecutionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/message/post.ftl
Labels: rest-api

#741 CAM-11552: feat(open-api): add task id-link endpoints
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/IdentityLinkDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/identity-links/delete/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/identity-links/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/identity-links/post.ftl
Labels: rest-api

#751 CAM-11679: re-integrate hook method for job execution
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
  javaee/jobexecutor-ra/src/main/java/org/camunda/bpm/container/impl/threading/ra/inflow/JcaInflowExecuteJobsRunnable.java
Labels: default-build

#725 [CAM-11516] chore(deps): bump feel scala engine to 1.11.0
  engine-dmn/feel-scala/src/main/java/org/camunda/bpm/dmn/feel/impl/scala/ScalaFeelEngine.java
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/CustomFunctionTest.java
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/function/ExternalFunctionTest.java
  engine-dmn/feel-scala/src/test/java/org/camunda/bpm/dmn/engine/feel/helper/FeelRule.java
  pom.xml
Labels: h2

#756 CAM-11532: add documentation for metric endpoints
  engine-rest/engine-rest-openapi/README.md
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/LinkableDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/metrics/MetricsIntervalResultDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/metrics/MetricsResultDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/{metrics-name}/sum/get.ftl
Labels: rest-api

#753 fix(engine): remove redundant task instance report authorization checks
  engine/src/main/java/org/camunda/bpm/engine/HistoryService.java
  engine/src/main/java/org/camunda/bpm/engine/authorization/Permissions.java
  engine/src/main/java/org/camunda/bpm/engine/authorization/TaskPermissions.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceReportImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/CommandChecker.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/auth/AuthorizationCommandChecker.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/multitenancy/TenantCommandChecker.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskReportManager.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
Labels: authorizations

#734 feat(engine): add removal time column to authorization table
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.db2.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.h2.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mariadb.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mssql.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mysql.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.oracle.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.postgres.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.12_to_7.13.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.12_to_7.13.sql
Labels: all-db

#723 feat(engine): historic task authorization is enforced for task query
  engine/src/main/java/org/camunda/bpm/engine/impl/db/AuthorizationCheck.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
Labels: authorizations, no-build

#726 feat(engine): historic task authorization is enforced for variable query
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricVariableInstanceAuthorizationTest.java
Labels: authorizations

#728 feat(engine): historic task authorization is enforced for detail query
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricDetailAuthorizationTest.java
Labels: authorizations

#731 feat(engine): add granting of hist task read permission
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/auth/DefaultAuthorizationProvider.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
Labels: authorizations

#748 feat(engine): historic task authorization is enforced for ident.link log
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIdentityLinkLog.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricIdentityLinkLogAuthorizationTest.java
Labels: authorizations

#749 feat(engine): introduce READ_VARIABLE permission for historic tasks
  engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/authorization/HistoricTaskPermissions.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/auth/DefaultAuthorizationProvider.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/util/AuthManagerUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/TaskReadVariablePermissionAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricDetailAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricVariableInstanceAuthorizationTest.java
Labels: authorizations

#729 feat(open-api): add task endpoints to the open api
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/sort-props.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/task-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/FormDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/CompleteTaskDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/SortTaskQueryParametersDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskBpmnErrorDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskEscalationDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/UserIdDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/data/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/count/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/count/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/create/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/assignee/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/bpmnError/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/bpmnEscalation/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/claim/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/create/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/{commentId}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/complete/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/delegate/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/deployed-form/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/form-variables/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/form/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/identity-links/delete/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/identity-links/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/identity-links/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/rendered-form/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/resolve/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/submit-form/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/unclaim/post.ftl
Labels: rest-api

#740 feat(engine): set removal time to auth when identity link is added
  engine/src/main/java/org/camunda/bpm/engine/authorization/Authorization.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/auth/DefaultAuthorizationProvider.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/AbstractRemovalTimeTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/HistoricRootProcessInstanceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyStartTest.java
Labels: no-build

#742 feat(engine): include deletion of authorizations in history cleanup
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupRemovalTimeTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerAuthorizationsTest.java
Labels: no-build

#743 feat(engine): set removal time to authorization on creation
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SaveAuthorizationCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationEntity.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyStartTest.java
Labels: no-build

#757 CAM-11553: feat(rest): add openapi task variables endpoints
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/variables/{varName}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/data/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/data/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/variables/{varName}/put.ftl
Labels: rest-api

#747 feat(engine): include authorization in set removal time batch operation
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeHierarchicalTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeNonHierarchicalTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/batch/helper/BatchSetRemovalTimeRule.java
Labels: no-build

#760 CAM-11554: feat(rest): add openapi task local variables endpoints
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/data/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/data/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/localVariables/{varName}/put.ftl
Labels: rest-api

#750 feat(rest): expose removal time & root process instance id for auth
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/authorization/AuthorizationDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AuthorizationRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AuthorizationRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
Labels: no-build

#765 feat(engine): historic auth is removed when deleting hist task
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/HistoricTaskInstanceManager.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
Labels: no-build
