Repository camunda/camunda-bpm-platform, pull requests merged in 2021-06, with the labels that each got.

#1476 chore(qa): disable tests on galera setup in old-engine
  qa/test-old-engine/pom.xml
Labels: mariadb, pipelines

#1456 chore(webapps): add validation column to variables table
  webapps/camunda-commons-ui/lib/widgets/variables-table/cam-widget-variables-table.html
  webapps/camunda-commons-ui/lib/widgets/variables-table/cam-widget-variables-table.js
  webapps/camunda-commons-ui/lib/widgets/variables-table/cam-widget-variables-table.less
  webapps/camunda-commons-ui/resources/img/error-sign.svg
  webapps/ui/cockpit/client/scripts/components/variables/variable-add-dialog.html
  webapps/ui/cockpit/client/scripts/components/variables/variable-add-dialog.js
  webapps/ui/cockpit/client/scripts/services/main.js
  webapps/ui/cockpit/client/scripts/services/variable-utils.js
  webapps/ui/cockpit/plugins/base/app/views/processInstance/addVariableAction.js
Labels: e2e

#1483 fix(ci): add missing leading slash to downstream project path
  Jenkinsfile
Labels: pipelines, run

#1492 chore(rest+openapi): allow assigning a procInstId to a task comment
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/CommentDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/create/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/{commentId}/get.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/CommentDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskCommentResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
Labels: rest-api

#1491 fix(tasklist): make adding procInstId to task comment configurable
  webapps/camunda-bpm-sdk-js/lib/api-client/resources/task.js
  webapps/ui/common/scripts/services/cam-configuration.js
  webapps/ui/tasklist/client/scripts/config/config.js
  webapps/ui/tasklist/client/scripts/task/plugins/action/modals/cam-tasklist-comment-form.js
Labels: e2e

#1488 chore(deps): bump form-js
  webapps/camunda-commons-ui/lib/widgets/variables-table/cam-widget-variables-table.less
  webapps/package-lock.json
  webapps/package.json
Labels: e2e

#1338 SUPPORT-9969
  distro/jbossas7/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/dmn/camunda-engine-dmn/main/module.xml
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/cdi/CdiBeanResolutionTest.java
Labels: all-as, jboss, jbosseap, wildfly

#1472 fix(webapps): fix frontend license book
  webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js
Labels: e2e

#1467 chore(deps): bump dev dependencies to latest versions
  webapps/Gruntfile.js
  webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js
  webapps/camunda-commons-ui/grunt/tasks/persistify.js
  webapps/camunda-commons-ui/lib/services/HttpClient.js
  webapps/grunt/tasks/license-check.js
  webapps/package-lock.json
  webapps/package.json
  webapps/ui/admin/client/scripts/camunda-admin-bootstrap.js
  webapps/ui/cockpit/client/scripts/directives/pie-chart.js
  webapps/ui/cockpit/client/scripts/pages/decisionInstance.js
  webapps/ui/cockpit/client/scripts/pages/processInstance.js
  webapps/ui/cockpit/client/scripts/repository/deployments/plugins/actions/delete/modals/cam-cockpit-delete-deployment-modal-ctrl.js
  webapps/ui/common/scripts/services/locales.js
  webapps/ui/tasklist/client/scripts/camunda-tasklist-bootstrap.js
  webapps/ui/welcome/client/scripts/camunda-welcome-bootstrap.js
Labels: e2e

#1495 chore(ci): add repo maven param
  Jenkinsfile
Labels: no-build

#1490 chore(ci): adjust h2-in-memory engine profile
  Jenkinsfile
  engine/pom.xml
Labels: all-as, all-db, no-build

#1473 feat(spring-boot): bump spring-boot to 2.5
  parent/pom.xml
  spring-boot-starter/starter/pom.xml
Labels: run, spring-boot

#1503 fix(build): use global cam-SDK
  webapps/.stylelintrc.json
  webapps/camunda-commons-ui/lib/services/HttpClient.js
Labels: default-build, e2e, webapp-integration

#1466 feat(engine): add Graal.js support
  distro/jbossas7/modules/pom.xml
  distro/jbossas7/modules/src/main/modules/com/ibm/icu/icu4j/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/camunda/bpm/camunda-engine/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/graalvm/js/js-scriptengine/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/graalvm/js/js/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/graalvm/regex/regex/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/graalvm/sdk/graal-sdk/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/graalvm/truffle/truffle-api/main/module.xml
  distro/jbossas7/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/deployment/processor/ModuleDependencyProcessor.java
  distro/jbossas7/webapp-standalone/pom.xml
  distro/jbossas7/webapp/pom.xml
  distro/run/core/pom.xml
  distro/run/pom.xml
  distro/tomcat/assembly/assembly.xml
  distro/tomcat/assembly/pom.xml
  distro/tomcat/webapp-standalone/pom.xml
  distro/wildfly/assembly/assembly.xml
  distro/wildfly/assembly/pom.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/com/ibm/icu/icu4j/main/module.xml
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/camunda-engine/main/module.xml
  distro/wildfly/modules/src/main/modules/org/graalvm/js/js-scriptengine/main/module.xml
  distro/wildfly/modules/src/main/modules/org/graalvm/js/js/main/module.xml
  distro/wildfly/modules/src/main/modules/org/graalvm/regex/regex/main/module.xml
  distro/wildfly/modules/src/main/modules/org/graalvm/sdk/graal-sdk/main/module.xml
  distro/wildfly/modules/src/main/modules/org/graalvm/truffle/truffle-api/main/module.xml
  distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/deployment/processor/ModuleDependencyProcessor.java
  engine-dmn/engine/pom.xml
  engine-plugins/spin-plugin/pom.xml
  engine-rest/assembly/pom.xml
  engine-spring/compatibility-test-spring4/pom.xml
  engine-spring/core/pom.xml
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/AbstractScriptTaskTest.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskGraalJsTest.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskNashornTest.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskTest.java
  engine/pom.xml
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/scripting/engine/ScriptEngineResolver.java
  engine/src/main/java/org/camunda/bpm/engine/impl/scripting/engine/ScriptingEngines.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/UpdateProcessInstancesSuspendStateAsyncTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/UpdateProcessInstancesSuspendStateTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/scripttask/AbstractScriptTaskTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/scripttask/ScriptTaskGraalJsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/scripttask/ScriptTaskNashornTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/scripttask/ScriptTaskTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/scripting/ScriptEngineNameJavaScriptTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/scripttask/sum.js
  examples/invoice/pom.xml
  internal-dependencies/pom.xml
  parent/pom.xml
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/AbstractScriptEngineSupportTest.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/JavascriptScriptEngineSupportGraalJsTest.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/scriptengine/JavascriptScriptEngineSupportNashornTest.java
  qa/test-db-upgrade/pom.xml
  qa/test-old-engine/pom.xml
  qa/wildfly-runtime/src/main/common/modules/org/camunda/bpm/camunda-engine/main/module.xml
Labels: all-as, default-build, pipelines, run, spring-boot

#1478 chore(engine): support Java 15 execution
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/FetchExternalTasksCmd.java
Labels: default-build, pipelines

#1508 chore(distro): add commons-dbcp to standalone webapps
  distro/jbossas7/webapp-standalone/pom.xml
  distro/tomcat/webapp-standalone/pom.xml
Labels: webapp-integration

#1510 feat(run): support external JVM options via JAVA_OPTS
  distro/run/assembly/resources/start.bat
  distro/run/assembly/resources/start.sh
Labels: run

#1512 chore(test): adjust script test to consider Spin env script
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/scripttask/ScriptTaskGraalJsTest.java
Labels: default-build

#1505 chore(ci): replace disableConcurrentBuilds opt with throttleJobProperty
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: rest-api
