Repository camunda/camunda-bpm-platform, pull requests merged in 2021-02, with the labels that each got.

#1295 chore(engine): support cleanup of task metrics
  engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/task-worker/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/{metrics-name}/sum/get.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/MetricsRestService.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/MetricsRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/MetricsRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/ManagementService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteMetricsCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteTaskMetricsCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupBatch.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupHelper.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupRemovalTime.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/MeterLogManager.java
  engine/src/main/java/org/camunda/bpm/engine/management/Metrics.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/TaskMetrics.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/DeleteMetricsAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/DeleteTaskMetricsAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryCleanupTaskMetricsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupRemovalTimeTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerTaskMetricsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/MetricsManagerForCleanupTest.java
Labels: all-db, pipelines, rest-api

#1302 chore(ci): switch postgesql 10.7 to 10.13
  .ci/config/matrices.yaml
Labels: default-build, no-build, pipelines, postgresql

#1299 fix(ci): fix matrix label resolve
  .ci/daily/Jenkinsfile
  Jenkinsfile
Labels: authorizations, no-build, pipelines

#1303 feat(engine): allow annotations on incidents
  engine/src/main/java/org/camunda/bpm/engine/EntityTypes.java
  engine/src/main/java/org/camunda/bpm/engine/RuntimeService.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricIncident.java
  engine/src/main/java/org/camunda/bpm/engine/impl/RuntimeServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetAnnotationForIncidentCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricIncidentEventEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoryEventTypes.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/HistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/IncidentEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/UserOperationLogManager.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/Incident.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/cockroachdb_engine_7.14_to_7.15.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.14_to_7.15.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.14_to_7.15.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.14_to_7.15.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.14_to_7.15.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.14_to_7.15.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.14_to_7.15.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.14_to_7.15.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Incident.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/AuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/IncidentAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/IncidentTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/IncidentUserOperationLogTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/mgmt/IncidentTest.shouldSetActivityIdProperty.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/mgmt/IncidentTest.shouldUpdateIncidentAfterCompaction.bpmn
Labels: all-db, pipelines

#1304 chore(engine-rest): add annotation methods to incident
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/AnnotationDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/IncidentDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/incident/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/incident/{id}/annotation/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/incident/{id}/annotation/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/incident/{id}/get.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricIncidentDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/IncidentDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/impl/IncidentResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/IncidentResource.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/IncidentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java
Labels: pipelines, rest-api

#1201 fix(engine): split up UPDATE query in separate queries
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricDecisionInstanceManager.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
Labels: all-db

#1308 chore(rest): bump commons-codec to 1.15 in tests
  engine-rest/engine-rest/pom.xml
Labels: rest-api

#1307 fix(ci): fix wildfly-compatibility rest stage exec dir
  .ci/config/stage-types.yaml
Labels: pipelines, rest-api

#1305 CAM-12852: fix(engine): set retries to more than 2100 jobs
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobManager.java
  qa/large-data-tests/pom.xml
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/SetJobRetriesAsyncTest.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/BatchModificationJobHelper.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/util/EngineDataGenerator.java
Labels: all-as, pipelines, rolling-update, sqlserver, webapp-integration

#1265 feat(env): add support for WildFly 21
  distro/wildfly/assembly/src/wildfly/standalone-full.xml
  distro/wildfly/assembly/src/wildfly/standalone.xml
  parent/pom.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml
  qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
Labels: pipelines, postgresql, wildfly

#1298 feat(engine-rest): Optimize variable update API object value parameter
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/optimize/OptimizeRestService.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/optimize/OptimizeVariableUpdateRestServiceTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/OptimizeService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/optimize/OptimizeHistoricVariableUpdateQueryCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/optimize/OptimizeServiceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/optimize/GetHistoricVariableUpdatesForOptimizeTest.java
  qa/large-data-tests/src/test/java/org/camunda/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java
Labels: rest-api

#1311 CAM-13059: fix(ci): refactor remaining jenkins matrices
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: default-build, no-build, pipelines, rest-api

#1309 improve(engine): improve telemetry test assertion
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
Labels: default-build

#1314 feat(engine+rest): serve camunda-forms form keys
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/deployed-start-form/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/deployed-form/get.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/impl/ProcessDefinitionResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/ContentTypeUtil.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessDefinitionRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractGetDeployedFormCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/form/FormServiceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/DeployedCamundaFormsProcess.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/start.form.json
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/task.form.json
Labels: rest-api

#1306 feat(cockpit): allow annotation of incidents
  webapps/camunda-bpm-sdk-js/lib/api-client/resources/incident.js
  webapps/camunda-commons-ui/lib/widgets/annotation/cam-annotation-edit.html
  webapps/camunda-commons-ui/lib/widgets/annotation/cam-annotation-edit.js
  webapps/camunda-commons-ui/lib/widgets/annotation/cam-annotation-edit.less
  webapps/camunda-commons-ui/lib/widgets/annotation/cam-annotation-modal.html
  webapps/camunda-commons-ui/lib/widgets/annotation/cam-annotation-modal.js
  webapps/camunda-commons-ui/lib/widgets/index.js
  webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/dto/IncidentDto.java
  webapps/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/incident.xml
  webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/IncidentRestServiceTest.java
  webapps/ui/cockpit/client/scripts/directives/incidents-tab.html
  webapps/ui/cockpit/client/scripts/directives/incidentsTab.js
  webapps/ui/cockpit/client/styles/styles-components.less
  webapps/ui/cockpit/client/styles/styles.less
Labels: e2e

#1315 fix(engine): improve bad performing sql query for historic task query
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
Labels: all-db, pipelines

#1321 feat(webapps): add withIncident filter to process instance
  webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/dto/query/AbstractProcessInstanceQueryDto.java
  webapps/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processInstance.xml
  webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/ProcessInstanceRestServiceTest.java
Labels: all-db, pipelines, webapp-integration

#1322 CAM-12992: telemetry doesn't report lambda/anonymous commands
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceReportImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceReportImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskReportImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandCounterInterceptor.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/FailedJobListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupHandler.java
  engine/src/main/java/org/camunda/bpm/engine/impl/metrics/MetricsQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/metrics/reporter/DbMetricsReporter.java
  engine/src/main/java/org/camunda/bpm/engine/impl/metrics/reporter/MetricsCollectionTask.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/deploy/DeleteDeploymentFailListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/deploy/DeploymentFailListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryDynamicDataTest.java
  webapps/src/main/java/org/camunda/bpm/cockpit/impl/db/QueryServiceImpl.java
  webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/base/sub/resources/ProcessDefinitionResource.java
  webapps/src/main/java/org/camunda/bpm/cockpit/impl/plugin/resources/ProcessInstanceRestService.java
Labels: mariadb, pipelines

#1325 fix(engine): prevent removal time update deadlock
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Attachment.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Comment.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricActivityInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricBatch.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDecisionInputInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDecisionInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDecisionOutputInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricExternalTaskLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIdentityLinkLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/UserOperationLogEntry.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java
Labels: sqlserver

#1330 fix(openapi): enable multiple return types in responses
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/report/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/deployed-start-form/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/deployed-form/get.ftl
Labels: rest-api

#1319 chore(telemetry): update telemetry dialog
  webapps/camunda-bpm-sdk-js/lib/api-client/resources/telemetry.js
  webapps/camunda-commons-ui/lib/analytics/index.js
  webapps/camunda-commons-ui/lib/analytics/modal.html
  webapps/camunda-commons-ui/lib/analytics/styles.less
  webapps/ui/admin/client/scripts/pages/analytics.html
  webapps/ui/common/styles/cam-webapps-common.less
Labels: e2e
