Repository camunda/camunda-bpm-platform, pull requests merged in 2021-07, with the labels that each got.

#1515 chore(engine): remove unused import from joda-time
  engine/src/main/java/org/camunda/bpm/engine/impl/calendar/DateTimeUtil.java
Labels: default-build

#1516 fix(engine-rest): add empty check for deployment activation time
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/DeploymentRestServiceImpl.java
Labels: rest-api

#1518 chore(distro): update json-path modules
  distro/jbossas7/modules/pom.xml
  distro/jbossas7/modules/src/main/modules/com/jayway/jsonpath/json-path/main/module.xml
  distro/jbossas7/modules/src/main/modules/net/minidev/accessors-smart/main/module.xml
  distro/jbossas7/modules/src/main/modules/net/minidev/json-smart/main/module.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/com/jayway/jsonpath/json-path/main/module.xml
  distro/wildfly/modules/src/main/modules/net/minidev/accessors-smart/main/module.xml
  distro/wildfly/modules/src/main/modules/net/minidev/json-smart/main/module.xml
Labels: all-as

#1509 chore(*): remove commons-dbcp
  distro/jbossas7/webapp-standalone/pom.xml
  distro/jbossas7/webapp-standalone/src/main/webapp/WEB-INF/applicationContext.xml
  distro/tomcat/webapp-standalone/pom.xml
  distro/tomcat/webapp-standalone/src/main/webapp/WEB-INF/applicationContext.xml
  engine-spring/compatibility-test-spring4/pom.xml
  engine-spring/core/pom.xml
  engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/jpa/JPASpringTest-context.xml
  engine/pom.xml
  internal-dependencies/pom.xml
  parent/pom.xml
Labels: all-as, default-build, migration, rolling-update, run, spring-boot, webapp-integration

#1521 chore(project): bump spin version to 1.11.0
  pom.xml
Labels: all-as, rest-api, webapp-integration

#1394 CAM-13361: feat(project): add maven wrapper
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  TESTING.md
  model-api/bpmn-model/README.asciidoc
  mvnw
  mvnw.cmd
  pom.xml
  qa/README.md
  qa/large-data-tests/README.md
  qa/test-db-instance-migration/README.md
  qa/test-db-rolling-update/README.md
  qa/test-db-upgrade/README.md
  qa/test-old-engine/README.md
Labels: e2e

#1522 CAM-13328: feat(engine): add wildfly 23 support
  .ci/daily/Jenkinsfile
  Jenkinsfile
  distro/wildfly/assembly/src/wildfly/standalone-full.xml
  distro/wildfly/assembly/src/wildfly/standalone.xml
  parent/pom.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml
  qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
Labels: wildfly

#1502 fix(tasklist): don't allow double group assignment
  webapps/ui/tasklist/client/scripts/task/controller/cam-tasklist-task-groups-ctrl.js
  webapps/ui/tasklist/client/scripts/task/modals/cam-tasklist-groups-modal.html
Labels: e2e

#1489 Switch into context of process application before deployment
  distro/jbossas7/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/service/ProcessApplicationDeploymentService.java
  distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/service/ProcessApplicationDeploymentService.java
  engine/src/main/java/org/camunda/bpm/application/AbstractProcessApplication.java
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/deployment/spring/timer/ApplicationContext.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/deployment/spring/timer/MyBean.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/deployment/spring/timer/SpringServletPATimerStartEventExpressionTest.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/cdi/CdiBeanResolutionOnDeploymentTest.java
  qa/integration-tests-engine/src/test/resources/META-INF/scan_for_definitions_processes.xml
  qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/deployment/spring/timer/start-event-expression-web.xml
  qa/integration-tests-engine/src/test/resources/org/camunda/bpm/integrationtest/deployment/spring/timer/timer-start-event-process.bpmn
Labels: all-as

#1529 chore(quarkus-extension): add initial project structure
  .ci/config/stage-types.yaml
  Jenkinsfile
  distro/jbossas7/subsystem/pom.xml
  parent/pom.xml
  pom.xml
  quarkus-extension/README.md
  quarkus-extension/engine/README.md
  quarkus-extension/engine/deployment/pom.xml
  quarkus-extension/engine/deployment/src/main/java/org/camunda/bpm/quarkus/engine/extension/deployment/impl/CamundaEngineProcessor.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/UnitTest.java
  quarkus-extension/engine/pom.xml
  quarkus-extension/engine/runtime/pom.xml
  quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaEngineRecorder.java
  quarkus-extension/engine/runtime/src/main/resources/META-INF/quarkus-extension.properties
  quarkus-extension/engine/runtime/src/main/resources/META-INF/quarkus-extension.yaml
  quarkus-extension/pom.xml
  webapps/pom.xml
  webapps/src/test/java/org/camunda/bpm/webapp/impl/security/auth/ContainerAuthenticationFilterTest.java
Labels: default-build

#1539 test(engine): use java 8 method signature
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/TaskMetricsTest.java
Labels: default-build

#1538 fix(open-api): correct response of incident count
  engine-rest/engine-rest-openapi/src/main/templates/paths/incident/count/get.ftl
Labels: rest-api

#1545 CAM-13771: remove spring-boot-loader-tools dependency
  spring-boot-starter/starter/pom.xml
Labels: run, spring-boot
