Repository camunda/camunda-bpm-platform, pull requests merged in 2021-08, with the labels that each got.

#1543 CAM-13763: chore(maven): bump javadoc plugin version
  parent/pom.xml
  pom.xml
Labels: default-build

#1551 chore(deps): bump quarkus to 2.1.0.Final
  parent/pom.xml
Labels: default-build

#1547 chore(quarkus-extension): disable engine-cdi interceptors by default
  quarkus-extension/engine/deployment/src/main/resources/application.properties
  quarkus-extension/engine/qa/src/test/java/org/camunda/bpm/engine/cdi/test/interceptor/CompleteTaskInterceptor.java
  quarkus-extension/engine/qa/src/test/java/org/camunda/bpm/engine/cdi/test/interceptor/StartProcessInterceptor.java
Labels: no-build

#1519 feat(engine+rest): allow resolving called processes before runtime
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/repository/CalledProcessDefinitionDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/ProcessDefinitionResource.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/repository/impl/ProcessDefinitionResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessDefinitionRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/RepositoryService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/RepositoryServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CommandLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetStaticCalledProcessDefinitionCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/core/model/BaseCallableElement.java
  engine/src/main/java/org/camunda/bpm/engine/impl/repository/CalledProcessDefinitionImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/CallableElementUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/EngineUtilLogger.java
  engine/src/main/java/org/camunda/bpm/engine/repository/CalledProcessDefinition.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ProcessDefinitionAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/repository/RepositoryServiceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/call-activities-with-references.bpmn
  engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/call_activities_with_tenants.bpmn
  engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/dynamic-call-activities.bpmn
Labels: default-build, pipelines, rest-api

#1546 test(quarkus-extension): add jira ticket for copied ProgrammaticBeanLookupTest
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/lookup/ProgrammaticBeanLookupTest.java
Labels: no-build

#1550 chore(engine-cdi): fix javadocs of BusinessProcessScoped annotation
  engine-cdi/src/main/java/org/camunda/bpm/engine/cdi/annotation/BusinessProcessScoped.java
Labels: no-build

#1553 feat(engine): integrate Liquibase
  database/pom.xml
  distro/run/distro/assembly.xml
  distro/sql-script/pom.xml
  distro/tomcat/distro/assembly.xml
  distro/wildfly/distro/assembly.xml
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml
Labels: all-db

#1557 chore(sql-script): test equality of Liquibase installation
  distro/sql-script/pom.xml
  distro/sql-script/src/test/java/org/camunda/bpm/sql/test/SqlScriptTest.java
  distro/sql-script/src/test/resources/properties-from-pom.properties
Labels: all-db

#1562 chore(open-api): add static-called-process-definitions
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/repository/CalledProcessDefinitionDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/static-called-process-definitions/get.ftl
Labels: rest-api

#1572 fix(engine): prevent deadlock on SQL Server in cleanup
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/VariableInstance.xml
Labels: sqlserver

#1474 CAM-13547: recreate engine mock before every test
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/AbstractRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricCaseActivityStatisticsRestServiceQueryTest.java
Labels: rest-api, pipelines

#1507 CAM-13625: add azure db support to ci
  .ci/config/matrices.yaml
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: no-build

#1580 fix(engine): fix resource leak when bootstrapping the engine
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Labels: all-db

#1584 chore(engine): change Liquibase baseline to 7.16.0
  distro/sql-script/pom.xml
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.cockroachdb.create.case.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.cockroachdb.create.case.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.cockroachdb.create.decision.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.cockroachdb.create.decision.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.cockroachdb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.cockroachdb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.cockroachdb.create.identity.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.db2.create.case.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.db2.create.case.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.db2.create.decision.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.db2.create.decision.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.db2.create.identity.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.h2.create.case.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.h2.create.case.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.h2.create.decision.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.h2.create.decision.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.h2.create.identity.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mariadb.create.case.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mariadb.create.case.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mariadb.create.decision.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mariadb.create.decision.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mariadb.create.identity.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mssql.create.case.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mssql.create.case.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mssql.create.decision.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mssql.create.decision.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mssql.create.identity.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mysql.create.case.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mysql.create.case.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mysql.create.decision.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mysql.create.decision.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mysql.create.identity.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.oracle.create.case.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.oracle.create.case.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.oracle.create.decision.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.oracle.create.decision.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.oracle.create.identity.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.postgres.create.case.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.postgres.create.case.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.postgres.create.decision.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.postgres.create.decision.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.postgres.create.identity.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml
Labels: all-db

#1589 fix(engine): correct OR task query JSON conversion
  engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java
Labels: no-build

#1569 fix(open-api): fix minor errors
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/task-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/variable-instance-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDefinitionsSuspensionStateDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/schema/log/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/user/{id}/credentials/put.ftl
Labels: rest-api

#1579 fix(openapi): add AnyValue type for ConditionalQueryParameterDto
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/AnyValue.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ConditionQueryParameterDto.ftl
Labels: rest-api

#1573 chore(openapi): make sorting prop nullable
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SchemaLogQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricActivityInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricDetailQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricExternalTaskLogQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricVariableInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/batch/HistoricBatchQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/identity/GroupQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/EventSubscriptionQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ExecutionQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDefinitionQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ProcessInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/VariableInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/externaltask/ExternalTaskQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
Labels: rest-api

#1595 chore(engine): add missing table to Liquibase baseline
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.cockroachdb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/baseline/liquibase.postgres.create.engine.sql
Labels: all-db

#1597 fix(qa): revert builder pattern on ProcessEngineConfigurationImpl setter
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Labels: rolling-update

#1596 test(engine): fix failing history level tests
  engine/src/main/java/org/camunda/bpm/engine/impl/test/TestHelper.java
  engine/src/main/java/org/camunda/bpm/engine/test/ProcessEngineRule.java
Labels: default-build

#1359 CAM-11281: feat(engine): add testcontainers integration to test suite
  TESTING.md
  database/pom.xml
  engine/pom.xml
  engine/src/test/resources/container-license-acceptance.txt
  engine/src/test/resources/logback-test.xml
  internal-dependencies/pom.xml
  parent/pom.xml
  pom.xml
  settings/maven/nexus-settings.xml
  test-utils/testcontainers/README.md
  test-utils/testcontainers/pom.xml
  test-utils/testcontainers/src/main/java/org/camunda/impl/test/utils/testcontainers/CamundaCockroachDBContainerProvider.java
  test-utils/testcontainers/src/main/java/org/camunda/impl/test/utils/testcontainers/CamundaMSSQLContainerProvider.java
  test-utils/testcontainers/src/main/java/org/camunda/impl/test/utils/testcontainers/CamundaMariaDBContainerProvider.java
  test-utils/testcontainers/src/main/java/org/camunda/impl/test/utils/testcontainers/CamundaMySqlContainerProvider.java
  test-utils/testcontainers/src/main/java/org/camunda/impl/test/utils/testcontainers/CamundaPostgreSQLContainerProvider.java
  test-utils/testcontainers/src/main/java/org/camunda/impl/test/utils/testcontainers/TestcontainersHelper.java
  test-utils/testcontainers/src/main/resources/META-INF/services/org.testcontainers.containers.JdbcDatabaseContainerProvider
  test-utils/testcontainers/src/main/resources/container-license-acceptance.txt
  test-utils/testcontainers/src/main/resources/testcontainers.properties
  test-utils/testcontainers/src/test/java/org/camunda/impl/test/utils/testcontainers/DatabaseContainerProviderTest.java
  test-utils/testcontainers/src/test/resources/container-license-acceptance.txt
  test-utils/testcontainers/src/test/resources/logback-test.xml
  test-utils/testcontainers/src/test/resources/testcontainers.properties
Labels: no-build

#1590 fix(engine-spring): respect custom beans in scripts
  engine-spring/compatibility-test-spring4/pom.xml
  engine-spring/core/pom.xml
  engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringProcessEngineConfiguration.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/AbstractScriptTaskTest.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskLimitedBeansTest.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskNoBeansTest.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/scripttask/TestbeanNoName.java
  engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskLimitedBeansTest-applicationContext.xml
  engine-spring/core/src/test/resources/org/camunda/bpm/engine/spring/test/scripttask/ScriptTaskNoBeansTest-applicationContext.xml
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Labels: default-build, spring-boot

#1593 fix(engine): include nested call activities in getStaticCalledProcessDefinitions
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetStaticCalledProcessDefinitionCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/repository/RepositoryServiceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/nested-call-activities.bpmn
Labels: default-build
