Repository camunda/camunda-bpm-platform, pull requests merged in 2021-01, with the labels that each got.

#1199 feat(openapi): add variable instance endpoint
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/deserialize-values-parameter.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/variable-instance-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/VariableInstanceDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/VariableInstanceQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/count/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/count/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/{id}/data/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/{id}/get.ftl
Labels: rest-api

#1221 CAM-12956: bump connect to 1.5.2
  distro/jbossas7/modules/src/main/modules/commons-codec/commons-codec/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml
  distro/jbossas7/modules/src/main/modules/org/apache/httpcomponents/httpcore/main/module.xml
  distro/wildfly/modules/src/main/modules/commons-codec/commons-codec/main/module.xml
  distro/wildfly/modules/src/main/modules/org/apache/httpcomponents/httpclient/main/module.xml
  distro/wildfly/modules/src/main/modules/org/apache/httpcomponents/httpcore/main/module.xml
  pom.xml
Labels: wildfly

#1193 feat(engine): config flag to skip output mappings on canceled activities
  engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationDeleteCascadeFireActivityEnd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/io/SkipOutputMappingOnCanceledActitivitesTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/io/SkipOutputMappingOnCanceledActitivitesTest.oneExternalTaskWithOutputMappingAndCatchingErrorBoundaryEvent.bpmn
  engine/src/test/resources/org/camunda/bpm/engine/test/io/SkipOutputMappingOnCanceledActitivitesTest.oneSubprocessWithOutputMappingAndCatchingErrorBoundaryEvent.bpmn
Labels: default-build

#1230 chore(ci): add history level jobs
  Jenkinsfile
Labels: default-build, no-build

#1222 CAM-12744: call incident handler on deletion of non-job incidents
  engine/src/main/java/org/camunda/bpm/engine/impl/incident/IncidentHandler.java
  engine/src/main/java/org/camunda/bpm/engine/impl/incident/IncidentHandling.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/IncidentEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/CreateAndResolveIncidentTest.java
Labels: default-build

#1229 feat(openapi): add job endpoints
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/job-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ConditionQueryParameterDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/JobConditionQueryParameterDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/SuspensionStateDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableQueryParameterDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDuedateDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobSuspensionStateDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/count/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/count/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/retries/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/suspended/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/duedate/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/duedate/recalculate/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/execute/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/priority/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/retries/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/stacktrace/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/suspended/put.ftl
Labels: rest-api

#1231 CAM-12869: add yaml config
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: default-build, no-build

#1239 CAM-12757: chore(ci): add custom retry to steps
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: no-build, rest-api

#1245 revert(ci): revert no-build label name
  Jenkinsfile
Labels: no-build, pipelines, spring-boot

#1246 CAM-12983: feat(ci): add e2e pr label support
  Jenkinsfile
Labels: e2e, pipelines

#1255 CAM-12987: chore(ci): add default-build label to webapp-unit matrix
  .ci/config/stage-types.yaml
Labels: default-build, pipelines

#1253 CAM-12986: detect downstream prs
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
Labels: e2e, migration

#1261 test(starter): adjust timer date
  spring-boot-starter/starter/src/test/resources/bpmn/eventingWithIntermediateCatch.bpmn
Labels: spring-boot

#1185 [CAM-12040]: Add support for nested errorEventDefinitions on external Tasks
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/ExternalTaskFailureDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/externaltask/impl/ExternalTaskResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/ExternalTaskService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ExternalTaskServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/helper/BpmnProperties.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/CamundaErrorEventDefinition.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleExternalTaskFailureCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/core/variable/scope/AbstractVariableScope.java
  engine/src/main/java/org/camunda/bpm/engine/impl/el/VariableScopeElResolver.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ReflectUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithNestedErrorEventDefinition.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithNestedErrorEventDefinitionEmptyExpression.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithNestedErrorEventDefinitionExpressionIncludesErrorMessage.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithNestedErrorEventDefinitionExpressionIncludesNullErrorMessage.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithNestedErrorEventDefinitionNullExpression.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithNestedErrorEventDefinitionTrueAndOutputMapping.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithNestedErrorEventDefinitionVariableExpression.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithTwoNestedErrorEventDefinitionExpressions.bpmn20.xml
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/Bpmn.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/builder/AbstractServiceTaskBuilder.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/builder/CamundaErrorEventDefinitionBuilder.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/BpmnModelConstants.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/impl/instance/camunda/CamundaErrorEventDefinitionImpl.java
  model-api/bpmn-model/src/main/java/org/camunda/bpm/model/bpmn/instance/camunda/CamundaErrorEventDefinition.java
  model-api/bpmn-model/src/test/java/org/camunda/bpm/model/bpmn/builder/ProcessBuilderTest.java
Labels: default-build

#1244 chore(engine): bump Jackson to 2.12.1
  distro/jbossas7/modules/src/main/modules/com/fasterxml/jackson/core/jackson-annotations/main/module.xml
  distro/jbossas7/modules/src/main/modules/com/fasterxml/jackson/core/jackson-core/main/module.xml
  distro/jbossas7/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/main/module.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-annotations/2.12.1/module.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-core/2.12.1/module.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/2.12.1/module.xml
  engine-rest/pom.xml
  pom.xml
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/resources-wildfly/jboss-deployment-structure-spin-json.xml
Labels: all-as

#1234 chore(deps): bump mysql-connector/j to 8.0.22
  database/pom.xml
  settings/maven/nexus-settings.xml
Labels: no-build

#1150 CAM-12776: update resteasy3 version to 3.14.0.Final
  parent/pom.xml
Labels: rest-api

#1256 CAM-12989: fix(ci): adjust db stages run conditions
  .ci/config/stage-types.yaml
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: pipelines, postgresql

#1263 CAM-12986: chore(ci): adjust nexus deployment eval
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: e2e, pipelines

#1264 CAM-12991: chore(ci): reduce yaml file reads
  .ci/daily/Jenkinsfile
  Jenkinsfile
Labels: no-build, pipelines

#1270 fix(ci): create crdb node before when stage evaluation
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: cockroachdb, pipelines

#1269 chore(deps): bump mysql-connector-java from 8.0.22 to 8.0.23
  database/pom.xml
Labels: mysql

#1275 fix(ci): fix compilation errors
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: pipelines

#1273 chore(*): bump Tomcat version
  parent/pom.xml
Labels: pipelines, run, spring-boot, tomcat

#1278 CAM-12776: make sure Resteasy 2 doesn't leak into Resteasy 3…
  engine-rest/engine-rest/pom.xml
Labels: pipelines, rest-api, webapp-integration

#1266 fix(engine): respect or query for historicTaskInstanceQueries
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryOrTest.java
Labels: all-db, pipelines

#1271 feat(openapi): add execution endpoints
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/execution-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/CreateIncidentDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/VariableValueDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ExecutionQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/ExecutionTriggerDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/count/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/count/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/create-incident/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/data/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/data/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/messageSubscriptions/{messageName}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/messageSubscriptions/{messageName}/trigger/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/signal/post.ftl
Labels: rest-api

#1289 chore(test): specify correct history level for historic task query tests
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryOrTest.java
Labels: no-build

#1277 chore(ci): use new syntax of cambpmConditionalRetry
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: all-as, all-db, no-build, pipelines
