Repository camunda/camunda-bpm-platform, pull requests merged in 2021-03, with the labels that each got.

#1331 CAM-10972: add mysql 8 support
  .ci/config/matrices.yaml
Labels: mysql, pipelines

#1339 feat(engine): add withoutDueDate filter for tasks
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricTaskInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java
  engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryExpressionTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryOrTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryTest.java
Labels: all-db

#1341 feat(engine-rest): add withoutDueDate filter for tasks
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/task-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java
Labels: no-build

#1345 feat(engine): add valueNotLike filter for task variables
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricTaskInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/QueryOperator.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Commons.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryOrTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryTest.java
Labels: all-db

#1346 feat(engine): add valueNotLike filter for task variables
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/task-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/ConditionQueryParameterDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java
Labels: rest-api

#1348 fix(engine-rest): return withoutDueDate option when enabled
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/FilterRestServiceInteractionTest.java
Labels: rest-api

#1355 chore(rest): return JSON type for .form files
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/ContentTypeUtil.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessDefinitionRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/form/FormServiceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/DeployedCamundaFormsProcess.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/start.form.json
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/task.form.json
Labels: rest-api

#1328 feat(repository): display preview of HTML files
  webapps/ui/cockpit/client/scripts/config.js
  webapps/ui/cockpit/client/scripts/repository/resource/controllers/cam-cockpit-resource-details-ctrl.js
  webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-html-source.html
  webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-html-source.js
  webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-resource-content.html
  webapps/ui/cockpit/client/scripts/repository/resource/directives/cam-cockpit-resource-content.js
  webapps/ui/cockpit/client/scripts/repository/resource/main.js
  webapps/ui/cockpit/client/styles/pages/repository.less
  webapps/ui/common/scripts/services/cam-configuration.js
Labels: e2e

#1351 CAM-12944: feat(dist): add wildfly 22 support
  distro/wildfly/assembly/src/wildfly/standalone-full.xml
  distro/wildfly/assembly/src/wildfly/standalone.xml
  parent/pom.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml
  qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
Labels: no-build, pipelines, wildfly

#1340 fix(openapi): fix deployment and batch responses
  engine-rest/engine-rest-openapi/src/main/templates/paths/batch/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/batch/statistics/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/create/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/deployment/{id}/get.ftl
Labels: rest-api

#1360 chore(ci): add aurora 4.0 support
  .ci/config/matrices.yaml
Labels: no-build, pipelines, postgresql

#1362 chore(engine-rest): remove Jackson 1 test dependency
  engine-rest/engine-rest/pom.xml
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/TomcatServerBootstrap.java
Labels: default-build, pipelines, rest-api

#1336 feat(forms): add support for form-js
  webapps/package-lock.json
  webapps/package.json
  webapps/ui/common/styles/cam-webapps-common.less
  webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js
  webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form.html
  webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form.js
  webapps/ui/tasklist/client/scripts/form/index.js
  webapps/ui/tasklist/client/scripts/process/plugins/action/modals/cam-tasklist-process-start-modal.js
  webapps/ui/tasklist/client/scripts/task/plugins/detail/cam-tasklist-task-detail-form-plugin.js
Labels: e2e

#1366 feat(openapi): serve swagger ui in camunda run
  .gitignore
  Jenkinsfile
  distro/run/assembly/assembly.xml
  distro/run/assembly/pom.xml
  distro/run/assembly/resources/README.txt
  distro/run/assembly/resources/default.yml
  distro/run/assembly/resources/production.yml
  distro/run/assembly/resources/start.bat
  distro/run/assembly/resources/start.sh
  distro/run/core/pom.xml
  distro/run/modules/swaggerui/pom.xml
  distro/run/modules/swaggerui/src/main/java/org/camunda/bpm/run/swaggerui/CamundaSwaggerUIConfiguration.java
  distro/run/modules/swaggerui/src/main/resources/META-INF/spring.factories
  distro/run/modules/swaggerui/ui/package-lock.json
  distro/run/modules/swaggerui/ui/package.json
  distro/run/modules/swaggerui/ui/src/favicon.ico
  distro/run/modules/swaggerui/ui/src/index.html
  distro/run/modules/swaggerui/ui/src/index.js
  distro/run/modules/swaggerui/ui/src/style.css
  distro/run/modules/swaggerui/ui/tasks/license.js
  distro/run/modules/swaggerui/ui/webpack.config.js
  distro/run/modules/webapps/pom.xml
  distro/run/pom.xml
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ComponentAvailabilityIT.java
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ProductionConfigurationIT.java
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/swaggerui/SwaggerUIGetRequestIT.java
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java
  engine-rest/engine-rest-openapi/src/main/templates/main.ftl
Labels: pipelines, run

#1367 chore(ci): rename `standalone` label to `upstream`
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: no-build, pipelines

#1370 chore(ci): add npm to jdk stages
  .ci/config/stage-types.yaml
Labels: default-build, pipelines

#1369 chore(project): bump tomcat to latest version
  parent/pom.xml
Labels: pipelines, spring-boot, tomcat

#1372 fix(openapi): fix incorrect user example
  engine-rest/engine-rest-openapi/src/main/templates/paths/user/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/user/options.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/user/{id}/options.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/user/{id}/profile/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/user/{id}/profile/put.ftl
Labels: pipelines, rest-api

#1374 chore(ci): add versioning
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: default-build, e2e, pipelines

#1376 fix(xtac-starter): add static modifier to bfpp returning bean methods
  spring-boot-starter/starter-client/spring-boot/src/main/java/org/camunda/bpm/client/spring/boot/starter/impl/ClientAutoConfiguration.java
  spring-boot-starter/starter-client/spring/src/main/java/org/camunda/bpm/client/spring/impl/PostProcessorConfiguration.java
  spring-boot-starter/starter-client/spring/src/test/java/org/camunda/bpm/client/spring/client/configuration/PropertyPlaceholderConfiguration.java
Labels: pipelines, spring-boot

#1378 fix(xtac-starter): fix open state when closing a subscription
  spring-boot-starter/starter-client/spring/src/main/java/org/camunda/bpm/client/spring/impl/subscription/SpringTopicSubscriptionImpl.java
  spring-boot-starter/starter-client/spring/src/test/java/org/camunda/bpm/client/spring/subscription/AutoOpenFalseTest.java
Labels: no-build, spring-boot

#1375 CAM-13018: fix(engine): validate telemetry data
  engine/pom.xml
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/EngineUtilLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ParseUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ProductPropertiesUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/PropertiesUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/StringUtil.java
  engine/src/main/resources/org/camunda/bpm/engine/product-info.properties
  engine/src/test/java/org/camunda/bpm/engine/impl/util/PropertiesUtilTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/ProcessEngineDetailsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/db/SchemaLogEnsureSqlScriptTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/TestconfigProperties.java
Labels: default-build, pipelines

#1381 CAM-13018: fix(qa): adjust test installation id
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/functional/telemetry/TelemetryConnectPluginTest.java
Labels: all-as, pipelines

#1380 fix(rest): remove incorrect GET method in options response
  engine-rest/engine-rest-openapi/src/main/templates/paths/group/{id}/members/options.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/group-members/options.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/tenant/{id}/user-members/options.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/identity/impl/GroupMembersResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/identity/impl/TenantGroupMembersResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/identity/impl/TenantUserMembersResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/GroupRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TenantRestServiceInteractionTest.java
Labels: default-build, pipelines, rest-api

#1377 chore(engine): exclude flaky test on MariaDB and CRDB
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java
Labels: cockroachdb, mariadb, no-build, pipelines

#1387 fix(rest+engine): wrong error message when submitting null or empty escalationCode
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/bpmnEscalation/post.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/TaskService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleTaskEscalationCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
Labels: default-build, pipelines, rest-api

#1384 feat(engine): improve ext task handleFailure robustness
  engine/src/main/java/org/camunda/bpm/engine/ExternalTaskService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/externaltask/ExternalTaskLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.externalTaskWithNestedErrorEventDefinitionVariableExpression.bpmn20.xml
Labels: default-build

#1390 CAM-13235: update license book for 7.15
  distro/license-book/assembly.xml
  distro/license-book/pom.xml
  distro/license-book/src/main/resources/license-book.txt
Labels: pipelines
