Repository camunda/camunda-bpm-platform, pull requests merged in 2022-10, with the labels that each got.

#2035 CAMTEAM-269: update to github issues and explain details
  CONTRIBUTING.md
  README.md
Labels: ci:no-build

#2036 chore(ci): adjust staging folder for javadoc
  .ci/daily/Jenkinsfile
Labels: ci:no-build

#2836 CAMTEAM-272: add workflow that synchronizes label colors
  .github/actions/common/dist/index.js
  .github/actions/common/index.js
  .github/actions/common/src/synchronize-label-colors.js
  .github/actions/common/src/utils/collection-utils.js
  .github/actions/synchronize-label-colors/action.yml
  .github/actions/synchronize-label-colors/index.js
  .github/workflows/sync-label-colors.yml
Labels: ci:no-build

#2849 chore(readme): change the issue tracker
  README.md
Labels: ci:no-build

#2834 chore(webapp): update jquery-ui to 1.13.2
  webapps/package-lock.json
  webapps/package.json
Labels: ci:e2e

#1610 2571: make surefire pick up history cleanup test
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireCleanupJobsTest.java
Labels: ci:all-db

#2855 [2346] chore(typed-values): mark javax.activation as optional dependency
  typed-values/pom.xml
Labels: ci:all-as, ci:default-build, ci:no-build, ci:run, ci:spring-boot

#2023 fix(engine-spring): handle inactive scope for beans available in scripts
  engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringBeansResolverFactory.java
  spring-boot-starter/pom.xml
  spring-boot-starter/starter-qa/integration-test-request-scope/pom.xml
  spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/camunda/bpm/springboot/project/qa/simple/Application.java
  spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/camunda/bpm/springboot/project/qa/simple/RequestScopeIT.java
  spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/camunda/bpm/springboot/project/qa/simple/RequestScopedTestBean.java
  spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/camunda/bpm/springboot/project/qa/simple/TestBean.java
  spring-boot-starter/starter-qa/integration-test-request-scope/src/test/resources/application.properties
  spring-boot-starter/starter-qa/integration-test-request-scope/src/test/resources/logback-test.xml
  spring-boot-starter/starter-qa/pom.xml
Labels: ci:no-build, ci:spring-boot, ci:wildfly
