Repository camunda/camunda-bpm-platform, pull requests merged in 2022-02, with the labels that each got.

#1755 CAM-14306: NPE with a null-hostile List of group ids for authentica…
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/GroupAuthorizationTest.java
Labels: h2, authorizations

#1756 CAM-14310: avoid NPE when getting telemetry data without license
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/telemetry/InternalsDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TelemetryRestServiceTest.java
  engine/src/main/java/org/camunda/bpm/engine/telemetry/Internals.java
Labels: rest-api

#1754 CAM-14285: disable remote access to h2 console
  distro/h2-webapp/src/main/webapp/WEB-INF/web.xml
Labels: webapp-integration

#1767 CAM-14345: test/fix multi instance with inner async after
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
Labels: migration, h2

#1771 chore(engine): camunda-engine-dmn jdk17 support
  engine-dmn/engine/pom.xml
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/DmnEngineMetricCollectorTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/ExpressionCachingTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/ExpressionLanguageTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/FeelIntegrationTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/type/DataTypeTransformerIntegrationTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/type/DmnDataTypeTransformerTest.java
  engine-dmn/feel-scala/pom.xml
  engine-dmn/pom.xml
  parent/pom.xml
Labels: default-build, pipelines

#1781 CAM-14308: make extension properties available for all external tasks
  engine-plugins/connect-plugin/src/main/java/org/camunda/connect/plugin/impl/ConnectorParseListener.java
  engine-plugins/connect-plugin/src/test/java/org/camunda/connect/plugin/ConnectProcessEnginePluginTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.businessRuleTask.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.messageEndEvent.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.messageIntermediateEvent.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.sendTask.bpmn20.xml
Labels: default-build

#1793 chore(engine): fix system permission bug
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ResourceTypeUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/PermissionsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/identity/AuthorizationServiceTest.java
Labels: default-build

#1792 chore(engine): camunda-engine jdk17 support
  engine/pom.xml
  engine/src/test/java/org/camunda/bpm/application/impl/context/ProcessApplicationContextTest.java
  engine/src/test/java/org/camunda/bpm/engine/impl/cfg/JtaTransactionInterceptorTest.java
  engine/src/test/java/org/camunda/bpm/engine/impl/incident/CompositeIncidentHandlerTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/GroupAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/cfg/AuthorizationCheckRevokesCfgTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/repository/RepositoryServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/AcquireJobCmdUnitTest.java
Labels: default-build, pipelines

#1794 fix(cockpit): fix checkbox in job retry dialog.
  webapps/ui/cockpit/plugins/base/app/views/processInstance/job-retry-bulk-dialog.html
  webapps/ui/cockpit/plugins/base/app/views/processInstance/jobRetryBulkDialog.js
Labels: e2e

#1778 chore(test): improve ManagementServiceGetTelemetryDataTest
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/util/WebApplicationUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/BootstrapEngineCommand.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ManagementServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteLicenseKeyCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetLicenseKeyCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/TelemetryRegistry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/LicenseKeyDataImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/LicenseKeyUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceGetTelemetryDataTest.java
  spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/telemetry/CamundaApplicationServerConfigurator.java
Labels: default-build

#1779 CAMTEAM-223: commit msg best practice
  CONTRIBUTING.md
Labels: no-build

#1804 chore(engine): update mockito version in qa db upgrade
  qa/test-db-upgrade/pom.xml
Labels: all-db, default-build, pipelines

#1805 chore(spring): downgrade spring framework version
  parent/pom.xml
Labels: all-as

#1760 fix(engine/tasklist): readonly boolean field cannot be submitted
  engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/AbstractRenderFormDelegate.java
  engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/FormPropertyAdapter.java
  engine/src/main/java/org/camunda/bpm/engine/impl/form/engine/HtmlFormEngine.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/HtmlFormEngineTest.testLegacyFormPropertySupportReadOnly.html
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/HtmlFormEngineTest.testRenderDateField.html
  webapps/camunda-bpm-sdk-js/lib/forms/controls/input-field-handler.js
Labels: default-build, e2e

#1745 CAM-14293: feat(run): add shutdown scripts
  distro/run/assembly/assembly.xml
  distro/run/assembly/resources/run.bat
  distro/run/assembly/resources/run.sh
  distro/run/assembly/resources/shutdown.bat
  distro/run/assembly/resources/shutdown.sh
  distro/run/assembly/resources/start.bat
  distro/run/assembly/resources/start.sh
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java
Labels: run

#1763 fix(sdk-js): avoid making embedded form fields dirty
  webapps/camunda-bpm-sdk-js/lib/angularjs/forms/index.js
Labels: e2e

#1764 fix(webapps): avoid showing an error for `GET /camunda-welcome`
  webapps/camunda-commons-ui/lib/pages/index.js
Labels: e2e

#1808 feat(admin): configure SYSTEM permissions for users
  webapps/ui/admin/client/scripts/pages/authorizations.js
Labels: e2e

#1799 chore(build): update postgres driver version to 42.3.3
  database/pom.xml
Labels: postgresql

#1816 CAM-11911: chore(run): add camunda-welcome to run
  distro/run/assembly/resources/start.bat
  distro/run/assembly/resources/start.sh
  distro/webjar/pom.xml
  spring-boot-starter/starter/src/main/java/org/camunda/bpm/spring/boot/starter/property/WebappProperty.java
Labels: all-as, run, spring-boot
