Repository camunda/camunda-bpm-platform, pull requests merged in 2022-07, with the labels that each got.

#1946 chore(openapi): remove task worker metrics from interval
  engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/get.ftl
Labels: no-build

#1940 fix(engine): make Liquibase work from JAR
  engine/pom.xml
  engine/src/main/resources/org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml
  spring-boot-starter/starter-qa/integration-test-liquibase/pom.xml
  spring-boot-starter/starter-qa/integration-test-liquibase/src/test/java/org/camunda/bpm/springboot/project/qa/liquibase/Application.java
  spring-boot-starter/starter-qa/integration-test-liquibase/src/test/java/org/camunda/bpm/springboot/project/qa/liquibase/LiquibaseApplicationIT.java
  spring-boot-starter/starter-qa/integration-test-liquibase/src/test/resources/application.properties
  spring-boot-starter/starter-qa/integration-test-liquibase/src/test/resources/logback-test.xml
  spring-boot-starter/starter-qa/pom.xml
Labels: all-db, migration, spring-boot

#1947 chore(engine): stabilize JobExecutorMetricsTest on CRDB
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/JobExecutorMetricsTest.java
Labels: cockroachdb

#1950 chore(engine): stabilize SqlScriptTest
  distro/sql-script/src/test/java/org/camunda/bpm/sql/test/SqlScriptTest.java
Labels: all-db

#1949 chore(engine): stabilize HistoricProcessInstanceTest
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
Labels: mysql

#1943 feat(engine/rest/openapi): provide exception error codes
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ExceptionDto.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/ExceptionDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/exception/ExceptionHandlerHelper.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ConditionRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/DecisionDefinitionRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExceptionHandlerTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/MessageRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessDefinitionRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/SignalRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskVariableRestResourceInteractionTest.java
  engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringTransactionInterceptor.java
  engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/SpringTransactionsProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/ProcessEngineException.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/JtaProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/StandaloneProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CommandLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/BatchDbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/SimpleDbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/el/UelExpressionCondition.java
  engine/src/main/java/org/camunda/bpm/engine/impl/errorcode/BuiltinExceptionCode.java
  engine/src/main/java/org/camunda/bpm/engine/impl/errorcode/ExceptionCodeProvider.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/CommandInvocationContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ExceptionCodeInterceptor.java
  engine/src/main/java/org/camunda/bpm/engine/impl/scripting/ScriptCondition.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/repository/DeleteProcessDefinitionTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/repository/RepositoryServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/callactivity/CallActivityDelegateMappingTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/cockroachdb/CockroachDbExclusiveLockDisabledTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/BuiltinExceptionCodeForeignKeyConstraintViolationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/CompetingCompleteTaskSetVariableTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/CompetingMessageCorrelationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentDeploymentTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentHistoryCleanupTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentHistoryLevelTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentInstallationIdInitializationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentTelemetryConfigurationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/DeadlockTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/ExceptionBuiltinCodesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/FailingJavaDelegateWithCustomException.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/FailingJavaDelegateWithErrorCode.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/FailingJavaDelegateWithOleAndErrorCode.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/conf/BuiltinExceptionCodeProviderDisabledWithCustomProviderTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/conf/CustomErrorCodeProviderTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/conf/ExceptionCodeDisabledTest.java
Labels: no-build, default-build

#1952 fix(engine): skip writing log when code is already fallback code
  engine/src/main/java/org/camunda/bpm/engine/impl/interceptor/ExceptionCodeInterceptor.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/ExceptionBuiltinCodesTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/conf/CustomErrorCodeProviderTest.java
Labels: h2

#1948 chore(engine): stabilize SequentialJobAcquisitionTest
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/SequentialJobAcquisitionTest.java
Labels: all-db, no-build

#1942 CAM-14423: Cockpit Decision View shows date variables as invalid when they are not
  webapps/ui/cockpit/plugins/decisionList/app/views/decisionInstance/inputTable.js
Labels: e2e

#1941 CAM-14696: Tasklist Plugin: method render does not get called on changing human task
  webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.html
  webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.js
Labels: e2e

#1957 chore(tasklist): fix eslint error breaking assembly build
  webapps/ui/cockpit/plugins/decisionList/app/views/decisionInstance/inputTable.js
  webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.js
Labels: e2e

#1955 CAM-14489: update h2 to 2.1.214
  database/pom.xml
Labels: migration, all-as, rolling-update, h2

#1962 CAM-14456: avoid propagation of skipIoMappings after cancellation
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationDeleteCascadeFireActivityEnd.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/BoundaryEventInputOutputTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/gateway/EventBasedGatewayInputOutputTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/iomapping/VariableLogDelegate.java
Labels: migration

#1944 feat(batch): show username for in progress batches
  webapps/ui/cockpit/client/scripts/batches/components/batch.js
  webapps/ui/cockpit/client/scripts/batches/controllers/view-ctrl.js
  webapps/ui/cockpit/client/scripts/batches/templates/cam-cockpit-batch-view.html
  webapps/ui/common/styles/app-splash.less
Labels: e2e

#1964 fix(engine/engine-rest): adjust task lastUpdated API
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/list/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/list/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/singleResult/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/filter/{id}/singleResult/post.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/task/TaskQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryProperty.java
  engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
Labels: rest-api

#1969 fix(engine): handle foreign key constraint violations on db2
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/BuiltinExceptionCodeForeignKeyConstraintViolationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/ExceptionBuiltinCodesTest.java
Labels: db2
