Repository camunda/camunda-bpm-platform, pull requests merged in 2022-11, with the labels that each got.

#2865 chore(openapi): add missing endpoints
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/TaskCountByCandidateGroupResultDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/report/candidate-group-count/get.ftl
Labels: ci:rest-api

#2852 fix(engine): fix bean method resolution with null param values
  engine/src/main/java/org/camunda/bpm/engine/impl/javax/el/BeanELResolver.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.java
Labels: ci:h2, ci:wildfly

#2861 chore(webapp): update moment to 2.29.4
  webapps/package-lock.json
  webapps/package.json
Labels: ci:e2e

#2884 CAMTEAM-276: disable creating blank issues
  .github/ISSUE_TEMPLATE/config.yml
Labels: ci:no-build

#2847 [#2876]: Add CI to generate REST Docs from Open API definition
  .ci/daily/Jenkinsfile
  engine-rest/docs/package-lock.json
  engine-rest/docs/package.json
  engine-rest/docs/pom.xml
  engine-rest/docs/template.hbs
  engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/diagram/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/key/{key}/tenant-id/{tenant-id}/diagram/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/decision-requirements-definition/{id}/diagram/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/execution/{id}/localVariables/{varName}/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/variable-instance/{id}/data/get.ftl
  engine-rest/pom.xml
Labels: ci:default-build, ci:no-build

#2885 [#2824]: fix(webapps): make adding missing license headers work on windows
  webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js
Labels: ci:e2e

#2860 [2856] chore(ci): switch to Maven 3.8
  .ci/daily/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: ci:h2, ci:jdk, ci:mysql, ci:no-build

#2901 chore(translations): sort en translations alphabetically
  webapps/package-lock.json
  webapps/ui/admin/client/en.json
  webapps/ui/cockpit/client/en.json
  webapps/ui/tasklist/client/en.json
  webapps/ui/welcome/client/en.json
Labels: ci:no-build

#2951 CAMTEAM-280: import correct secret from vault
  .github/workflows/extract-issue-links.yml
Labels: ci:no-build

#2953 chore(ci): exclude rest docs from wls-compatibility
  Jenkinsfile
Labels: ci:rest-api

#2022 chore(engine): add telemetry data collection time frame info
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/telemetry/TelemetryInternalsDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/telemetry/data/get.ftl
  engine-rest/engine-rest-openapi/src/test/java/org/camunda/bpm/engine/rest/openapi/client/ProcessInstanceTest.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/telemetry/InternalsDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TelemetryRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/TelemetryConfigureCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/dto/InternalsImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/telemetry/reporter/TelemetrySendingTask.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ClockUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/JsonUtil.java
  engine/src/main/java/org/camunda/bpm/engine/telemetry/Internals.java
  engine/src/test/java/org/camunda/bpm/engine/impl/util/ClockUtilTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceGetTelemetryDataTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/telemetry/TelemetryReporterTest.java
  parent/pom.xml
  qa/test-old-engine/pom.xml
Labels: ci:h2, ci:mysql, ci:rest-api, bot:java-dependency-tree

#2963 chore(ci): add PostgreSQL 15
  .ci/config/matrices.yaml
Labels: ci:no-build, ci:postgresql

#2964 [2818] chore(deps): bump `feel-scala` engine to version `1.15.3`
  pom.xml
Labels: ci:h2, ci:tomcat, ci:wildfly, bot:java-dependency-tree

#2977 test(karma): fix permanently
  webapps/camunda-commons-ui/vendor/dataDepend.js
  webapps/camunda-commons-ui/vendor/jquery.js
Labels: ci:e2e
