Repository camunda/camunda-bpm-platform, pull requests merged in 2022-06, with the labels that each got.

#1920 fix(engine): fix problematic exception handling for Java 17
  engine/src/main/java/org/camunda/bpm/engine/impl/javax/el/BeanELResolver.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.java
Labels: jdk

#1919 feat(engine): introduce lastUpdated API for tasks
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/TaskService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskQueryProperty.java
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/camunda/bpm/engine/impl/json/JsonTaskQueryConverter.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
  engine/src/main/java/org/camunda/bpm/engine/task/Task.java
  engine/src/main/java/org/camunda/bpm/engine/task/TaskQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.cockroachdb.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.db2.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.h2.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mariadb.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mssql.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mysql.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.oracle.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.postgres.drop.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/cockroachdb_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Task.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/encoding/ProcessEngineCharacterEncodingTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterTaskQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/StandaloneTaskTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskLastUpdatedTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryExpressionTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/task/TaskDecoratorTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/form/DeployedCamundaFormSingleTaskProcess.bpmn20.xml
  qa/test-old-engine/pom.xml
Labels: mysql

#1931 chore(ci): rename Aurora PostgreSQL stages
  .ci/config/matrices.yaml
Labels: postgresql
