Repository camunda/camunda-bpm-platform, pull requests merged in 2022-04, with the labels that each got.

#1869 chore(parent): bump Spring versions
  parent/pom.xml
Labels: migration, rest-api, webapp-integration, default-build, run, spring-boot, java-dependency-tree, webapp-unit

#1870 CAM-14434: enable rolling-update and old-engine tests for h2
  qa/test-db-rolling-update/create-new-engine/pom.xml
  qa/test-db-rolling-update/create-old-engine/pom.xml
  qa/test-db-rolling-update/test-old-engine/pom.xml
  qa/test-old-engine/pom.xml
Labels: rolling-update, h2, default-build

#1877 CAM-14439: fix(run): run.sh script works with whitespaces
  distro/run/assembly/resources/run.sh
Labels: run

#1876 CAM-14507: display copy option when the mouse is on the JSON telemetry data
  webapps/camunda-commons-ui/lib/widgets/debug/cam-widget-debug.html
Labels: e2e

#1879 CAM-14497: fix(engine): add missing and sql operator
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricDetailQueryTest.java
Labels: rest-api, default-build

#1842 chore(webapps): use angularjs from xlts.dev
  Jenkinsfile
  webapps/README.md
  webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js
  webapps/camunda-commons-ui/index.js
  webapps/package-lock.json
  webapps/package.json
  webapps/pom.xml
  webapps/scripts/xlts.js
Labels: no-build, e2e

#1857 chore(engine-dmn): bump feel engine to version 1.14.2
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/feel/BreakingScalaFeelBehaviorTest.java
  engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.inputVariableName.dmn
  engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.overrideInputVariableName.dmn
  engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.variableContext.dmn
  engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/el/ExpressionEvaluationTest.variableContextWithInputVariable.dmn
  pom.xml
Labels: h2

#1883 chore(database): bump MySQL connector to 8.0.28
  database/pom.xml
Labels: mysql

#1886 CAM-14536: fix(engine): correct flag in bpmn deployment tests
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/deployment/BpmnDeploymentTest.java
Labels: default-build

#1889 CAMTEAM-235: chore(ci): disable docker gha trigger stage
  .ci/daily/Jenkinsfile
Labels: no-build

#1856 chore(ci): remove unsupported environments
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  Jenkinsfile
  database/pom.xml
  engine/pom.xml
  engine/src/test/java/org/camunda/bpm/engine/test/persistence/DatabaseFlushTest.java
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/util/DeploymentHelper.java
  qa/test-db-upgrade/pom.xml
  qa/test-old-engine/pom.xml
Labels: all-db, websphere

#1885 chore(database): bump Resteasy to 3.15.3.Final
  parent/pom.xml
Labels: rest-api, all-as

#1884 chore(example): consolidate intro page of invoice example
  distro/camunda-welcome/index.html
  distro/camunda-welcome/invoice.html
  examples/invoice/src/main/webapp/assets/css/app.css
  examples/invoice/src/main/webapp/assets/css/common.css
  examples/invoice/src/main/webapp/assets/css/intro.css
  examples/invoice/src/main/webapp/assets/css/styles.min.css
  examples/invoice/src/main/webapp/assets/fonts/IBMPlexSans-Bold.otf
  examples/invoice/src/main/webapp/assets/fonts/IBMPlexSans-BoldItalic.otf
  examples/invoice/src/main/webapp/assets/fonts/IBMPlexSans-Italic.otf
  examples/invoice/src/main/webapp/assets/fonts/IBMPlexSans-Regular.otf
  examples/invoice/src/main/webapp/assets/img/favicon.ico
  examples/invoice/src/main/webapp/assets/vendor/bootstrap/css/bootstrap-responsive.min.css
  examples/invoice/src/main/webapp/assets/vendor/bootstrap/css/bootstrap.min.css
  examples/invoice/src/main/webapp/assets/vendor/bootstrap/img/glyphicons-halflings-white.png
  examples/invoice/src/main/webapp/assets/vendor/bootstrap/img/glyphicons-halflings.png
  examples/invoice/src/main/webapp/assets/vendor/bootstrap/js/bootstrap.min.js
  examples/invoice/src/main/webapp/assets/vendor/jquery/jquery.min.js
  examples/invoice/src/main/webapp/index.html
Labels: no-build

#1859 chore(deps): bump logback to version 1.2.11
  parent/pom.xml
  pom.xml
Labels: all-as, h2, spring-boot

#1895 CAM-14149: display removal time for process and decision instances
  webapps/ui/cockpit/client/scripts/pages/decision-instance.html
Labels: e2e

#1896 chore(deps): bump moment version
  webapps/package-lock.json
  webapps/package.json
Labels: e2e

#1897 chore(engine): allow querying deployments w/o name
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Deployment.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Resource.xml
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/deployment/BpmnDeploymentTest.java
Labels: all-db

#1892 chore(*): bump Jackson versions
  clients/java/client/pom.xml
  database/pom.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-annotations/2.13.2.20220328/module.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-core/2.13.2.20220328/module.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/2.13.2.20220328/module.xml
  engine-rest/engine-rest-openapi-generator/pom.xml
  engine-rest/engine-rest/pom.xml
  engine-rest/pom.xml
  parent/pom.xml
  pom.xml
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/resources-wildfly/jboss-deployment-structure-spin-json.xml
Labels: rest-api, wildfly, jbosseap, default-build
