Repository camunda/camunda-bpm-platform, pull requests merged in 2022-09, with the labels that each got.

#1991 CAM-14611: chore(parent): bump spring and spring-boot versions
  parent/pom.xml
Labels: ci:all-as, ci:default-build, ci:run, ci:spring-boot, bot:java-dependency-tree

#2008 chore(webapps): add license header to `lib/globalize.js`
  webapps/grunt/tasks/license-header.js
Labels: ci:no-build

#1988 feat(batch): add search options for runtime batches
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/batch.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/batch/BatchStatisticsQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/BatchRestServiceStatisticsTest.java
  engine/src/main/java/org/camunda/bpm/engine/batch/BatchStatisticsQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/BatchStatisticsQueryImpl.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Statistics.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/BatchStatisticsQueryTest.java
  webapps/ui/cockpit/client/en.json
  webapps/ui/cockpit/client/scripts/batches/components/batch.js
  webapps/ui/cockpit/client/scripts/batches/config/batch-search-config.json
  webapps/ui/cockpit/client/scripts/batches/controllers/view-ctrl.js
  webapps/ui/cockpit/client/scripts/batches/templates/cam-cockpit-batch-view.html
Labels: ci:e2e, ci:all-db

#2020 chore(project): move the pr-labels files to separate dir
  .github/helpers/README.md
  .github/helpers/pr-labels.yml
Labels: ci:no-build

#1977 fix(webapps): determine plugin path without traversal
  webapps/ui/admin/client/scripts/camunda-admin-bootstrap.js
  webapps/ui/cockpit/client/scripts/camunda-cockpit-bootstrap.js
  webapps/ui/common/scripts/services/plugins/loadPlugins.js
  webapps/ui/tasklist/client/scripts/camunda-tasklist-bootstrap.js
  webapps/ui/welcome/client/scripts/camunda-welcome-bootstrap.js
Labels: ci:e2e

#2007 chore(webapps): bump xlts.dev angularjs
  webapps/package.json
Labels: ci:e2e, ci:no-build

#2004 chore(h2): remove camunda-h2-webapp
  Jenkinsfile
  distro/h2-webapp/pom.xml
  distro/h2-webapp/src/main/webapp/WEB-INF/jboss-web.xml
  distro/h2-webapp/src/main/webapp/WEB-INF/web.xml
  distro/tomcat/distro/assembly.xml
  distro/tomcat/distro/pom.xml
  distro/wildfly/distro/assembly.xml
  distro/wildfly/distro/pom.xml
  pom.xml
Labels: ci:h2, ci:tomcat, ci:wildfly

#2009 fix(engine): return copied list in #getIdentityLinksForTask()
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/GetIdentityLinksForTaskCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskIdentityLinksTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/tasklistener/util/GetIdentityLinksTaskListener.java
Labels: ci:default-build, ci:migration, ci:rolling-update

#2011 chore(engine-rest): consolidate `engine-rest` artifacts
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  bom/pom.xml
  distro/run/modules/pom.xml
  engine-rest/assembly/assembly-war-tomcat.xml
  engine-rest/assembly/assembly-war-was9.xml
  engine-rest/assembly/assembly-war-wildfly.xml
  engine-rest/assembly/assembly-war-wls.xml
  engine-rest/assembly/pom.xml
  engine-rest/engine-rest-jaxrs2/pom.xml
  engine-rest/engine-rest-jaxrs2/src/main/java/org/camunda/bpm/engine/rest/FetchAndLockRestService.java
  engine-rest/engine-rest-jaxrs2/src/main/java/org/camunda/bpm/engine/rest/impl/CamundaRestResources.java
  engine-rest/engine-rest-jaxrs2/src/main/java/org/camunda/bpm/engine/rest/impl/FetchAndLockRestServiceImpl.java
  engine-rest/engine-rest-jaxrs2/src/main/java/org/camunda/bpm/engine/rest/impl/JaxRsTwoDefaultProcessEngineRestServiceImpl.java
  engine-rest/engine-rest-jaxrs2/src/main/java/org/camunda/bpm/engine/rest/impl/JaxRsTwoNamedProcessEngineRestServiceImpl.java
  engine-rest/engine-rest-jaxrs2/src/test/java-jersey2/org/camunda/bpm/engine/rest/util/container/JerseyServerBootstrap.java
  engine-rest/engine-rest-jaxrs2/src/test/java-jersey2/org/camunda/bpm/engine/rest/util/container/JerseySpecifics.java
  engine-rest/engine-rest-jaxrs2/src/test/java-resteasy3/org/camunda/bpm/engine/rest/util/container/ResteasyServerBootstrap.java
  engine-rest/engine-rest-jaxrs2/src/test/java-resteasy3/org/camunda/bpm/engine/rest/util/container/ResteasySpecifics.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/AbstractRestServiceTest.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/helper/MockExternalTaskBuilder.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/helper/MockGroupBuilder.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/helper/MockUserBuilder.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/spi/impl/MockedProcessEngineProvider.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/util/DateTimeUtils.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/util/container/ContainerSpecifics.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/util/container/EmbeddedServerBootstrap.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/util/container/JaxrsApplication.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/util/container/ServerBootstrapException.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/util/container/TestContainerRule.java
  engine-rest/engine-rest-jaxrs2/src/test/java/org/camunda/bpm/engine/rest/util/container/TestRuleFactory.java
  engine-rest/engine-rest-jaxrs2/src/test/resources-jersey2/META-INF/services/org.camunda.bpm.engine.rest.util.container.ContainerSpecifics
  engine-rest/engine-rest-jaxrs2/src/test/resources-resteasy3/META-INF/services/org.camunda.bpm.engine.rest.util.container.ContainerSpecifics
  engine-rest/engine-rest-jaxrs2/src/test/resources/META-INF/services/org.camunda.bpm.engine.rest.spi.ProcessEngineProvider
  engine-rest/engine-rest-jaxrs2/src/test/resources/testconfig.properties
  engine-rest/engine-rest/pom.xml
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/ExternalTaskRestService.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/FetchExternalTasksExtendedDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ExternalTaskRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/FetchAndLockContextListener.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/FetchAndLockHandlerImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/FetchAndLockRequest.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/FetchAndLockResult.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/spi/FetchAndLockHandler.java
  engine-rest/engine-rest/src/main/resources/META-INF/services/org.camunda.bpm.engine.rest.spi.FetchAndLockHandler
  engine-rest/engine-rest/src/test/java-resteasy/org/camunda/bpm/engine/rest/ResteasyTaskRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/impl/FetchAndLockHandlerTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/impl/FetchAndLockRestServiceInteractionTest.java
  engine-rest/pom.xml
  spring-boot-starter/starter-rest/pom.xml
  spring-boot-starter/starter-webapp-core/pom.xml
Labels: ci:h2, ci:no-build

#2002 chore(ci): remove environments no longer supported
  .ci/config/matrices.yaml
  Jenkinsfile
Labels: ci:no-build

#2003 chore(project): remove retired envs
  database/pom.xml
  engine-rest/engine-rest/pom.xml
Labels: ci:all-as, ci:all-db, ci:no-build, ci:rest-api, bot:java-dependency-tree

#2025 feat(tasklist): add support for dynamic camunda forms
  webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js
  webapps/package-lock.json
  webapps/package.json
  webapps/ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js
Labels: ci:e2e

#1982 feat(cockpit): improve safety of the migration operation
  webapps/camunda-commons-ui/lib/widgets/selection-type/cam-widget-selection-type.html
  webapps/camunda-commons-ui/lib/widgets/selection-type/cam-widget-selection-type.js
  webapps/camunda-commons-ui/lib/widgets/selection-type/cam-widget-selection-type.less
  webapps/ui/cockpit/client/en.json
  webapps/ui/cockpit/client/styles/styles.less
Labels: ci:e2e, ci:no-build

#2026 test(engine): exclude concurrency signal event test on cockroachdb
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventConcurrencyTest.java
Labels: ci:cockroachdb

#1981 feat(cockpit): improve safety of the restart and modify operations
  webapps/ui/cockpit/client/en.json
Labels: ci:e2e, ci:no-build

#2021 fix(engine): skip FailedJobListener for timed out & already re-acquired jobs
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/FailedJobListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobExecutorLogger.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrentJobExecutorTest.java
Labels: ci:all-db
