Repository camunda/camunda-bpm-platform, pull requests merged in 2022-08, with the labels that each got.

#1966 CAM-14702: Implement a new selection type UI
  webapps/camunda-commons-ui/lib/widgets/index.js
  webapps/camunda-commons-ui/lib/widgets/selection-type/cam-widget-selection-type.html
  webapps/camunda-commons-ui/lib/widgets/selection-type/cam-widget-selection-type.js
Labels: no-build

#1959 feat(batch): delete historic batch entity feature
  webapps/ui/cockpit/client/scripts/batches/components/batch.js
  webapps/ui/cockpit/client/scripts/batches/components/delete.js
  webapps/ui/cockpit/client/scripts/batches/controllers/modal-ctrl.js
  webapps/ui/cockpit/client/scripts/batches/controllers/view-ctrl.js
  webapps/ui/cockpit/client/scripts/batches/templates/cam-cockpit-batch-view.html
  webapps/ui/cockpit/client/scripts/batches/templates/delete-modal.html
Labels: e2e

#1945 feat(batch): add & show start time for batches
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/batch/BatchDto.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/batch/BatchDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/batch/BatchStatisticsDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/batch/BatchStatisticsQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/BatchRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/BatchRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/BatchRestServiceStatisticsTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockBatchBuilder.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockBatchStatisticsBuilder.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine/src/main/java/org/camunda/bpm/engine/batch/Batch.java
  engine/src/main/java/org/camunda/bpm/engine/batch/BatchStatisticsQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/BatchQueryProperty.java
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/BatchEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/BatchStatisticsQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/builder/BatchBuilder.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.cockroachdb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/cockroachdb_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.17_to_7.18.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Batch.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Statistics.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/BatchQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/BatchStatisticsQueryTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/TestOrderingUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/batch/BatchMigrationHistoryTest.java
  webapps/ui/cockpit/client/scripts/batches/controllers/view-ctrl.js
  webapps/ui/cockpit/client/scripts/batches/templates/cam-cockpit-batch-view.html
Labels: all-db, migration

#1974 fix(webapps): update commit hash of the translations repo
  webapps/package-lock.json
Labels: e2e

#1976 fix(ci): change xlts.dev secrets vault path
  Jenkinsfile
Labels: default-build, e2e

#1978 chore(engine): remove millisecond precision in batch test for MySQL
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/BatchQueryTest.java
Labels: mysql

#1970 test(engine): fix flaky deadlock test on sql server
  engine/src/test/java/org/camunda/bpm/engine/test/errorcode/DeadlockTest.java
Labels: all-db

#1983 feat(db): add postgres 14 support
  .ci/config/matrices.yaml
Labels: postgresql

#1989 fix(webapps): ensure third-party license headers are present
  webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js
  webapps/camunda-commons-ui/index.js
  webapps/camunda-commons-ui/lib/directives/index.js
  webapps/camunda-commons-ui/lib/index.js
  webapps/camunda-commons-ui/lib/widgets/cam-share-link/test/cam-share-link.src.js
  webapps/camunda-commons-ui/lib/widgets/chart-line/test/cam-widget-chart-line.src.js
  webapps/camunda-commons-ui/lib/widgets/clipboard/test/cam-widget-clipboard.src.js
  webapps/camunda-commons-ui/lib/widgets/header/test/cam-widget-header.src.js
  webapps/camunda-commons-ui/lib/widgets/index.js
  webapps/camunda-commons-ui/lib/widgets/loader/test/cam-widget-loader.src.js
  webapps/camunda-commons-ui/lib/widgets/variable/test/cam-widget-variable.src.js
  webapps/camunda-commons-ui/lib/widgets/variables-table/test/cam-widget-variables-table.src.js
  webapps/camunda-commons-ui/vendor/ui-bootstrap-tpls-2.5.0-camunda.js
  webapps/grunt/tasks/terser.js
  webapps/package-lock.json
  webapps/package.json
  webapps/ui/tasklist/client/scripts/task/index.js
Labels: e2e

#1987 CAM-14804: In Tasklist and Cockpit, update to Google Chrome v. 104 causes columns to change size
  webapps/ui/common/styles/_three-cols-layout.less
Labels: e2e

#1984 CAM-14506: don't make variable concurrent on single execution
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/VariableInstanceConcurrentLocalInitializer.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstantiationAtActivitiesTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/concurrentExecutionVariable.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/concurrentExecutionVariableWithSubprocess.bpmn20.xml
Labels: migration, rolling-update, h2

#1992 fix(engine): make deadlock check null safe
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java
Labels: h2, no-build

#1985 CAM-14756: feat(qa): adjust IT tests to better support was liberty
  database/pom.xml
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/AbstractWebappUiIntegrationTest.java
Labels: webapp-integration

#1934 fix(engine): find method by resolving types from param vals in juel
  engine/src/main/java/org/camunda/bpm/engine/impl/javax/el/BeanELResolver.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/el/ExpressionManagerTest.java
Labels: all-as, h2

#1965 chore(engine/springboot): fix historic task update events for related entities
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TaskEntity.java
  spring-boot-starter/starter/src/test/java/org/camunda/bpm/spring/boot/starter/CamundaEventingIT.java
Labels: spring-boot

#1901 chore(webapps): move english translations into main repository
  webapps/grunt/config/localescompile.js
  webapps/package-lock.json
  webapps/package.json
  webapps/ui/admin/client/en.json
  webapps/ui/cockpit/client/en.json
  webapps/ui/tasklist/client/en.json
  webapps/ui/tasklist/grunt/config/watch.js
  webapps/ui/welcome/client/en.json
Labels: e2e

#1998 CAM-14838: define PR labels from yml file
  .github/README.md
  .github/pr-labels.yml
Labels: no-build

#1999 CAM-14741: revert(cdi): don't test against weld 2.4
  engine-cdi/compatibility-test-weld2/pom.xml
  engine-cdi/pom.xml
Labels: default-build, jdk
