Repository camunda/camunda-bpm-platform, pull requests merged in 2023-10, with the labels that each got.

#3783 chore(ci): introduce quarkus tests profile
  Jenkinsfile
  quarkus-extension/pom.xml
Labels: ci:h2, ci:no-build

#3775 test(engine-rest): Add PersistenceConnection Test
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/NonPersistenceConnectionExceptionLoggingTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/PersistenceConnectionExceptionLoggingTest.java
Labels: ci:default-build

#3822 fix(qa): fix qa setups after 7.20 release
  qa/test-db-instance-migration/test-fixture-721/pom.xml
  qa/test-db-rolling-update/create-old-engine/src/main/resources/camunda.auth.cfg.xml
  qa/test-db-rolling-update/create-old-engine/src/main/resources/camunda.cfg.xml
  qa/test-old-engine/pom.xml
Labels: ci:migration, ci:mysql, ci:rolling-update

#3811 chore(deps): update tomcat to 9.0.80 and 10.1.13 (run)
  parent/pom.xml
Labels: ci:run, ci:tomcat, bot:java-dependency-tree

#3806 fix(engine): Fix historyCleanupDefaultNumberOfRetries
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupHelper.java
Labels: ci:all-as

#3782 fix(engine): add missing property check for historic incident
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricIncident.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricIncidentQueryTest.java
Labels: ci:all-db

#3825 chore(openapi): fix pagination properties in various endpoints
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricExternalTaskLogQueryDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/batch/cleanable-batch-report/count/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/incident/count/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/incident/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/variable-instance/count/get.ftl
Labels: ci:rest-api

#3888 chore(deps): update tomcat to 9.0.82 (run 10.0.15); spring boot 3.1.5
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigAllowCredentialsTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigAllowedHeadersTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledAllowedOriginConfiguredTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationEnabledWildcardTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationExposedHeadersTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsConfigurationPreflightMaxAgeTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/cors/CorsWithChangedContextPathTest.java
  parent/pom.xml
Labels: ci:run, ci:tomcat, bot:java-dependency-tree, bot:java-dependency-check

#3882 chore(ci): add support for postgres 16
  .ci/config/matrices.yaml
Labels: ci:postgresql

#3872 chore(ci): add maven and nexus jobs to daily pipeline
  .ci/daily/Jenkinsfile
Labels: ci:no-build

#3892 chore(rest/docs): make the build OS independent
  engine-rest/docs/package.json
Labels: ci:rest-api
