Repository camunda/camunda-bpm-platform, pull requests merged in 2023-04, with the labels that each got.

#3311 style(settings): Adjust IntelliJ formatter.xml to Make Static Imports Precede Imports
  settings/intellij-idea/formatter.xml
Labels: ci:no-build

#3354 fix(rest): Remove additionalProperties from Unnecessary Responses
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/telemetry/TelemetryDataDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/telemetry/TelemetryInternalsDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/telemetry/TelemetryProductDto.ftl
Labels: ci:rest-api

#3306 chore(project): update Spin to 1.19.1
  distro/jboss/webapp-standalone/pom.xml
  distro/tomcat/webapp-standalone/pom.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/net/minidev/accessors-smart/main/module.xml
  distro/wildfly26/modules/pom.xml
  distro/wildfly26/modules/src/main/modules/net/minidev/accessors-smart/main/module.xml
  pom.xml
Labels: ci:all-as, ci:default-build

#3356 chore(parent): Bump resteasy version to 3.15.6
  parent/pom.xml
Labels: ci:rest-api

#3109 fix(engine): improve speed of deploying message start event models
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java
Labels: ci:h2

#3361 fix(engine): support OLE on PostgreSQL for failed statement
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/EnginePersistenceLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/DbEntityManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/entitymanager/operation/DbOperation.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java
  engine/src/main/java/org/camunda/bpm/engine/impl/errorcode/ExceptionCodeProvider.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/DatabaseUtil.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/ExceptionUtil.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/AbstractCompetingTransactionsOptimisticLockingTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/BuiltinExceptionCodeForeignKeyConstraintViolationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/CompetingTransactionsOptimisticLockingTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/CompetingTransactionsOptimisticLockingTestWithoutBatchProcessing.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/partitioning/SkipHistoryOptimisticLockingExceptionsDisabledTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/concurrency/AbstractCompetingTransactionsOptimisticLockingTest.shouldDetectConcurrentDeletionOfExecutionForTaskInsert.bpmn20.xml
Labels: ci:cockroachdb, ci:mysql, ci:postgresql

#3380 chore(github): uncheck boxes in alpha release template
  .github/ISSUE_TEMPLATE/alpha_release.md
Labels: ci:no-build

#3381 chore(github): create patch release issue template
  .github/ISSUE_TEMPLATE/patch_release.md
Labels: ci:no-build

#3382 chore(spring): update spring framework and spring boot
  parent/pom.xml
Labels: ci:run, ci:spring-boot, bot:java-dependency-tree

#3383 chore(github): adapt notification workflow parameters for devex notif…
  .github/workflows/extract-issue-links.yml
Labels: ci:no-build

#3365 fix(engine): adjust exception handling in external tasks
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HandleExternalTaskCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.shouldThrowProcessEngineExceptionWhenOtherResourceIsNotFound.bpmn20.xml
Labels: ci:spring-boot
