Repository camunda/camunda-bpm-platform, pull requests merged in 2023-01, with the labels that each got.

#3040 [#2777]: chore(ci): add aws auora postgresql 13
  .ci/config/matrices.yaml
Labels: ci:postgresql

#3048 chore(ci): add withLabels to all stages
  .ci/daily/Jenkinsfile
  Jenkinsfile
Labels: ci:no-build

#3054 [2805]: chore(xtac): remove deprecated exception types
  clients/java/client/src/it/java/org/camunda/bpm/client/variable/pa/PaExceptionIT.java
  clients/java/client/src/main/java/org/camunda/bpm/client/exception/BadRequestException.java
  clients/java/client/src/main/java/org/camunda/bpm/client/exception/EngineException.java
  clients/java/client/src/main/java/org/camunda/bpm/client/exception/NotAcquiredException.java
  clients/java/client/src/main/java/org/camunda/bpm/client/exception/NotResumedException.java
Labels: ci:h2

#3056 2850: remove password and salt fields from user#toString
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/UserEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceTest.java
Labels: ci:no-build

#3055 2949: change exception type when signalling single execution
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/SignalRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/SignalRestServiceTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SignalEventReceivedCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventReceivedBuilderTest.java
Labels: ci:rest-api

#3063 chore(ci): add custom span attributes (OTEL) at the pipelines end
  .ci/daily/Jenkinsfile
  .ci/main-trigger/Jenkinsfile
  .ci/sidetrack/Jenkinsfile
  Jenkinsfile
Labels: ci:no-build

#3077 fix(webapps): include admin groups & users in admin check
  webapps/src/main/java/org/camunda/bpm/cockpit/plugin/resource/AbstractCockpitPluginResource.java
  webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/IncidentRestServiceTenantCheckTest.java
  webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/ProcessDefinitionResourceTenantCheckTest.java
  webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/ProcessInstanceResourceTenantCheckTest.java
  webapps/src/test/java/org/camunda/bpm/cockpit/plugin/base/tenantcheck/ProcessInstanceRestServiceTenantCheckTest.java
Labels: ci:authorizations, ci:webapp-integration

#3039 test(archunit): check if public API interfaces leak implementation
  engine-cdi/core/pom.xml
  engine-dmn/engine/pom.xml
  engine-spring/core/pom.xml
  engine/pom.xml
  engine/src/test/resources/archunit_ignore_patterns.txt
  model-api/bpmn-model/pom.xml
  model-api/bpmn-model/src/test/resources/archunit_ignore_patterns.txt
  model-api/cmmn-model/pom.xml
  model-api/dmn-model/pom.xml
  pom.xml
  test-utils/archunit/pom.xml
  test-utils/archunit/src/main/java/org/camunda/bpm/engine/test/archunit/ArchRulesTest.java
  typed-values/pom.xml
  typed-values/src/test/resources/archunit_ignore_patterns.txt
Labels: ci:h2, ci:no-build

#3081 chore(test): fix failing job prio tests for MSSQL and DB2
  engine/src/test/java/org/camunda/bpm/engine/test/jobexecutor/JobExecutorAcquireJobsForPriorityRangeTest.java
Labels: ci:all-db

#3084 chore(webapps): incorporate german webapp translations
  webapps/grunt/config/localescompile.js
  webapps/ui/admin/client/locales/de.json
  webapps/ui/admin/client/locales/en.json
  webapps/ui/admin/grunt/config/eslint.js
  webapps/ui/cockpit/client/locales/de.json
  webapps/ui/cockpit/client/locales/en.json
  webapps/ui/cockpit/grunt/config/eslint.js
  webapps/ui/tasklist/client/locales/de.json
  webapps/ui/tasklist/client/locales/en.json
  webapps/ui/tasklist/grunt/config/eslint.js
  webapps/ui/tasklist/grunt/config/watch.js
  webapps/ui/welcome/client/locales/de.json
  webapps/ui/welcome/client/locales/en.json
  webapps/ui/welcome/grunt/config/eslint.js
Labels: ci:e2e

#3059 chore(rest): align fetching of engine in REST services
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/AbstractAuthorizedRestResource.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/AbstractRestProcessEngineAware.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/AuthorizationRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ConditionRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ExternalTaskRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/IdentityRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/IncidentRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/MessageRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/MetricsRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/MigrationRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessDefinitionRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ProcessInstanceRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/SchemaLogRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/SignalRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/TelemetryRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/VariableInstanceRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/history/HistoricProcessDefinitionRestServiceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/spi/impl/AbstractProcessEngineAware.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/authorization/impl/AuthorizationResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/identity/impl/AbstractIdentityResource.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/identity/impl/GroupResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/identity/impl/TenantResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/FilterResourceImpl.java
Labels: ci:rest-api, ci:run, ci:spring-boot

#3104 fix(cockpit): add `camunda-dmn-js` features
  webapps/camunda-commons-ui/grunt/tasks/ensureLibs.js
  webapps/camunda-commons-ui/grunt/tasks/persistify.js
  webapps/camunda-commons-ui/index.js
  webapps/camunda-commons-ui/lib/widgets/dmn-viewer/cam-widget-dmn-viewer.js
  webapps/grunt/tasks/license-check.js
  webapps/package-lock.json
  webapps/package.json
  webapps/ui/welcome/grunt/config/copy.js
Labels: ci:e2e

#3108 chore(ci): fetch the project version from the JOB_NAME
  .ci/daily/Jenkinsfile
Labels: ci:no-build

#3090 chore(ci): add explicit check for default branch in assembly stage
  Jenkinsfile
Labels: ci:no-build
