Repository camunda/camunda-bpm-platform, pull requests merged in 2023-07, with the labels that each got.

#3539 fix(ci): run javadocs with JDK 17
  .ci/daily/Jenkinsfile
Labels: ci:no-build

#3520 chore(swaggerui): bump version
  distro/run/modules/swaggerui/pom.xml
  distro/run/modules/swaggerui/ui/.gitignore
  distro/run/modules/swaggerui/ui/package-lock.json
  distro/run/modules/swaggerui/ui/package.json
  distro/run/modules/swaggerui/ui/tasks/license.js
  distro/run/modules/swaggerui/ui/tasks/licenses/LICENSE_format
  distro/run/modules/swaggerui/ui/tasks/licenses/LICENSE_toggle-selection
  distro/run/modules/swaggerui/ui/webpack.config.js
  engine-rest/docs/.gitignore
  engine-rest/docs/package-lock.json
  engine-rest/docs/pom.xml
  parent/pom.xml
  webapps/pom.xml
Labels: ci:default-build, ci:run

#3536 test(engine-rest): retry server start when port still bound
  engine-rest/engine-rest-jakarta/src/test/java-resteasy/org/camunda/bpm/engine/rest/util/container/ResteasySpecifics.java
  engine-rest/engine-rest-jakarta/src/test/java-resteasy/org/camunda/bpm/engine/rest/util/container/ResteasyUndertowServerBootstrap.java
  engine-rest/engine-rest/src/test/java-jersey2/org/camunda/bpm/engine/rest/util/container/JerseyServerBootstrap.java
  engine-rest/engine-rest/src/test/java-resteasy/org/camunda/bpm/engine/rest/util/container/ResteasyServerBootstrap.java
  engine-rest/engine-rest/src/test/java-resteasy/org/camunda/bpm/engine/rest/util/container/ResteasyTomcatServerBootstrap.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/AbstractServerBootstrap.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/EmbeddedServerBootstrap.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/util/container/TomcatServerBootstrap.java
Labels: ci:rest-api

#3540 test(engine+webapps): simplify revoke ALWAYS tests
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/AuthorizationRevokeModeAlwaysTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/AuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/SetTaskPropertyAuthorizationTest.java
  webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/authorization/AuthorizationTest.java
Labels: ci:all-db

#3421 chore(cdi): remove weld 1 support
  engine-cdi/compatibility-test-weld3/pom.xml
  engine-cdi/core/pom.xml
  engine-cdi/pom.xml
  qa/integration-tests-engine/pom.xml
Labels: ci:all-as, ci:default-build, bot:java-dependency-tree

#3565 fix(engine): respect user when deleting auth for group memberships
  engine/src/main/java/org/camunda/bpm/engine/impl/identity/db/DbIdentityServiceProvider.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java
Labels: ci:h2, ci:no-build

#3577 chore(pom.xml): bump release parent
  pom.xml
Labels: ci:h2

#3538 chore(run): add test coverage for cockpit plugins
  distro/run/qa/example-plugin/pom.xml
  distro/run/qa/example-plugin/src/main/java/org/camunda/bpm/run/plugins/TestCockpitPlugin.java
  distro/run/qa/example-plugin/src/main/java/org/camunda/bpm/run/plugins/TestCockpitResource.java
  distro/run/qa/example-plugin/src/main/resources/META-INF/services/org.camunda.bpm.cockpit.plugin.spi.CockpitPlugin
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/plugin/CockpitPluginAutoDeploymentIT.java
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java
  distro/run/qa/pom.xml
  distro/run/qa/runtime/pom.xml
Labels: ci:run

#3143 fix(engine-dmn): allow to return blank table output as null
  engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java
  engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/evaluation/DecisionTableEvaluationHandler.java
  engine-dmn/engine/src/test/java/org/camunda/bpm/dmn/engine/api/ReturnBlankTableOutputAsNullTest.java
  engine-dmn/engine/src/test/resources/org/camunda/bpm/dmn/engine/api/ReturnBlankTableOutputAsNull.dmn
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/dmn/configuration/DmnEngineConfigurationBuilder.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/dmn/HistoricDecisionInstanceReturnBlankTableOutputAsNullTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/history/ReturnBlankTableOutputAsNull.dmn
Labels: ci:h2

#3567 chore(project): Update Jackson to 2.15.2
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-annotations/2.15.2/module.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-core/2.15.2/module.xml
  distro/wildfly/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/2.15.2/module.xml
  distro/wildfly26/modules/src/main/modules/com/fasterxml/jackson/core/jackson-annotations/2.15.2/module.xml
  distro/wildfly26/modules/src/main/modules/com/fasterxml/jackson/core/jackson-core/2.15.2/module.xml
  distro/wildfly26/modules/src/main/modules/com/fasterxml/jackson/core/jackson-databind/2.15.2/module.xml
  parent/pom.xml
  pom.xml
  qa/integration-tests-engine/src/test/resources-wildfly26/jboss-deployment-structure-spin-json.xml
Labels: ci:jbosseap, ci:rest-api, ci:wildfly

#3596 fix(run): exclude Run QA module from JDK 11 stages
  .ci/config/stage-types.yaml
Labels: ci:jdk

#3594 chore(webapps): update fast-xml-parser
  webapps/frontend/package-lock.json
  webapps/frontend/package.json
Labels: ci:e2e

#3554 test(engine): log unexpected exception in concurrent tests
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/ConcurrencyTestHelper.java
Labels: ci:all-db

#3593 chore(oracle): remove support for Oracle 12
  .ci/config/matrices.yaml
  database/pom.xml
  qa/performance-tests-engine/README.md
  settings/maven/nexus-settings.xml
Labels: ci:oracle
