Repository camunda/camunda-bpm-platform, pull requests merged in 2023-06, with the labels that each got.

#3446 feat(engine): Add Separate HistoryCleanup Retries Config
  engine/src/main/java/org/camunda/bpm/engine/ProcessEngineConfiguration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/HistoryCleanupCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupContext.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupHelper.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupJobDeclaration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/EverLivingJobEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/SetTaskPropertyAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryCleanupTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/IncidentTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/EntityRemoveRule.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/Removable.java
Labels: ci:default-build

#3432 chore(project): remove superfluous CI stages
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  .ci/daily/Jenkinsfile
  Jenkinsfile
  engine-rest/engine-rest/pom.xml
  engine-rest/engine-rest/src/test/java-cxf/org/camunda/bpm/engine/rest/util/container/CXFServerBootstrap.java
  engine-rest/engine-rest/src/test/java-cxf/org/camunda/bpm/engine/rest/util/container/CXFSpecifics.java
  engine-rest/engine-rest/src/test/java-cxf/org/camunda/bpm/engine/rest/util/container/CXFTomcatServerBootstrap.java
  engine-rest/engine-rest/src/test/resources-cxf/META-INF/services/org.camunda.bpm.engine.rest.util.container.ContainerSpecifics
  engine-rest/engine-rest/src/test/resources-cxf/custom-date-format-web.xml
  engine/pom.xml
  parent/pom.xml
Labels: ci:all-db, ci:rest-api

#3476 test(qa): increase maximum heap size for old engine tests
  qa/test-old-engine/pom.xml
Labels: ci:all-db

#3453 chore(sql-script): integrate upgrade tests
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  .ci/daily/Jenkinsfile
  distro/sql-script/pom.xml
  distro/sql-script/src/test/java/org/camunda/bpm/sql/test/SqlScriptTest.java
  distro/sql-script/src/test/resources/properties-from-pom.properties
  qa/pom.xml
  qa/test-db-upgrade/README.md
  qa/test-db-upgrade/clear.authorization.table.sql
  qa/test-db-upgrade/config/camunda.cfg.xml
  qa/test-db-upgrade/config/org/camunda/bpm/engine/test/concurrency/historycleanup.camunda.cfg.xml
  qa/test-db-upgrade/pom.xml
Labels: ci:all-db

#3420 chore(webapps): get rid of warnings
  webapps/frontend/ui/admin/client/styles/styles.less
  webapps/frontend/ui/cockpit/client/styles/styles.less
  webapps/frontend/ui/tasklist/client/styles/styles.less
  webapps/frontend/ui/welcome/client/styles/styles.less
Labels: ci:e2e

#3478 fix(engine): Fix SetProperty & Multi-tenancy Problem with MySQL ms Precision
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/SetTaskPropertyAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancySetTaskPropertyTest.java
Labels: ci:mysql, ci:no-build

#3469 Integrate revoke stages into engine unit tests
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  Jenkinsfile
  engine/pom.xml
  engine/src/main/java/org/camunda/bpm/engine/test/ProcessEngineRule.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ActivityStatisticsAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/AuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/DeploymentAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/DeploymentStatisticsAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/EventSubscriptionAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ExecutionAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/IncidentAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/JobAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/JobDefinitionAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ProcessDefinitionAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ProcessDefinitionStatisticsAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ProcessInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/SetTaskPropertyAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/TaskAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/VariableInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/batch/BatchQueryAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/batch/BatchStatisticsQueryAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/batch/HistoricBatchQueryAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/dmn/DecisionDefinitionAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/dmn/DecisionRequirementsDefinitionQueryAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/ExternalTaskQueryAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/FetchExternalTaskAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricActivityInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricActivityStatisticsAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricDecisionInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricDetailAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricExternalTaskLogAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricIdentityLinkLogAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricIncidentAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricJobLogAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricProcessInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/HistoricVariableInstanceAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/history/UserOperationLogAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/task/updatevariable/StandaloneTaskAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/util/AuthorizationTestBaseRule.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/filter/FilterAuthorizationsTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/identity/AuthorizationQueryAuthorizationsTest.java
  webapps/assembly-jakarta/pom.xml
  webapps/assembly/pom.xml
  webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/authorization/AuthorizationTest.java
Labels: ci:all-db

#3484 chore(webapps): cleanup grunt leftovers
  webapps/README.md
  webapps/frontend/camunda-bpm-sdk-js/.eslintignore
  webapps/frontend/camunda-commons-ui/.eslintignore
  webapps/frontend/camunda-commons-ui/index.js
Labels: ci:e2e

#3452 chore(ci): run Assembly, spring-boot-starter, and run stage with JDK 17
  .ci/config/stage-types.yaml
  Jenkinsfile
Labels: ci:default-build, ci:no-build, ci:spring-boot

#3455 chore(test): add graalvm js script engine dependency
  spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml
Labels: ci:no-build, ci:spring-boot, bot:java-dependency-tree

#3465 chore(run-IT): fetch process id via java.lang.Process#pid()
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/util/SpringBootManagedContainer.java
Labels: ci:no-build, ci:run

#3489 chore(ci): remove JDK8 CI stages
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
Labels: ci:default-build

#3473 Fix History Cleanup Removal Time Issue
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupJobHandler.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupByteArrayRemovalTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/EntityRemoveRule.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/Removable.java
Labels: ci:default-build

#3398 chore(webapps): retry test server start when port bound
  webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/util/HeaderRule.java
Labels: ci:all-db

#3507 3447: adjust clirr and test fixture
  Jenkinsfile
  engine/.clirr-jenkins-ignore.xml
  qa/test-db-instance-migration/test-fixture-719/pom.xml
Labels: ci:default-build, ci:migration

#3485 3439: Spring 6 support for engine-spring
  Jenkinsfile
  bom/pom.xml
  distro/wildfly/assembly/pom.xml
  engine-spring/core-6/pom.xml
  engine-spring/core/src/main/java/org/camunda/bpm/engine/spring/application/SpringProcessApplicationElResolver.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/autodeployment/SpringAutoDeployTest.java
  engine-spring/core/src/test/java/org/camunda/bpm/engine/spring/test/transaction/UserBean.java
  engine-spring/pom.xml
  parent/pom.xml
  qa/integration-tests-engine-jakarta/pom.xml
  qa/integration-tests-engine-jakarta/src/test/java/org/camunda/bpm/integrationtest/util/DeploymentHelper.java
  qa/pom.xml
  qa/wildfly-runtime/pom.xml
Labels: ci:all-as, ci:default-build, ci:spring-boot, ci:webapp-integration

#3504 fix(cockpit): fix initial deployments page loading
  webapps/frontend/ui/common/scripts/module/controllers/cam-pagination-search-integration.js
Labels: ci:e2e

#3508 fix(engine): Fix Broken Tests
  engine-dmn/engine/src/main/java/org/camunda/bpm/dmn/engine/impl/spi/transform/DmnElementTransformHandler.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/dmn/configuration/DmnEngineConfigurationBuilder.java
  engine/src/main/java/org/camunda/bpm/engine/impl/dmn/transformer/DecisionDefinitionHandler.java
  engine/src/test/java/org/camunda/bpm/engine/test/dmn/deployment/DecisionDefinitionTest.java
Labels: ci:default-build

#3492 chore(engine): Allow Null Values to TaskService Operations
  engine/src/main/java/org/camunda/bpm/engine/TaskService.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractSetTaskPropertyCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskDescriptionCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskDueDateCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetTaskFollowUpDateCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
Labels: ci:h2

#3511 test(engine): increase wait time on CRDB for batch test
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/migration/batch/BatchMigrationTest.java
  qa/test-old-engine/pom.xml
Labels: ci:cockroachdb

#3405 feat(quarkus): update to quarkus3
  engine-cdi/core/pom.xml
  engine-cdi/jakarta/pom.xml
  parent/pom.xml
  quarkus-extension/engine/deployment/src/main/java/org/camunda/bpm/quarkus/engine/extension/deployment/impl/CamundaEngineProcessor.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/BusinessProcessContextTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/ConfigurableProcessEngineTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/EmbeddedProcessEngineTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/ManagedJobExecutorTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineConfigFileTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineConfigurationConfigTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineDefaultConfigTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineJobExecutorConfigTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineProgrammaticAndConfigFileTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/deployment/ProcessEngineMultipleDeploymentTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/deployment/ProcessEngineSingleDeploymentTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/id/ConfigureDbIdGeneratorTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/id/DefaultIdGeneratorTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/lookup/BeanWithProducerMethods.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/lookup/ProgrammaticBeanLookupTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/TransactionIntegrationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/UserTransactionIntegrationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/conf/ChooseDatasourceConfigurationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/conf/DatasourceConfigurationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/persistence/conf/NoDefaultDatasourceConfigurationTest.java
  quarkus-extension/engine/qa/pom.xml
  quarkus-extension/engine/qa/src/test/java/org/camunda/bpm/engine/cdi/test/CdiProcessEngineTestCase.java
  quarkus-extension/engine/qa/src/test/java/org/camunda/bpm/engine/cdi/test/bean/QuarkusDeclarativeProcessController.java
  quarkus-extension/engine/runtime/pom.xml
  quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/QuarkusProcessEngineConfiguration.java
  quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaEngineRecorder.java
  quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/InjectableBusinessProcessContext.java
  quarkus-extension/pom.xml
Labels: ci:default-build

#3502 fix(cockpit): fix `fast-xml-parser` usage
  webapps/frontend/camunda-bpm-sdk-js/lib/forms/type-util.js
Labels: ci:e2e

#3526 test(engine): stabilize SignalEventConcurrencyTest
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/signal/SignalEventConcurrencyTest.java
Labels: ci:all-db
