Repository camunda/camunda-bpm-platform, pull requests merged in 2023-03, with the labels that each got.

#3163 [3148]: fix(webapps): forward to welcome app if unauthorized
  webapps/camunda-bpm-sdk-js/lib/api-client/http-client.js
  webapps/camunda-commons-ui/lib/services/HttpClient.js
  webapps/camunda-commons-ui/lib/services/ifUnauthorizedForwardToWelcomeApp.js
  webapps/camunda-commons-ui/lib/services/index.js
Labels: ci:e2e, ci:no-build

#3188 test(qa): execute Jakarta test classes on JDK 11+
  qa/test-db-upgrade/pom.xml
  qa/test-old-engine/pom.xml
Labels: ci:h2, ci:migration, ci:rolling-update

#3181 chore(project): update commons-fileupload, tomcat, spring boot
  internal-dependencies/pom.xml
  parent/pom.xml
Labels: ci:rest-api, ci:run, ci:spring-boot, ci:tomcat, bot:java-dependency-tree

#3184 feat(javaee): Support EJB 4.0 in EJB Client
  engine-cdi/jakarta/pom.xml
  engine/src/main/resources/META-INF/camunda-renames.properties
  engine/src/main/resources/META-INF/jakarta-renames.properties
  javaee/ejb-client-jakarta/pom.xml
  javaee/ejb-client/src/main/java/org/camunda/bpm/application/impl/ejb/DefaultEjbProcessApplication.java
  parent/pom.xml
  pom.xml
Labels: ci:all-as

#3204 fix(openapi): include duedate parameter for all job retries endpoints
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobRetriesDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesByProcessDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/SetJobRetriesDto.ftl
Labels: ci:rest-api

#3183 chore(deps): update quarkus 2.x
  parent/pom.xml
Labels: bot:java-dependency-tree

#3211 fix(engine-rest): fix jdk profile activation problem
  engine-rest/engine-rest-jakarta/pom.xml
Labels: ci:rest-api

#3213 fix(cockpit): improve wording
  webapps/ui/cockpit/client/locales/en.json
  webapps/ui/cockpit/plugins/base/app/views/processInstance/job-retry-bulk-dialog.html
  webapps/ui/cockpit/plugins/base/app/views/processInstance/job-retry-dialog.html
Labels: ci:no-build

#3205 fix(tasklist): changing task props don't re-render plugin
  webapps/ui/tasklist/client/scripts/task/directives/cam-tasklist-task.js
Labels: ci:e2e

#3202 fix(webapps): translate pagination ui
  webapps/ui/admin/client/locales/de.json
  webapps/ui/admin/client/locales/en.json
  webapps/ui/admin/client/scripts/camunda-admin-ui.js
  webapps/ui/cockpit/client/locales/de.json
  webapps/ui/cockpit/client/locales/en.json
  webapps/ui/cockpit/client/scripts/camunda-cockpit-ui.js
  webapps/ui/common/scripts/util/translate-pagination-ctrls.js
  webapps/ui/tasklist/client/locales/de.json
  webapps/ui/tasklist/client/locales/en.json
  webapps/ui/tasklist/client/scripts/camunda-tasklist-ui.js
  webapps/ui/welcome/client/locales/de.json
  webapps/ui/welcome/client/locales/en.json
  webapps/ui/welcome/client/scripts/camunda-welcome-ui.js
Labels: ci:e2e

#3203 fix(cockpit): fix display of date in dmn output table
  webapps/ui/cockpit/plugins/decisionList/app/views/decisionInstance/outputTable.js
Labels: ci:e2e

#3198 chore(settings): adjust nexus mirror
  settings/maven/nexus-settings.xml
Labels: ci:no-build

#3237 fix(ci): fix webapps assembly exclusion
  .ci/config/stage-types.yaml
  CONTRIBUTING.md
Labels: ci:jdk

#3241 fix(webapps): fix engine webapps stages and missing groupId
  .ci/config/stage-types.yaml
  webapps/assembly/pom.xml
Labels: ci:authorizations

#3227 fix (bug fix): set objectMaper on JobQueryDto
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/JobRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java
Labels: ci:rest-api

#3235 chore(distro/wildfly): remove JBoss Web dependency
  distro/wildfly/modules/src/main/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml
  distro/wildfly26/modules/src/main/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml
  qa/wildfly-runtime/src/main/common/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml
  qa/wildfly26-runtime/src/main/common/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml
Labels: ci:jboss, ci:wildfly

#3249 chore(distro/wildfly): use jakarta webapps & enable QA
  Jenkinsfile
  distro/wildfly/webapp/pom.xml
Labels: ci:wildfly

#3251 fix(ci): fix stages containing assembly-jakarta
  .ci/config/stage-types.yaml
  examples/invoice/pom.xml
Labels: ci:jdk

#3212 feat(logging): add webapps logging
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  webapps/assembly-jakarta/pom.xml
  webapps/assembly/src/main/java/org/camunda/bpm/admin/impl/web/SetupResource.java
  webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/WebappLogger.java
  webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/security/auth/AuthenticationUtil.java
  webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/security/auth/Authentications.java
  webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/security/auth/UserAuthenticationResource.java
  webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/security/auth/UserAuthenticationResourceLoggingTest.java
  webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/security/auth/UserAuthenticationResourceTest.java
  webapps/assembly/src/test/resources/camunda-test-engine.cfg.xml
  webapps/pom.xml
Labels: ci:all-as, ci:webapp-integration, scope:webapp

#3255 chore(webapps): bump form-js to 0.12.2
  webapps/frontend/package-lock.json
  webapps/frontend/package.json
Labels: ci:e2e

#3264 chore(webapps): enable jakarta unit tests
  .ci/config/stage-types.yaml
  .ci/daily/Jenkinsfile
  webapps/assembly-jakarta/pom.xml
  webapps/assembly/pom.xml
Labels: ci:authorizations, ci:default-build

#3266 chore(webapps): introduce logback config file
  webapps/assembly/src/test/resources/logback-test.xml
  webapps/assembly/src/test/resources/logging.properties
Labels: ci:h2, scope:webapp

#3270 feat(example/invoice): add jakarta invoice example module
  distro/wildfly/distro/assembly.xml
  distro/wildfly/distro/pom.xml
  examples/invoice-jakarta/README.md
  examples/invoice-jakarta/pom.xml
  examples/invoice/pom.xml
  examples/invoice/src/main/java/org/camunda/bpm/example/invoice/InvoiceProcessApplication.java
  examples/invoice/src/main/java/org/camunda/bpm/example/invoice/JakartaInvoiceProcessApplication.java
  examples/pom.xml
  pom.xml
  qa/integration-tests-webapps/shared-engine/pom.xml
Labels: ci:all-as, ci:webapp-integration

#3292 chore(webapps/locales): provide german translation for 7.19
  webapps/frontend/ui/cockpit/client/locales/de.json
Labels: ci:no-build

#3285 chore(license-book): update license book for 7.19.0
  distro/license-book/src/main/resources/license-book.txt
Labels: ci:no-build
