Repository camunda/camunda-bpm-platform, pull requests merged in 2023-05, with the labels that each got.

#3364 fix(engine): propagate skipCustomListeners in removeTasks
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/deploy/SingleVariableListener.java
Labels: ci:default-build

#3389 test(spring-boot): correcting frontend lib path
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/ChangedAppPathIT.java
Labels: ci:spring-boot

#3387 chore(run/swaggerui): include prod deps only in license book
  distro/run/modules/swaggerui/ui/webpack.config.js
Labels: ci:run

#3390 chore(webapps): fix xlts skip registry config
  webapps/frontend/scripts/xlts.js
Labels: ci:default-build

#3391 chore(webapps): prettier overrides editorconfig
  webapps/frontend/.prettierrc
Labels: ci:no-build

#3397 fix(webapps): add resource handler for new assets directory
  spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappAutoConfiguration.java
  spring-boot-starter/starter-webapp-core/src/main/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappInitializer.java
Labels: ci:run, ci:spring-boot

#3369 chore(pom): add Camunda public artifactory repo for local builds
  javaee/jobexecutor-ra/pom.xml
  parent/pom.xml
  pom.xml
Labels: ci:all-as, ci:webapp-integration

#3408 fix(webapps): make `skipFrontendBuild` possible again
  distro/webjar/pom.xml
  webapps/assembly-jakarta/pom.xml
  webapps/assembly/pom.xml
  webapps/pom.xml
Labels: ci:no-build

#3415 chore(webapps): fix charset of scripts
  webapps/frontend/webpack.common.js
  webapps/frontend/webpack.prod.js
Labels: ci:e2e

#3423 fix(webapps/cockpit): fix variable file upload
  webapps/frontend/ui/cockpit/client/scripts/components/variables/variable-upload-dialog.html
  webapps/frontend/ui/cockpit/client/scripts/components/variables/variable-upload-dialog.js
Labels: ci:e2e

#3427 chore(parent): bump Spring Boot and Tomcat versions
  parent/pom.xml
Labels: ci:run, ci:spring-boot, ci:tomcat, ci:webapp-integration, bot:java-dependency-tree

#3410 chore(webapps): bump xlts.dev angularjs
  webapps/frontend/package.json
Labels: ci:e2e

#3450 chore(webpack): correct dev server proxy mapping
  webapps/assembly/pom.xml
  webapps/frontend/webpack.dev.js
Labels: ci:e2e

#3456 feat(webapps): explicit asset declaration for plugins
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/LoginIT.java
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/PluginsRootResourceIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/PluginsRootResourceIT.java
  webapps/assembly/src/main/java/org/camunda/bpm/webapp/plugin/resource/AbstractAppPluginRootResource.java
  webapps/assembly/src/test/java/org/camunda/bpm/webapp/plugin/resource/AbstractAppPluginRootResourceTest.java
Labels: ci:e2e, ci:all-as, ci:webapp-integration
