Repository camunda/camunda-bpm-platform, pull requests merged in 2023-08, with the labels that each got.

#3617 chore(rest): remove WAS 9 support
  engine-rest/assembly/assembly-war-was.xml
  engine-rest/assembly/pom.xml
  engine-rest/assembly/src/main/runtime/was/webapp/WEB-INF/web.xml
  engine-rest/assembly/src/main/runtime/was9/webapp/WEB-INF/web.xml
Labels: ci:websphere

#3632 fix(engine): fail on db metadata initialization errors
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ConfigurationLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Labels: ci:all-db

#3641 chore(engine-spring): remove Spring 4 test compatibility module
  engine-spring/compatibility-test-spring4/pom.xml
  engine-spring/compatibility-test-spring4/src/test/java/org/camunda/bpm/engine/spring/test/Spring4TestHelper.java
  engine-spring/compatibility-test-spring4/src/test/resources/META-INF/services/org.camunda.bpm.engine.spring.test.SpringTestHelper
  engine-spring/pom.xml
Labels: ci:default-build, ci:jdk

#3568 chore(run): add JDK check to run script
  distro/run/assembly/resources/run.bat
  distro/run/assembly/resources/run.sh
Labels: ci:run

#3634 chore(parent): bump to snakeyaml 2.1
  parent/pom.xml
Labels: ci:run, bot:java-dependency-tree

#3675 chore(pom): bump Spin to 1.21.0
  pom.xml
Labels: ci:default-build

#3608 chore(webapps): update semver
  distro/run/modules/swaggerui/ui/package-lock.json
  engine-rest/docs/package-lock.json
  engine-rest/docs/package.json
  webapps/frontend/package-lock.json
Labels: ci:e2e

#3625 test(sql-script): stabilize cleanup and comparison
  distro/sql-script/src/test/java/org/camunda/bpm/sql/test/SqlScriptTest.java
Labels: ci:all-db

#3683 feat(engine): re-evaluate timer cycle expression
  engine/src/main/java/org/camunda/bpm/engine/impl/calendar/CycleBusinessCalendar.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/RepeatingFailedJobListener.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/TimerDeclarationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TimerEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/EngineUtilLogger.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/MyCycleTimerBean.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.shouldReevaluateTimerCycleWhenDue.bpmn20.xml
Labels: ci:default-build, ci:mysql

#3705 chore(prj): move template engines to community hub
  bom/pom.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/org/camunda/template-engines/camunda-template-engines-freemarker/main/module.xml
  distro/wildfly26/modules/pom.xml
  distro/wildfly26/modules/src/main/modules/org/camunda/template-engines/camunda-template-engines-freemarker/main/module.xml
  pom.xml
Labels: ci:default-build, ci:wildfly

#3703 chore(bom): remove xslt template engine
  bom/pom.xml
  pom.xml
Labels: ci:no-build

#3718 chore(engine): cover re-evaluate start timer cycle with date
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/TimerDeclarationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/TimerEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
Labels: ci:h2, ci:mysql, ci:no-build
