Repository camunda/camunda-bpm-platform, pull requests merged in 2024-11, with the labels that each got.

#4770 add(ci): add support for AWS Aurora Postgres 16
  .ci/config/matrices.yaml
Labels: ci:no-build, ci:postgresql, ci:skipTests

#4552 feat(root): Add Postgres 17
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  .ci/daily/Jenkinsfile
  Jenkinsfile
  engine-rest/engine-rest-jakarta/pom.xml
Labels: ci:migration, ci:postgresql, ci:rolling-update, ci:skipTests

#4785 Bump to commons-io:2.17.0
  internal-dependencies/pom.xml
Labels: ci:default-build, ci:jdk, ci:rest-api, ci:rolling-update, ci:webapp-integration, bot:java-dependency-check

#4769 fix(engine): allow querying for hist pis by async activities
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
Labels: ci:all-db

#4734 chore(webapps): use HeroDev libraries
  Jenkinsfile
  webapps/README.md
  webapps/frontend/package.json
  webapps/frontend/scripts/xlts.js
  webapps/pom.xml
Labels: ci:e2e, ci:webapp-integration

#4778 fix(admin): fix display of usage metrics > 12 months
  webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.js
Labels: ci:e2e, bot:backport:7.21, bot:backport:7.22

#4801 chore(config): Add Podspec Execution to instance-migration
  .ci/config/stage-types.yaml
Labels: ci:postgresql

#4805 openapi(tasks): include task state in response specification
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/task/TaskDto.ftl
Labels: bot:backport:7.22

#4790 feat(engine): don't fail on change variables async when process instance does not exist
  engine/src/main/java/org/camunda/bpm/engine/impl/batch/variables/BatchSetVariablesHandler.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractVariableCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/SetExecutionVariablesCmd.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RuntimeServiceTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/JobEntityAndJobLogBatchIdTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/ExecutableProcessUtil.java
Labels: ci:all-db, ci:default-build, ci:migration, ci:rest-api, ci:rolling-update, bot:backport:7.22

#4807 chore(parent): Bump Spring Libraries
  parent/pom.xml
Labels: ci:e2e, ci:all-as, ci:spring-boot, bot:java-dependency-check, bot:backport:7.22

#4819 chore(parent): Set Spring Version to 6.1.15
  parent/pom.xml
Labels: ci:all-as, ci:rest-api

#4808 fix(openApi): add missing schema declarations
  engine-rest/engine-rest-openapi/README.md
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/errorDetails/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/{id}/error-details/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/{id}/stacktrace/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/stacktrace/get.ftl
Labels: bot:backport:7.22

#4565 feat(core) Add update and delete command Java/Rest APIs
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/{commentId}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/{commentId}/delete.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/ProcessInstanceCommentResource.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/runtime/impl/ProcessInstanceCommentResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/TaskCommentResource.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/sub/task/impl/TaskCommentResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine/src/main/java/org/camunda/bpm/engine/EntityTypes.java
  engine/src/main/java/org/camunda/bpm/engine/TaskService.java
  engine/src/main/java/org/camunda/bpm/engine/history/UserOperationLogEntry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/TaskServiceImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/auth/AuthorizationCommandChecker.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/multitenancy/TenantCommandChecker.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AddCommentCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteProcessInstanceCommentCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/DeleteTaskCommentCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/UpdateCommentCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/CommentEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/CommentManager.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/UserOperationLogManager.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Comment.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/AuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/ProcessInstanceCommentAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/TaskCommentAuthorizationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/encoding/ProcessEngineCharacterEncodingTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskLastUpdatedTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/task/TaskServiceTest.java
Labels: ci:e2e, ci:default-build, ci:rest-api
