Repository camunda/camunda-bpm-platform, pull requests merged in 2024-05, with the labels that each got.

#4320 fix(webapp): add missing metrics translations
  webapps/frontend/package-lock.json
  webapps/frontend/public/app/admin/locales/de.json
  webapps/frontend/public/app/admin/locales/en.json
  webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.html
Labels: ci:e2e

#4317 feat(api): add filter on rootProcessInstanceId for historic task instances query
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-task-instance-query-params.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricTaskInstanceQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricTaskInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricTaskInstanceQueryImpl.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricTaskInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricTaskInstanceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/history/multiprocess/rootProcess.bpmn
  engine/src/test/resources/org/camunda/bpm/engine/test/api/history/multiprocess/secondLevelProcess.bpmn
  engine/src/test/resources/org/camunda/bpm/engine/test/api/history/multiprocess/thirdLevelProcess.bpmn
Labels: ci:all-db, ci:rest-api

#4328 bugfix(commons): fix typed-values parent path
  commons/typed-values/pom.xml
Labels: ci:e2e, ci:all-as

#4330 chore(swaggerui): bump dependencies
  distro/run/modules/swaggerui/ui/package-lock.json
  distro/run/modules/swaggerui/ui/package.json
Labels: ci:run

#4341 fix(ci): move publishDocs to runSteps
  .ci/daily/Jenkinsfile
Labels: ci:no-build

#4350 chore(webapp): bump form-js
  webapps/frontend/package-lock.json
  webapps/frontend/package.json
Labels: ci:e2e

#4360 deps(project): update to Spring 6.1.7 and 5.3.35
  parent/pom.xml
Labels: ci:e2e, ci:all-as, ci:spring-boot, ci:wildfly, bot:java-dependency-check

#4356 chore(.github): adjust pr labels helper
  .github/helpers/pr-labels.yml
Labels: ci:no-build

#4370 chore(deps): update to SB 3.2.6, SF 6.3.36, 6.1.8
  parent/pom.xml
Labels: ci:jdk, ci:spring-boot, ci:wildfly, bot:java-dependency-check

#4355 4195 move freemarker engine into platform
  bom/camunda-only-bom/pom.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/org/camunda/template-engines/camunda-template-engines-freemarker/main/module.xml
  distro/wildfly26/modules/pom.xml
  distro/wildfly26/modules/src/main/modules/org/camunda/template-engines/camunda-template-engines-freemarker/main/module.xml
  freemarker-template-engine/.gitignore
  freemarker-template-engine/README.md
  freemarker-template-engine/pom.xml
  freemarker-template-engine/src/main/java/org/camunda/templateengines/FreeMarkerCompiledScript.java
  freemarker-template-engine/src/main/java/org/camunda/templateengines/FreeMarkerScriptEngine.java
  freemarker-template-engine/src/main/java/org/camunda/templateengines/FreeMarkerScriptEngineFactory.java
  freemarker-template-engine/src/main/resources/META-INF/services/javax.script.ScriptEngineFactory
  freemarker-template-engine/src/test/java/org/camunda/templateengines/engine/FreeMarkerScriptEngineTest.java
  freemarker-template-engine/src/test/java/org/camunda/templateengines/engine/util/Greeter.java
  pom.xml
Labels: ci:e2e, ci:all-as

#4364 fix(engine): remove orphan event subscriptions on process definition redeployment
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java
  engine/src/test/java/org/camunda/bpm/engine/test/concurrency/DeleteProcessDefinitionTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/repository/processWithStartSignalEvent.bpmn20.xml
Labels: ci:all-db

#4376 feat(ci): add support for sql server 2022
  .ci/config/matrices.yaml
Labels: ci:sqlserver
