Repository camunda/camunda-bpm-platform, pull requests merged in 2024-01, with the labels that each got.

#4019 chore(engine-rest, clients): Change sorting param
  clients/java/client/src/main/java/org/camunda/bpm/client/topic/impl/dto/FetchAndLockRequestDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/externaltask/FetchExternalTasksDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ExternalTaskRestServiceInteractionTest.java
Labels: ci:all-as, ci:rest-api, ci:spring-boot

#4006 Try out spring boot 3.2
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/webapps/AbstractWebappUiIT.java
  distro/run/qa/pom.xml
  parent/pom.xml
  qa/integration-tests-webapps/integration-tests/src/main/java/org/camunda/bpm/AbstractWebappUiIntegrationTest.java
  spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/CamundaBpmWebappConfigurationIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/WebappTestApp.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/ChangedAppPathIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/EmptyAppPathIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/RequestTrailingSlashIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/containerbasedauth/ChangedAppPathContainerBasedAuthIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/apppath/containerbasedauth/ContainerBasedAuthTestApp.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/authcache/it/AuthCacheTTLDefaultIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/authcache/it/AuthCacheTTLDisabledIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/authcache/it/AuthCacheTTLValidateAllRequestsIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/CsrfPreventionIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/CookieNameIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteCustomValueIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteDisabledIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteEnabledIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteOptionLaxIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SameSiteOptionStrictIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SecureDisabledIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/csrf/it/properties/SecureEnabledIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/HstsIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/HttpHeaderSecurityDefaultsIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/properties/HttpHeaderSecurityAbsenceIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/properties/HttpHeaderSecurityPresenceIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/headersec/it/properties/HttpHeaderSecurityValueIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/redirect/ResourceLoadingProcessEnginesAppPathCamundaIndexRedirectTest.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/redirect/ResourceLoadingProcessEnginesAppPathCamundaTest.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/redirect/ResourceLoadingProcessEnginesAppPathRootIndexRedirectTest.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/redirect/ResourceLoadingProcessEnginesAppPathRootTest.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/SessionCookieIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/CookieNameIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteCustomValueIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteDisabledIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteEnabledIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteOptionLaxIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SameSiteOptionStrictIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SecureDisabledIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/session/it/properties/SecureEnabledIT.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/camunda/bpm/spring/boot/starter/webapp/filter/util/FilterTestApp.java
Labels: ci:run, ci:spring-boot, bot:java-dependency-check

#4027 chore(parent): increase wait for spring-boot-maven-plugin
  parent/pom.xml
Labels: ci:no-build, ci:spring-boot

#3982 chore(dependency): update joda time
  distro/wildfly/modules/src/main/modules/org/joda/time/2.1/module.xml
  distro/wildfly26/modules/src/main/modules/org/joda/time/2.1/module.xml
  pom.xml
Labels: ci:wildfly, bot:java-dependency-tree, bot:java-dependency-check

#4043 fix(engine): REST API endpoint should use UTF-8 charset
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/mapper/MultipartFormData.java
Labels: ci:tomcat

#4022 chore(integration-tests-engine): Increase Max Job Wait Timeout
  qa/integration-tests-engine/src/test/java/org/camunda/bpm/integrationtest/util/AbstractFoxPlatformIntegrationTest.java
Labels: ci:wildfly

#4014 feat(engine): Introduce operation log for sync message correlations
  engine/src/main/java/org/camunda/bpm/engine/history/UserOperationLogEntry.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ProcessEngineLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractCorrelateMessageCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CorrelateAllMessageCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/CorrelateMessageCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/SynchronousOperationLogProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/UserOperationLogEntryEventEntity.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationUserOperationLogTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/useroperationlog/SyncApiUserOperationLogLimitConfigurationTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationTest.sendMessageProcess.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationTest.testCatchingMessageEventCorrelation.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationTest.testCorrelateAllWithoutMessage.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationTest.testMatchingStartEventAndExecution.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationTest.testMessageStartEventCorrelation.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationTest.testMultipleMessageStartEventsCorrelation.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationTest.waitForMessageProcess.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationUserOperationLogTest.intermediateMessageEvent.bpmn
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/message/MessageCorrelationUserOperationLogTest.messageStartEvent.bpmn
  engine/src/test/resources/org/camunda/bpm/engine/test/history/useroperationlog/SyncApiUserOperationLogLimitConfigurationTest.shouldAllowToConfigureNegativeOne.cfg.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/history/useroperationlog/SyncApiUserOperationLogLimitConfigurationTest.shouldAllowToConfigurePositiveValue.cfg.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/history/useroperationlog/SyncApiUserOperationLogLimitConfigurationTest.shouldThrowExceptionWhenConfigureLowNegativeValue.cfg.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/history/useroperationlog/SyncApiUserOperationLogLimitConfigurationTest.shouldThrowExceptionWhenConfigureZero.cfg.xml
Labels: ci:h2

#3981 chore(dependency): update mybatis
  pom.xml
Labels: ci:all-db, bot:java-dependency-check

#4032 fix(engine): use correct job definition for job log
  engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricJobLogTest.java
Labels: ci:all-db

#4050 feat(cockpit): ease search for process definitions
  webapps/assembly/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processDefinition.xml
  webapps/frontend/ui/cockpit/plugins/base/app/views/processesDashboard/process-definition-search-config.json
Labels: ci:e2e, ci:all-db
