Repository camunda/camunda-bpm-platform, pull requests merged in 2024-09, with the labels that each got.

#4572 fix(modules): oauth2 module should be available for ce and ee
  distro/run/pom.xml
Labels: ci:spring-boot, ci:skipTests

#4574 chore(distro/tomcat/assembly): Add Juel to distro/lib Folder
  distro/tomcat/assembly/assembly.xml
Labels: ci:tomcat

#4526 feat(engine): check transaction isolation level on init
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ConfigurationLogger.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/test/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationTest.java
  engine/src/test/resources/camunda.cfg.skipIsolationLevelCheckEnabled.xml
Labels: ci:all-as, ci:all-db

#4509 feat(cockpit): add rootInstanceId filter to humanTask search
  webapps/frontend/public/app/cockpit/locales/de.json
  webapps/frontend/public/app/cockpit/locales/en.json
Labels: ci:e2e

#4481 feat(run): add spring security oauth2 integration
  distro/run/assembly/pom.xml
  distro/run/modules/oauth2/pom.xml
  distro/run/modules/oauth2/src/main/java/org/camunda/bpm/spring/boot/starter/security/CamundaBpmSpringSecurityDisableAutoConfiguration.java
  distro/run/modules/oauth2/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-starter/starter-security/pom.xml
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaBpmSpringSecurityDisableAutoConfiguration.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaSpringSecurityOAuth2AutoConfiguration.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/ClientsNotConfiguredCondition.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2AuthenticationProvider.java
  spring-boot-starter/starter-security/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-boot-starter/starter-security/src/test/java/my/own/custom/spring/boot/project/SampleApplication.java
  spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/CamundaBpmSampleApplicationTest.java
  spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/CamundaBpmSamplePermitAllApplicationTest.java
Labels: ci:run, ci:spring-boot

#4570 feat(run): add oauth2 identity provider
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaSpringSecurityOAuth2AutoConfiguration.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/OAuth2Properties.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2GrantedAuthoritiesMapper.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProvider.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProviderFactory.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProviderPlugin.java
Labels: ci:default-build, ci:spring-boot, ci:distro

#4582 chore(deps): bump spring boot to 3.3.3
  parent/pom.xml
Labels: ci:spring-boot, bot:java-dependency-check, ci:skipTests

#4563 chore(quarkus): Bump quarkus version to 3.14
  parent/pom.xml
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineConfigFileTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineConfigurationConfigTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineJobExecutorConfigTest.java
  quarkus-extension/engine/deployment/src/test/java/org/camunda/bpm/quarkus/engine/test/config/CamundaEngineProgrammaticAndConfigFileTest.java
  quarkus-extension/engine/deployment/src/test/resources/application.properties
  quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/job-executor-application.properties
  quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/mixed-application.properties
  quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/process-engine-config-application.properties
  quarkus-extension/engine/qa/src/test/resources/application.properties
  quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/CamundaEngineConfig.java
  quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/CamundaJobExecutorConfig.java
  quarkus-extension/engine/runtime/src/main/java/org/camunda/bpm/quarkus/engine/extension/impl/CamundaEngineRecorder.java
Labels: ci:h2, bot:java-dependency-check, ci:skipTests

#4531 chore(database): Bump H2 to 2.2.222
  database/pom.xml
Labels: ci:h2, ci:default-build, ci:migration, bot:java-dependency-check, ci:skipTests

#4420 4214 restarted process instance
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/process-instance/{id}/get.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstance.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ProcessInstantiationBuilderImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/RestartProcessInstancesCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/StartProcessInstanceAtActivitiesCmd.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricProcessInstanceEventEntity.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.db2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.h2.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mariadb.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mssql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.mysql.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.oracle.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/drop/activiti.postgres.drop.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RestartProcessInstanceAsyncTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/RestartProcessInstanceSyncTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceStateTest.java
Labels: ci:all-as

#4560 Camunda Run: Offer a common way to disable the generated wadl of the rest api
  distro/run/assembly/resources/default.yml
  distro/run/assembly/resources/production.yml
  distro/run/core/src/main/java/org/camunda/bpm/run/CamundaBpmRunRestConfiguration.java
  distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunProperties.java
  distro/run/core/src/main/java/org/camunda/bpm/run/property/CamundaBpmRunRestProperties.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/rest/WadlDisabledTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/rest/WadlEnabledTest.java
  distro/run/core/src/test/java/org/camunda/bpm/run/test/config/rest/WadlUnsetTest.java
Labels: ci:rest-api, ci:run

#4614 chore(webapps): bump webpack to the latest version
  webapps/frontend/package-lock.json
  webapps/frontend/package.json
Labels: ci:e2e, ci:skipTests

#4623 chore(deps): bump Tomcat to 10.1.29
  parent/pom.xml
Labels: ci:tomcat, ci:webapp-integration, bot:java-dependency-check

#4139 chore(ci): introduce declarative pod specs
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  .ci/daily/Jenkinsfile
  Jenkinsfile
  parent/pom.xml
Labels: ci:e2e, ci:jdk, ci:rest-api, ci:webapp-integration

#4610 Test: hybrid jdk declarative and label based
  .ci/config/matrices.yaml
  .ci/config/stage-types.yaml
  engine-rest/docs/pom.xml
Labels: ci:default-build, ci:jdk, ci:skipTests

#4634 chore(ci): fix merge conflicts
  .ci/config/stage-types.yaml
Labels: ci:no-build

#4603 feat(oauth2): revalidate access tokens
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaSpringSecurityOAuth2AutoConfiguration.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/AuthorizeTokenFilter.java
Labels: ci:run, ci:spring-boot

#4635 chore(ci): migrate distro-maven and public-nexus stages
  .ci/daily/Jenkinsfile
Labels: ci:default-build, ci:skipTests

#4636 chore(ci/daily): fix `stage-restapi-docs` by adding ssh
  .ci/daily/Jenkinsfile
Labels: ci:no-build

#4604 feat(oauth2): add sso logout support
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/CamundaSpringSecurityOAuth2AutoConfiguration.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/OAuth2Properties.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/SsoLogoutSuccessHandler.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/plugin/SsoLogoutPluginConstants.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/plugin/admin/SsoLogoutAdminPlugin.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/plugin/admin/SsoLogoutAdminPluginRootResource.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/plugin/cockpit/SsoLogoutCockpitPlugin.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/plugin/cockpit/SsoLogoutCockpitPluginRootResource.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/plugin/tasklist/SsoLogoutTasklistPlugin.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/plugin/tasklist/SsoLogoutTasklistPluginRootResource.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/plugin/welcome/SsoLogoutWelcomePlugin.java
  spring-boot-starter/starter-security/src/main/java/org/camunda/bpm/spring/boot/starter/security/oauth2/impl/plugin/welcome/SsoLogoutWelcomePluginRootResource.java
  spring-boot-starter/starter-security/src/main/resources/META-INF/services/org.camunda.bpm.admin.plugin.spi.AdminPlugin
  spring-boot-starter/starter-security/src/main/resources/META-INF/services/org.camunda.bpm.cockpit.plugin.spi.CockpitPlugin
  spring-boot-starter/starter-security/src/main/resources/META-INF/services/org.camunda.bpm.tasklist.plugin.spi.TasklistPlugin
  spring-boot-starter/starter-security/src/main/resources/META-INF/services/org.camunda.bpm.welcome.plugin.spi.WelcomePlugin
  spring-boot-starter/starter-security/src/main/resources/plugin-webapp/sso-logout-plugin/app/plugin.css
  spring-boot-starter/starter-security/src/main/resources/plugin-webapp/sso-logout-plugin/app/plugin.js
Labels: ci:run, ci:spring-boot

#4624 4620 add historic process instance query to execute modification async
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/ModificationDto.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/ModificationDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/impl/ModificationRestServiceImpl.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/ModificationRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/impl/ModificationBuilderImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/cmd/AbstractModificationCmd.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/ModificationBuilder.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ModificationExecutionAsyncTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/runtime/ModificationExecutionSyncTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.syncAfterOneTaskProcess.bpmn20.xml
Labels: ci:default-build, ci:rest-api

#4590 4587 add incident id in filter to historic process instance query
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/failingProcessAfterUserTaskCreateOneIncident.bpmn20.xml
Labels: ci:all-db, ci:default-build, ci:rest-api

#4619 feature(engine): add activityIdIn filter to HistoricProcessInstanceQuery
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.failingSubprocessWithAsyncBeforeTask.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.subprocessWithAsyncBeforeTask.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.testHistoricProcessInstanceQueryActivityIdInWithIncident.bpmn
Labels: ci:all-db, ci:default-build, ci:rest-api

#4640 chore(rest): expose batch id for job and historic job log to REST API
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/{id}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/get.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockJobBuilder.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceInteractionTest.java
Labels: ci:rest-api

#4625 chore(engine): add batchId for job and jobLog
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/models/org/camunda/bpm/engine/rest/dto/runtime/JobDto.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/{id}/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/post.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/get.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricJobLogDto.java
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockJobBuilder.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricJobLogRestServiceInteractionTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricJobLog.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/event/HistoricJobLogEvent.java
  engine/src/main/java/org/camunda/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/jobexecutor/JobDeclaration.java
  engine/src/main/java/org/camunda/bpm/engine/impl/persistence/entity/JobEntity.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/Job.java
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.engine.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/db2_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/h2_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mariadb_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mssql_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/mysql_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/oracle_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/db/upgrade/postgres_engine_7.21_to_7.22.sql
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricJobLog.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/JobEntityAndJobLogBatchIdTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/util/BatchRule.java
Labels: ci:all-db

#4647 fix(engine): Add missing HistoryLevel annotation to test
  engine/src/test/java/org/camunda/bpm/engine/test/history/JobEntityAndJobLogBatchIdTest.java
Labels: ci:no-build, ci:skipTests

#4612 chore(quarkus): Bump quarkus version to 3.15
  parent/pom.xml
Labels: ci:h2, bot:java-dependency-check, ci:skipTests

#4654 chore(license-book): update license book for 7.22.0
  distro/license-book/src/main/resources/license-book.txt
Labels: ci:no-build

#4662 chore(release): update German translation
  webapps/frontend/public/app/admin/locales/de.json
  webapps/frontend/public/app/cockpit/locales/de.json
  webapps/frontend/public/app/tasklist/locales/de.json
  webapps/frontend/public/app/welcome/locales/de.json
Labels: ci:no-build
