Repository camunda/camunda-bpm-platform, pull requests merged in 2024-10, with the labels that each got.

#4663 chore(ci): remove postgresql_132 CI
  .ci/config/matrices.yaml
Labels: ci:postgresql

#4677 chore(database): activate oracle23 in old-engine stage in CI
  .ci/config/matrices.yaml
  qa/test-old-engine/pom.xml
Labels: ci:h2, ci:migration, ci:oracle, ci:rolling-update

#4681 chore(engine): Bump Spring Framework
  parent/pom.xml
Labels: ci:e2e, ci:all-as, ci:spring-boot, ci:wildfly, bot:java-dependency-check, bot:backport:7.20, bot:backport:7.21, bot:backport:7.22

#4742 fix(mssql): replace or with union in external task to improve performance
  engine/src/main/java/org/camunda/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Authorization.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/authorization/externaltask/ExternalTaskQueryAuthorizationTest.java
Labels: ci:all-db, bot:backport:7.21, bot:backport:7.22

#4747 chore(spring-boot): Bump Spring Boot version to 3.3.5
  parent/pom.xml
Labels: ci:all-as, ci:spring-boot, scope:spring-boot, bot:java-dependency-check, bot:backport:7.22
