Repository camunda/camunda-bpm-platform, pull requests merged in 2024-08, with the labels that each got.

#4456 fix(webapp): fix formjs date picker error
  webapps/frontend/webpack.common.js
Labels: ci:e2e

#4510 chore(engine): Remove Unnecessary JBoss Artifacts
  engine/pom.xml
Labels: ci:all-as, ci:wildfly

#4497 chore(distro/run): Remove Swagger from camunda-run
  Jenkinsfile
  distro/run/assembly/assembly.xml
  distro/run/assembly/pom.xml
  distro/run/assembly/resources/README.txt
  distro/run/assembly/resources/run.bat
  distro/run/assembly/resources/run.sh
  distro/run/core/pom.xml
  distro/run/modules/swaggerui/pom.xml
  distro/run/modules/swaggerui/src/main/java/org/camunda/bpm/run/swaggerui/CamundaSwaggerUIConfiguration.java
  distro/run/modules/swaggerui/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  distro/run/modules/swaggerui/ui/.gitignore
  distro/run/modules/swaggerui/ui/package-lock.json
  distro/run/modules/swaggerui/ui/package.json
  distro/run/modules/swaggerui/ui/src/favicon.ico
  distro/run/modules/swaggerui/ui/src/index.html
  distro/run/modules/swaggerui/ui/src/index.js
  distro/run/modules/swaggerui/ui/src/style.css
  distro/run/modules/swaggerui/ui/tasks/license.js
  distro/run/modules/swaggerui/ui/tasks/licenses/LICENSE_format
  distro/run/modules/swaggerui/ui/tasks/licenses/LICENSE_toggle-selection
  distro/run/modules/swaggerui/ui/webpack.config.js
  distro/run/pom.xml
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ComponentAvailabilityIT.java
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ProductionConfigurationIT.java
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/swaggerui/SwaggerUIGetRequestIT.java
Labels: ci:run, ci:skipTests

#4535 chore(project): Remove Swagger References
  .ci/config/stage-types.yaml
  CONTRIBUTING.md
Labels: ci:jdk, ci:skipTests

#4536 fix(identity/ldap): adjust ldap error handling
  engine-plugins/identity-ldap/src/main/java/org/camunda/bpm/identity/impl/ldap/LdapIdentityProviderSession.java
Labels: ci:default-build

#4524 chore(webapps): bump requirejs to latest - 2.3.7
  webapps/frontend/package-lock.json
  webapps/frontend/package.json
Labels: ci:e2e

#4534 chore(deps): bump tomcat to versions 9.0.90 and 10.1.25
  parent/pom.xml
Labels: ci:run, ci:spring-boot, ci:tomcat, bot:java-dependency-check

#4522 chore(databases): add oracle 23ai
  .ci/config/matrices.yaml
  database/pom.xml
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSession.java
  engine/src/test/java/org/camunda/bpm/engine/test/persistence/ConnectionPersistenceExceptionTest.java
  qa/test-old-engine/pom.xml
Labels: ci:no-build, ci:oracle, ci:skipTests

#4542 chore(db): use uppercase DB property names
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricActivityInstance.xml
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricCaseActivityInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/persistence/DatabaseNamingConsistencyTest.java
  webapps/assembly/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processDefinition.xml
  webapps/assembly/src/test/java/org/camunda/bpm/webapp/impl/engine/WebappsDatabaseNamingConsistencyTest.java
Labels: ci:all-db, ci:default-build, ci:webapp-integration, bot:backport:7.20, bot:backport:7.21

#4544 remove(tests): remove telemetry configuration property
  qa/test-old-engine/pom.xml
  quarkus-extension/README.md
  quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/mixed-application.properties
  quarkus-extension/engine/deployment/src/test/resources/org/camunda/bpm/quarkus/engine/test/config/process-engine-config-application.properties
Labels: ci:no-build, ci:postgresql

#4562 chore(deps): revert to graalvm 21.1.0
  parent/pom.xml
Labels: ci:all-as, ci:webapp-integration, bot:java-dependency-check

#4506 feat(engine): Add variableNameLike filter to historic detail REST API
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-detail-query-params.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricDetailQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricDetailRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricDetailQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricDetailQueryImpl.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricDetail.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricDetailQueryTest.java
Labels: ci:h2

#4478 feat(run): add spring security module
  bom/camunda-only-bom/pom.xml
  clients/java/client/pom.xml
  distro/run/assembly/assembly.xml
  distro/run/assembly/pom.xml
  distro/run/assembly/resources/run.bat
  distro/run/assembly/resources/run.sh
  distro/run/modules/oauth2/pom.xml
  distro/run/modules/oauth2/src/main/java/org/camunda/bpm/spring/boot/starter/security/CamundaBpmSpringSecurityDisableAutoConfiguration.java
  distro/run/modules/oauth2/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  distro/run/pom.xml
  distro/run/qa/integration-tests/src/test/java/org/camunda/bpm/run/qa/ComponentAvailabilityIT.java
  parent/pom.xml
  spring-boot-starter/pom.xml
  spring-boot-starter/starter-security/pom.xml
  spring-boot-starter/starter-security/src/test/java/my/own/custom/spring/boot/project/SampleApplication.java
  spring-boot-starter/starter-security/src/test/java/my/own/custom/spring/boot/project/SamplePermitAllApplication.java
  spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/CamundaBpmSampleApplicationTest.java
  spring-boot-starter/starter-security/src/test/java/org/camunda/bpm/spring/boot/starter/security/CamundaBpmSamplePermitAllApplicationTest.java
  spring-boot-starter/starter-security/src/test/resources/logback-test.xml
Labels: ci:run, ci:spring-boot, bot:java-dependency-tree, bot:java-dependency-check

#4568 fix(ci): skip starter-security module for jdk11 stages
  .ci/config/stage-types.yaml
Labels: ci:jdk
