Repository camunda/camunda-bpm-platform, pull requests merged in 2024-07, with the labels that each got.

#4479 chore(qa): add `tomcat9-runtime` to distro profile
  qa/pom.xml
Labels: ci:no-build

#4498 chore(tomcat-runtime): Fix webapp-IT-tomcat-10-h2 failing tests
  qa/tomcat-runtime/pom.xml
Labels: ci:tomcat, ci:webapp-integration

#4500 chore(parent): Bump Quarkus to Version 3.85
  parent/pom.xml
Labels: ci:h2, ci:default-build

#4503 chore(parent): Bump Graalvm to Version 21.3.11
  parent/pom.xml
Labels: ci:all-as, bot:java-dependency-check
