Repository camunda/camunda-bpm-platform, pull requests merged in 2025-07, with the labels that each got.

#5289 revert(webapps): unintended changes
  Jenkinsfile
  webapps/assembly/src/main/runtime/develop/resources/META-INF/processes.xml
  webapps/assembly/src/main/runtime/test/resources/META-INF/processes.xml
  webapps/assembly/src/test/resources/camunda-test-engine.cfg.xml
  webapps/assembly/src/test/resources/camunda.cfg.prefix.xml
Labels: ci:h2

#5292 chore(renovate): whitelist `commons-lang3` for automatic updates
  .github/renovate.json
Labels: ci:no-build

#5310 chore(deps) bump spring & tomcat
  parent/pom.xml
Labels: bot:java-dependency-check, ci:all
