Repository camunda/camunda-bpm-platform, pull requests merged in 2025-06, with the labels that each got.

#5239 chore(deps): update to latest tomcat
  parent/pom.xml
Labels: ci:jdk, ci:rest-api, ci:tomcat, ci:webapp-integration, bot:java-dependency-check

#5048 fix(engine): Adjust flaky test to only execute jobs under test
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/metrics/JobExecutorMetricsTest.java
Labels: ci:h2

#5257 feat(engine, engine-rest-core) Add a query criteria to retrieve all executing jobs
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/job-definition-query-params.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/job-query-params.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/runtime/JobQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/JobRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/helper/MockProvider.java
  engine/src/main/java/org/camunda/bpm/engine/impl/JobQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/runtime/JobQuery.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/Job.xml
  engine/src/test/java/org/camunda/bpm/engine/test/api/mgmt/JobQueryTest.java
  webapps/frontend/camunda-bpm-sdk-js/lib/api-client/resources/job.js
Labels: ci:e2e, ci:postgresql, ci:rest-api, ci:tomcat
