Repository camunda/camunda-bpm-platform, pull requests merged in 2025-02, with the labels that each got.

#4912 feat(webapps): Display business key in called process instances tab
  webapps/assembly/src/main/resources/org/camunda/bpm/cockpit/plugin/base/queries/processInstance.xml
  webapps/assembly/src/test/java/org/camunda/bpm/cockpit/plugin/base/ProcessInstanceResourceTest.java
  webapps/assembly/src/test/resources/processes/two-parallel-call-activities-calling-different-process.bpmn
  webapps/frontend/public/app/cockpit/locales/de.json
  webapps/frontend/public/app/cockpit/locales/en.json
  webapps/frontend/ui/cockpit/plugins/base/app/views/processInstance/called-process-instance-table.html
  webapps/frontend/ui/cockpit/plugins/base/app/views/processInstance/calledProcessInstanceTable.js
Labels: ci:webapp-integration

#4926 fix(webapps/tasklist): render task if no filter exists
  webapps/frontend/ui/tasklist/client/scripts/tasklist/directives/cam-tasklist-tasks.js
Labels: ci:e2e, bot:backport:7.22

#4920 feat(queryAPI): add filter for instances with jobs retrying in java API
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
  engine/src/test/resources/org/camunda/bpm/engine/test/api/history/testInstancesWithJobsRetrying.bpmn20.xml
  engine/src/test/resources/org/camunda/bpm/engine/test/api/mgmt/ManagementServiceTest.testGetJobExceptionStacktrace.bpmn20.xml
Labels: ci:all-db, ci:default-build

#4946 chore(deps): bump to feel-scala 1.19.1
  pom.xml
Labels: ci:h2, bot:java-dependency-check, ci:skipTests

#4862 chore(engine): bump `spring-beans` to 6
  engine/pom.xml
  engine/src/test/java/org/camunda/bpm/container/impl/jmx/deployment/BpmPlatformXmlLocationTest.java
  engine/src/test/java/org/camunda/bpm/container/impl/jmx/deployment/MockInitialContextFactory.java
  engine/src/test/java/org/camunda/bpm/container/impl/jmx/deployment/MockInitialContextRule.java
  engine/src/test/java/org/camunda/bpm/engine/test/api/history/HistoryCleanupOnEngineBootstrapTest.java
  engine/src/test/resources/jndi.properties
  webapps/assembly/src/main/java/org/camunda/bpm/webapp/impl/security/filter/PathFilterRule.java
Labels: ci:all-as, bot:java-dependency-check

#4950 chore(CI): archive Tomcat server log for flaky test investigation
  Jenkinsfile
Labels: ci:tomcat, scope:ci, bot:backport:7.20, ci:distro, bot:backport:7.21, bot:backport:7.22

#4897 feat(engine): HistoricProcessInstanceQuery processInstanceIdNotIn filter
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
  engine/src/main/java/org/camunda/bpm/engine/history/HistoricProcessInstanceQuery.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
  engine/src/main/java/org/camunda/bpm/engine/impl/util/CompareUtil.java
  engine/src/main/resources/org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/camunda/bpm/engine/test/history/HistoricProcessInstanceTest.java
  webapps/frontend/camunda-commons-ui/lib/widgets/inline-field/cam-widget-inline-field.html
  webapps/frontend/camunda-commons-ui/lib/widgets/inline-field/cam-widget-inline-field.js
  webapps/frontend/camunda-commons-ui/lib/widgets/search-pill/cam-widget-search-pill.html
  webapps/frontend/public/app/cockpit/locales/de.json
  webapps/frontend/public/app/cockpit/locales/en.json
Labels: ci:e2e

#4922 feat(restAPI): add withJobsRetrying to rest and openAPI
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
  engine-rest/engine-rest/src/test/java/org/camunda/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
Labels: ci:rest-api

#4947 chore(distro): bump tomcat version to 10.1.36 and 9.0.100
  parent/pom.xml
Labels: ci:run, ci:spring-boot, ci:tomcat, ci:webapp-integration, bot:java-dependency-check, bot:backport:7.20, ci:skipTests, bot:backport:7.21, bot:backport:7.22

#4957 fix(engine-rest): fix parsing processInstanceIdNotIn
  engine-rest/engine-rest/src/main/java/org/camunda/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
  engine/src/main/java/org/camunda/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
Labels: ci:rest-api
