Repository camunda/camunda-bpm-platform, pull requests merged in 2025-09, with the labels that each got.

#5386 fix(openApi): add missing quotation marks
  engine-rest/engine-rest-openapi/src/main/templates/paths/authorization/create/post.ftl
Labels: bot:backport:7.23

#5401 chore(github): add workarounds section to bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: ci:no-build

#5435 chore(quarkus): support 3.27.0 LTS
  parent/pom.xml
Labels: ci:h2, bot:java-dependency-check
