Repository camunda/camunda-bpm-platform, pull requests merged in 2025-08, with the labels that each got.

#5263 chore(distro): add support for WildFly 37
  distro/wildfly/assembly/src/wildfly/standalone-full.xml
  distro/wildfly/assembly/src/wildfly/standalone.xml
  distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/deployment/processor/ModuleDependencyProcessor.java
  distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/extension/handler/EnhancedQueueExecutorService.java
  distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/extension/handler/JobExecutorAdd.java
  distro/wildfly/subsystem/src/main/java/org/camunda/bpm/container/impl/jboss/service/MscExecutorService.java
  distro/wildfly/subsystem/src/test/java/org/camunda/bpm/container/impl/jboss/test/JBossSubsystemXMLTest.java
  parent/pom.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml
  qa/wildfly-runtime/src/main/wildfly/domain/configuration/host.xml
  qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
Labels: ci:jbosseap, ci:wildfly, bot:java-dependency-check

#5285 test(engine): add test for cron expressions
  engine/pom.xml
  engine/src/main/java/org/camunda/bpm/engine/impl/calendar/CronExpression.java
  engine/src/main/java/org/camunda/bpm/engine/impl/calendar/CronTimer.java
  engine/src/main/java/org/camunda/bpm/engine/impl/calendar/CycleBusinessCalendar.java
  engine/src/test/java/org/camunda/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
  engine/src/test/java/org/camunda/bpm/engine/test/standalone/calendar/CycleBusinessCalendarTest.java
  internal-dependencies/pom.xml
  parent/pom.xml
Labels: ci:all-db, ci:default-build, ci:jdk, ci:rest-api

#5360 fix(webapps): use word-break: break-all in .tooltip
  webapps/frontend/camunda-commons-ui/resources/less/shared/base.less
Labels: ci:e2e, bot:backport:7.23

#5372 chore(webapps): add tracking info to eol links
  distro/camunda-welcome/index.html
  webapps/frontend/public/app/admin/locales/de.json
  webapps/frontend/public/app/admin/locales/en.json
  webapps/frontend/public/app/cockpit/locales/de.json
  webapps/frontend/public/app/cockpit/locales/en.json
  webapps/frontend/public/app/tasklist/locales/de.json
  webapps/frontend/public/app/tasklist/locales/en.json
  webapps/frontend/public/app/welcome/locales/de.json
  webapps/frontend/public/app/welcome/locales/en.json
Labels: ci:e2e, bot:backport:7.23

#5350 fix(db2): update to modern pagination for DB2
  engine/src/main/java/org/camunda/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
Labels: ci:db2, bot:backport:7.22, bot:backport:7.23, ci:all
